### ISSUE TITLE
Is it possible to use my own graphics?

### ISSUE THREAD

**Issue by SnugglePilot** [nguyenquyhy/Flight-Tracker-StreamDeck#10]
I would love the ability to assign a "true" graphic and a "false" graphic to use, so I can have my own button graphics - instead of using the generic toggle graphics.

**Comment by nguyenquyhy** [comment]
It should be possible. I'll see how to add this in.

**Comment by rmroc451** [comment]
Cant you just put a different graphic in the asset folder, of the plugin, that you want to replace? Its a work around for now.  As long as you replace and use the same names, you should be good.

**Comment by SnugglePilot** [comment]
@rmroc451 I don't want to replace it outright, I want to use different graphics for different buttons (each with different lit/unlit states). eg; in some planes I want to use the included button to toggle things in airliners, but for my C172 I want to replace the art with a giant red switch for the alternator/battery switches.

**Comment by rmroc451** [comment]
Yeah, i have something similar setup on my repo hard-coded to alt images, but I can easily adjust that to try to load an image from a path you specify.

I'll see if I can implement that tomorrow morning and release a subrelease with it on my repo. I can pr it over to this one then if we like it :)

**Comment by rmroc451** [comment]
Also have this ready, when the PR for my master gets merged, we can PR this then:

https://github.com/rmroc451/Flight-Tracker-StreamDeck/commit/16178b1305c74dff78f56a036d4b018504bf09ce

**Comment by nguyenquyhy** [comment]
Implemented in version 0.3. https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/releases/tag/v0.3
