### ISSUE TITLE
The new MobiFlight GNS 530 example profile doesn't work.

### ISSUE THREAD

**Issue by arthurfuxake** [nguyenquyhy/Flight-Tracker-StreamDeck#101]
The new MobiFlight GNS 530 example profile doesn't work because it's using MF_ instead of MOBIFLIGHT_

Works perfectly once corrected.

**Comment by rmroc451** [comment]
Good call, forgot about that when @nguyenquyhy asked me to update the structure entries.

Thanks for pointing that out!

**Comment by rug4ever** [comment]
do you have a version for the g1000 or g3000 
a profil

pls send

**Comment by rmroc451** [comment]
@rug4ever nope, I just slapped together the quick demo of how you could use the mobiflight events so folks could see how to use them and quickly surmise its awesome :)
