### ISSUE TITLE
MobiFlight AS3000 TSC Horizontal BottomKnob Increment

### ISSUE THREAD

**Issue by Jovian657** [nguyenquyhy/Flight-Tracker-StreamDeck#102]
Stream Deck Plugin v0.22 and MSFS 1.11.7.0

Thanks for adding the awesome MobiFlight capability. I noticed the following on the TBM 930. I created two generic toggle buttons for:

MOBIFLIGHT_AS3000_TSC_Horizontal_BottomKnob_Small_INC
MOBIFLIGHT_AS3000_TSC_Horizontal_BottomKnob_Small_DEC

When I use the StreamDeck toggle button to increase or decrease the MFD map range, I get the following range sequence in nautical miles: 0.5, 2, 5, 15, 35, 100, 200.

However, when I use the virtual cockpit to do the same, I get the following range sequence 0.5, 1, 2, 3, 5, 10, 15, 20, 35, 50, 100, 150, 200.

It seems that the StreamDeck toggle button is incrementing by plus or minus two-steps instead of only one-step. Thank you for your consideration.

**Comment by rug4ever** [comment]
Hello,

If you can send your complete Variable for the TBM 930

and do you have a Setup for the G1000 ?

Thx

**Comment by rmroc451** [comment]
we send one increment per button press. Are you long holding or single pressing @Jovian657?

If it does this while single pressing, that would be an issue with the MobiFlight wasm handling the inc/dec calls.

**Comment by Jovian657** [comment]
@rug4ever and @rmroc451 Thank you for your quick replies. 

@rug4ever Here is a screenshot for the generic toggle button for MOBIFLIGHT_AS3000_TSC_Horizontal_BottomKnob_Small_DEC which I called MFD -. Unfortunately, I am currently not using the G1000. 

![SD_Dec](https://user-images.githubusercontent.com/74513907/102749517-2732d280-4332-11eb-9a4c-6067de0d5a6f.jpg)

The generic toggle button for MOBIFLIGHT_AS3000_TSC_Horizontal_BottomKnob_Small_INC is in the same format.

@rmroc451 I am single pressing.

Some new observations.
1. Reboot PC.
2. StreamDeck button properly steps by one.
3. I thought the problem was fixed by a reboot.
4. Reboot PC
5. StreamDeck button unfortunately steps by two again.
6. Reboot PC
7. StreamDeck button properly steps by one.
8. Issue seems to be intermittent.

There is a second map in the TBM 930 in the PFD.  I created two new generic toggle buttons to change the map range in the PFD using

MOBIFLIGHT_AS3000_PFD_SOFTKEYS_1,
MOBIFLIGHT_AS3000_PFD_SOFTKEYS_2

The PFD map range correctly steps by one with no issues (works great!). Not sure what is happening with the MFD map range.

**Comment by Jovian657** [comment]
New observations - based on two ways to activate the MFD map range. 

1. The first is to use the Virtual Cockpit to press softkey 2 on the TSC (with the mouse) to switch to MFD mode in the TSC. 

2. The second is to use MOBIFLIGHT_AS3000_TSC_Horizontal_SoftKey_2 in StreamDeck.

If one uses the first way, then the map range properly steps by one (preferred).  If one uses the second way, then the map range steps by two (not preferred).

**Comment by nguyenquyhy** [comment]
When it comes to MobiFlight events, we have no visibility under the hood as the code for the WASM module is not released. We simply trigger the event when the button is clicked. I think it would be more beneficial if you ask in MobiFlight forum about this.
