### ISSUE TITLE
MASTER IGNITION SWITH

### ISSUE THREAD

**Issue by Kaledozor** [nguyenquyhy/Flight-Tracker-StreamDeck#103]
je n'arrive pas à faire fonctionnner la fonction 'MASTER IGNITION SWITCH' sur le C152 et C172.

![image](https://user-images.githubusercontent.com/74936407/102708262-d309fd00-42f5-11eb-893d-18b26b1cc871.png)

Le FEEDBACK fonctionne bien mais je n'arrive pas à activer depuis le Streamdeck.

**Comment by rmroc451** [comment]
Are you trying to toggle through the starter toggle the avionics master switches (white ones)?

The ignition switch is indexed and settable, also these are available to use https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/master/FlightStreamDeck.Core/Structs.cs#L684-L690.

I had a subfolder with buttons for each key position (off, L, R, Both, start) and then you can touch each one to set the switch position.

It's been on my mind to give folks a settable list that it fires a command from a user defined sequence each time someone presses the button.  and a long press would go backward...  We'll see how far I get on that vs the backlog here over the next two weeks while on "vacation" :)

**Comment by Kaledozor** [comment]
👍👍

**Comment by rmroc451** [comment]
Does that solve the issue, can I close this then?

**Comment by rmroc451** [comment]
Closing via https://forums.flightsimulator.com/t/stream-deck-button-box-my-c172-implementation/229137/282?u=rmroc451

**Comment by Kaledozor** [comment]
In fact it works with:
![image](https://user-images.githubusercontent.com/74936407/102724822-89a5c600-4366-11eb-9c3e-8c0e269d8deb.png)


The 2 switches at the same time but it does the job.
