### ISSUE TITLE
Allow gauges to have min/max values set from sim variables

### ISSUE THREAD

**Issue by linmar22** [nguyenquyhy/Flight-Tracker-StreamDeck#109]
This would make stuff like flap position indicators and fuel gauges aircraft-agnostic.

**Comment by Andywmm9** [comment]
I vote for this too.

**Comment by nguyenquyhy** [comment]
There is already a PR #100 (great number) for this. I'll test and try to release it soon.  😁

**Comment by nguyenquyhy** [comment]
I tag the wrong PR. This was implemented in #78 and released in version 0.20.
