### ISSUE TITLE
Cessna 208B Grand Caravan Fuel selector switches

### ISSUE THREAD

**Issue by mikeB2210** [nguyenquyhy/Flight-Tracker-StreamDeck#110]
Using FSUIPC7 I get a Toggel command "Fuel_Selector_Set". Is it possible to add this so I I can add a Stream Deck Button?
Thanks in advance.

Michael

**Comment by nguyenquyhy** [comment]
`FUEL_SELECTOR_SET` is added in the next version.

**Comment by nguyenquyhy** [comment]
Added in version 0.23.
