### ISSUE TITLE
Tap to Sync Current Heading

### ISSUE THREAD

**Issue by Jovian657** [nguyenquyhy/Flight-Tracker-StreamDeck#113]
Stream Deck Plugin v0.22 and MSFS 1.12.13.0

It would be great to have a tap button to -Sync Current Heading- as an alternative to using the preset toggle button for AP Heading which requires a hold to -Sync Current Heading-.

I tried to program a generic toggle button but was unable to find a supported SimConnect event on the supported-event-list. Please advise if it is on the list with a non-intuitive name. Thanks!

**Comment by nguyenquyhy** [comment]
The event is HEADING_BUG_SET. I'll add it and some related one in the next version.

**Comment by Jovian657** [comment]
@nguyenquyhy Thanks. FYI, I tried HEADING_BUG_SET in a generic toggle button but it had no effect.

**Comment by nguyenquyhy** [comment]
Yep you need to wait for the next update.

**Comment by nguyenquyhy** [comment]
Done in version 0.23. You can use event `HEADING_BUG_SET` and parameter `PLANE HEADING DEGREES MAGNETIC`.

**Comment by Jovian657** [comment]
Works perfectly. Thanks!
