### ISSUE TITLE
COM and NAV Button Improvements

### ISSUE THREAD

**Issue by jplewis01** [nguyenquyhy/Flight-Tracker-StreamDeck#114]
I would like to propose some Look and Feel improvements for the Com and Nav Buttons.
To be clear these are look and feel improvements only. The implemented logic works great!

### 1/ NAV & COM Button Background Customization.
 As a user I would like to be able to customize the background for the COM and NAV Buttons to allow custom backgrounds for each type. 
Implement the capability to use the Streamdeck ICON functionality as the background for COM and NAV buttons. Currently it seems the ICON Layer overlays COM and NAV Button text layers. When a background ICON is loaded (Stream Deck Native method) it sits on top of the COM Text completely obscuring the text. This is different to how the Preset Toggle button layout works see examples below
![image](https://user-images.githubusercontent.com/22717408/103227124-840a2c00-48e2-11eb-8534-373fa312cb4a.png)
![image](https://user-images.githubusercontent.com/22717408/103227148-8e2c2a80-48e2-11eb-9cc6-ba2a603df964.png)
	In these two examples I created an on and off Icon with a black background behind the display values.
	I would very much like to replicate that capability in the COM and NAV Buttons instead of the Default Grey Background that they currently display. 
	
### 2/ NAV and COM Readability improvements. 
As a user I would like to see improved readability of the NAV and COM Text items. This will allow easier reading especially at slightly longer distances

**Button Label**
- Use a font with a slightly heavier stroke weight and a slightly larger font point size.
- Move the placement of the label NAV1 or COM2 slightly higher on the button.

**Active and Standby Frequencies**
- Use a Slightly heavier font stroke weight for both frequencies with a slightly larger font point size.
- In addition to the active frequency being Yellow/Green, use a bold font for the active frequency to improve active frequency recognition. Optional: Add an active item indicator to the left of the active frequency

![image](https://user-images.githubusercontent.com/22717408/103227264-c16eb980-48e2-11eb-8796-2d6ae98cb61d.png)
		Proposed Changes(left) vs. Current Design (right).

- 	Background: User defined Icon file allowing the addition of anything that Streamdeck supports
- 	Larger Heavy Font for Button Title (COM1)
- 	Larger Yellow Bold Font for active frequency
- 	Small Yellow Triangle indicating the active Frequency
- 	Larger White (Std weight) font for the standby frequency
 
No changes to functional behavior

**Comment by rug4ever** [comment]
can i get the Icons
the New Version vor 1 and 10 with hold its so nice.
the streamdeck its so cool in msfs2020

**Comment by nguyenquyhy** [comment]
COM/NAV background support and some alignment improvement is released in v0.31.
