### ISSUE TITLE
Request: function to open the numpad for COM/NAV without displaying frequency values

### ISSUE THREAD

**Issue by vicentezc** [nguyenquyhy/Flight-Tracker-StreamDeck#115]
**Is your feature request related to a problem? Please describe.**

This request is not related to a problem, I am raising it because I have been doing customization (modified ImageLogic.cs locally) and I would like to have a way to open the numpad for COM1/2 & NAV1/2 but without the frequencies being displayed in the button.
![Screenshot 2020-12-29 174440](https://user-images.githubusercontent.com/74352566/103299851-cd02d300-49fd-11eb-9760-1390e422cdd8.png)

**Describe the solution you'd like**

In the selected button in the image above (COM1), I would like to access the numpad for COM1, but I would like to have only "COM1" displayed, without the active/stby frequencies being displayed.
I managed to update ImageLogic.cs on my side to get there, but this would require modifying much more and don't know the project structure well.
This would require an extra option "Display/Hide frequencies" for NAV & COM functions, and maybe some tweaks in the display.

**Describe alternatives you've considered**

Another possibility would be to allow the numpad to be accessible with a variable maybe? In that case, when clicking on the button where the Standby frequency, it could open the numpad for a given COM or NAV. But this is probably more complex.

Another thing I tried was to simply add a "Switch Profile" function but all the logic is not triggered when simply switching profiles in Stream Deck

**Additional context**

As I mentioned above, I updated the method GetNavComImage in ImageLogic.cs to tweak the display with my preference, so this is why it's different than the default.

Thanks for the great work!

**Comment by vicentezc** [comment]
By the way, if you could tell me which files to modify to:
* Add a new option in the stream deck menu for COM/NAV
* Implement this option in the core
* Update the display of the button (assuming this would be ImageLogic.cs and the GetNavComImage method would require a new parameter)

I could give it a try and submit a pull request.
Cheers!

**Comment by nguyenquyhy** [comment]
Does this mean the button shows a static image? If it is so, a much simpler way would be to use the `Set from File` function of Stream Deck. It basically overwrites the plugin.

![image](https://user-images.githubusercontent.com/1560418/103303238-6b178d00-4a40-11eb-8972-9f3af1f56d1d.png)

**Comment by vicentezc** [comment]
That's exactly what I needed, your suggestion is working perfectly for me!
Thanks a lot for the help!
Cheers!
