### ISSUE TITLE
Possible Syntax Error in structs.cs  for ver 23???

### ISSUE THREAD

**Issue by jplewis01** [nguyenquyhy/Flight-Tracker-StreamDeck#118]
I noticed today the in the Toggle variables section of Structs.cs that the Final Variable name in the data structure has no trailing comma which I expected. In the Toggle Events section, the final event name does have a trailing comma. Would this trailing comma cause any problems in the code? I have seen just this kind of syntax issue cause problems in other projects I have QA'ed. I thought it worth noting in case it presents a problem.

**Comment by rmroc451** [comment]
nope, thats just visual flavor...  :)
