### ISSUE TITLE
TOGGLE_PROPELLER_DEICE

### ISSUE THREAD

**Issue by Andywmm9** [nguyenquyhy/Flight-Tracker-StreamDeck#121]
There is an event for TOGGLE_PROPELLER_DEICE, but there doesn't seem to be any associated value to check if this is turned on.  Could this be added?  Thanks!

**Comment by Crunchmeister1** [comment]
I second this. WOuld be very nice to have that feedback on the SD button.

**Comment by sn3akz** [comment]
It should be `PROP DEICE SWITCH:index`, but not sure if it's already present in the struct
