### ISSUE TITLE
Windshield de-ice toggle and feedback

### ISSUE THREAD

**Issue by Crunchmeister1** [nguyenquyhy/Flight-Tracker-StreamDeck#122]
The ability to toggle windshield de-ice on and off, as well as having visual feedback would be nice to have.

**Comment by Guenseli** [comment]
I just found the variable 1·(>K:WINDSHIELD_DEICE_TOGGLE,·Number) which is able to toggle, also available for on and off.

But doesn't work in the StreamDeck plugin.
Hope the dev jumps in with a hint if it is possible to implement such variables

**Comment by nguyenquyhy** [comment]
I am not very familiar with K variables. I guess they are similar to H variables, which are not available via SimConnect and need a WASM module to extract.

**Comment by sn3akz** [comment]
@nguyenquyhy maybe we need a MOAWM project (Mother Of All WASM Modules)

**Comment by nguyenquyhy** [comment]
That's basically FSUIPC for FSX, which I really hope we will no longer need for this new sim 😂.

**Comment by sn3akz** [comment]
FSUIPC is now compatible with MSFS :)

**Comment by nguyenquyhy** [comment]
Yep it is compatible since the very early day, but FSUIPC7 uses SimConnect, so it doesn't extract internal vars, unlike FSUIPC6 for FSX and P3D.

**Comment by Crunchmeister1** [comment]
> @nguyenquyhy maybe we need a MOAWM project (Mother Of All WASM Modules)

Ideally, that would be really awesome to be able to interface with the sim directly rather than having to rely on a mix of 3rd party apps to bridge the gap between external hardware or software and the sim.

**Comment by nguyenquyhy** [comment]
Yep that's why I don't want another FSUIPC. But if Asobo drops the ball on this, maybe we have no choice 🤷‍♂️

**Comment by Crunchmeister1** [comment]
> Yep that's why I don't want another FSUIPC. But if Asobo drops the ball on this, maybe we have no choice 🤷‍♂️

Sadly it would seem dropping the ball is their speciality.

**Comment by mnwpro1** [comment]
> 

I have found that Stream Deck acts oddly if you do not specify the LEFT or RIGHT prefix keys ... You have to click the drop down next to the dialog when entering the ctrl key seq. at the top be sure there is a check.  Check this each time.  This fixed many HOT KEY Buttons on the StreamDeck oddly. Going thru this 3D chess match forced me to have to define Key Binding terms by all parties cuz SIMs are FUN !
-Read the rest if you know how to TOGGLE -
Further can anyone understand the use of TOGGLE and SET in the MSFS key bindings... I have real world definitions, and I know what a Toggle is, but the defintions platoon has different ideas of what these are to be used for.  NEW Terminology with better definitions would help... Using the word you are defining in the definition is poor form/style in most worlds. Ive been a programmer I hated writing documentation - so someone else did it and things got lost in translation, either in language or experience.
In the case of TOGGLE in the button assignments Perhaps "Keyboard Toggle" or "Button Toggle" or "ON / OFF"  or "PRESS and RELEASE" cuz the assignment of a TOGGLE to a TOGGLE switch do not workie.  TOGGLE in MSFS means temporary on - PRESS and immediate RELEASE.  Even trying the PRESS or RELEASE options does not allow intuitive use of a TOGGLE option to a TOGGLE switch.  This is maddening.  I assume the various options are for those who use KB mostly, so one key can be both ON and OFF.  
I also assume SET is for setting a dial or multi position switch, like FLAPS to position 1 2 3 4, but I see many videos showing use of the TOGGLE switches on Honeycomb Throttle to SET Lights ON.   Yikes.
More problems arise for me when assigning buttons and the only option  is  TOGGLE - WING Lights and LOGO lights for example.  My Oysters EyceK8tes, no ON and OFF -

**Comment by nguyenquyhy** [comment]
For internal sim events, you can try to use this plugin with MobiFlight module.
