### ISSUE TITLE
HTML variables 

### ISSUE THREAD

**Issue by Guenseli** [nguyenquyhy/Flight-Tracker-StreamDeck#126]
Hello,

first thanks for your wnderful software and a happy new year.

I'm no programmer, so sorry if there are some things I say which will sound stupid in your ears ;)

Ok, I try to make the MSFS Airplanes work with StreamDeck and my VRInsight MCP Combo. For the MCP I use LORBYs AAO and are able to control the CJ4 FMS with as example the following HTML variable:

1·(>H:CJ4_FMC_1_BTN_LEGS,·Number)

I tried now to insert it into your StreamDeck plugin as Toggle event:
CJ4_FMC_1_BTN_LEGS
or
H:CJ4_FMC_1_BTN_LEGS

but nothing works.
Can you give me a hint how I could insert it or are you able to make these HTML variables work?

many thanks!
Günter

**Comment by nguyenquyhy** [comment]
H events are internal stuffs that is not sent via SimConnect (which is what the plugin is using), and need a WASM mod to expose them. Currently we do not have any WASM module, but we support a large list of events exposed by MobiFlight WASM mod.

You can check out our guide here https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/master/docs/USERGUIDE.md#mobiflight-wasm-module-integration.

**Comment by Guenseli** [comment]
thx for ansering,

yes, I already have this stuff implemented.

I think it would be better than to ask then for implementing my variables.
thank you!

**Comment by nguyenquyhy** [comment]
Yes it would probably be much faster and easier for MobiFlight to add that in.

Right now it is like the wild west regarding that kind of WASM module. Everyone spins their own WASM module to do the same thing: extracting the HVars and LVars. In my community folder I already have one for YourControl, one for MobiFlight and probably another one if I want to test Lorby's AAO.

I would love to collaborate with someone else (e.g. MobiFlight) or wait for Asobo to provide a better solution than to write just another WASM module to do such job.

**Comment by Guenseli** [comment]
Yes, you are right

Contacted them and they will provide the variables :)

**Comment by Andywmm9** [comment]
I've been hearing this in the release notes, can you describe what a WASM module is?

**Comment by nguyenquyhy** [comment]
That's a file you have to put in the Community folder which will be run inside the sim, so it can access a lot more internal stuffs. It is a replacement for the old way of writing .dll.

**Comment by nguyenquyhy** [comment]
Please try again with MOBIFLIGHT WASM module.
