### ISSUE TITLE
TBM 930 PFD Timer Start and Stop

### ISSUE THREAD

**Issue by Jovian657** [nguyenquyhy/Flight-Tracker-StreamDeck#127]
In the TBM 930, there is a timer (TMR) displayed in the PFD. One can start the timer to begin counting up in seconds with a mouse click on the TSC in the virtual cockpit. Clicking on the same icon in the TSC will stop the timer.  

It will be great if a StreamDeck toggle button can be programmed to start/stop this timer.

**Comment by Crunchmeister1** [comment]
That's a function that's very specific to that plane. There's no function in Simconnect or the SDK I can find attached to that,much like there's no function attached to the TBM's inertial separately

**Comment by sn3akz** [comment]
> like there's no function attached to the TBM's inertial separately

There is. It's mapped to anti-ice engine 1.

**Comment by Crunchmeister1** [comment]
> > like there's no function attached to the TBM's inertial separately
> 
> There is. It's mapped to anti-ice engine 1.

Sort of....

ANTI_ICE_TOGGLE_ENG1 toggles it on an off. It's either opened or closed. That's now how it's supposed to work in the TBM.

When you hit the switch in the TBM's cockpit, the inertial separator slowly opens  / closes from 0 to 100% over a span of 30 seconds.  This prevents the sudden sudden loss of torque when you close it, and the sudden surge of torque when you open it. It allows the pilot to slowly adjust torque as the inertial separator moves. That's impossible to do properly with an on/off toggle.

THAT particular function is not mappable, and there's no SDK or SimConnect variable to replicate the way the inertial separator is supposed to function when you use the switch in cockpit..

**Comment by sn3akz** [comment]
> That's not how it works in the TBM.
I'm aware of that, but I don't think the 30 second travel should be a function in SimConnect. IMO, toggling the button should start a plane 'animation' of 30 seconds and thus should be in the plane logic and not the control logic.

**Comment by Crunchmeister1** [comment]
> I don't think the 30 second travel should be a function in SimConnect. IMO,

There's no event anywhere that triggers that whole event. SimConnect shouldn't handle the 30 sec delay thing. It should just fire the event in the sim. Via an external source, we get a simple on / off. Whatever Asobo did in the sim to make that 30 sec ramp up / down isn't accessible from either a SimConnect event nor via a keybind.

**Comment by nguyenquyhy** [comment]
With the support of MobiFlight events now, I guess this should be doable.
