### ISSUE TITLE
Variables with an index don't read correctly

### ISSUE THREAD

**Issue by SnugglePilot** [nguyenquyhy/Flight-Tracker-StreamDeck#13]
I'm trying to use the "Generic Gauge" to show my current throttle position in the Cub Crafter X.

I add a Generic Gauge component, and I leave all the fields blank/default except the Display Value field. I set this to `GENERAL ENG THROTTLE LEVER POSITION:1` , which is the documented method for pulling this value. The value always reports as zero (and I get the `!` warning indicator on the device whenever the profile loads, which I assume is some sort of error state).

I've also tried different formats - `... POSITION 1` and `... POSITION: 1` and `... POSITION  1` (two spaces) etc. to try and match the enum listed in the source, but I'm not seeing any results.

In case it was only mapped to the generic toggle button, I also tried sliding a Generic Toggle Button into my layout. I left all the fields blank/default, except the Display Value - this always appears blank and never populates with a value.

Interestingly, if I set the display value on the Generic Toggle Button to specifically `... POSITION: 1` (with a colon and a space before the one) the green light shows up on the toggle button.

FWIW I'm seeing similar results for the mixture and propeller pitch levers.

**Comment by nguyenquyhy** [comment]
`ENERAL ENG THROTTLE LEVER POSITION:1` is correct as I am using it right now.
Currently, you have to set the Min and Max value for the gauge button to work. I'll see how to improve this later.

**Comment by SnugglePilot** [comment]
Oh gosh, you know what the problem was? The default values of "0" and "100" on the min/max fields I thought were prepopulated. In fact you have to type the same values over the "default". I think you should either default the values to the display value if empty, or you should change the default display value to not mislead people!

**Comment by nguyenquyhy** [comment]
Yes. I got the same issue previously 😂. I'll definitely do something for that.
