### ISSUE TITLE
Xfer button in comms panel works sporadically

### ISSUE THREAD

**Issue by Crunchmeister1** [nguyenquyhy/Flight-Tracker-StreamDeck#132]
As per the title. Using the XFer button in the comms panel is hit or miss.

- sometimes it will work as intended. This now seems to be the exception rather than the rule.
- Sometimes it will function as the "enter" function and not switch the the active frequency but keep the new frequency in standby
- sometimes it will cause the plugin to go into its death spiral  with repeated "connecting to Stream Deck" message in sim.

**Comment by rmroc451** [comment]
I had noticed this as well while doing the cannonball run on the 26th.

I tried tinkering/massaging it while trying to focus on the flight. I didn't fix it, but an attempt was made here: https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/pull/108

I'll look at this while looking #86

**Comment by nguyenquyhy** [comment]
I'll close this issue for now as we have many changes on the button and it might help with this issue. Please feel free to reopen if it still happens on v0.32.
