### ISSUE TITLE
Possible to rotate button displays by 180 degrees?

### ISSUE THREAD

**Issue by Jovian657** [nguyenquyhy/Flight-Tracker-StreamDeck#138]
Is there a way to flip all StreamDeck buttons so they display upside down? This would be useful for cockpit builders where the StreamDeck is mounted on a vertical panel.  When mounted vertically, right side up, the buttons are angled slightly down and the cable is on top of the package. It would be great to be able to rotate the StreamDeck package 180 degrees clockwise so that the cable is oriented downward and the buttons are displayed angled up. This would require all graphics for the button displays to be flipped vertically also (i.e. rotated 180 degrees clockwise).

**Comment by rmroc451** [comment]
its possible. I've seen other plugins that have an entire "stream deck profile" for their own settings.  We could investigate something like this to allow you to apply a rotation to all of this plugins buttons.

@nguyenquyhy, you ok with an implementation of this?

**Comment by nguyenquyhy** [comment]
Yah I am not against this feature, but I don't want to add a checkbox to every button. This would sit better in a "global" setting page of the plugin. 
I am not sure the best way to do this setting page, but I am not really fond of adding a new profile just for our own setting (I hope I understand your suggestion correctly). Although it does feel cool to click and change settings, it adds one more rarely used item to my already long profile list.

**Comment by ToddLorey** [comment]
I'd be interested in this rotation as well.  I'm using my Stream Deck rotated by 90 degrees so I have a 3x5 array instead of the 5x3 when it's in "landscape mode".  The best solution would be a global rotation in the Stream Deck software itself, but I haven't seen that yet.  Maybe there's an addon I haven't found??

**Comment by mattchesters** [comment]
From Stream Deck software version 5.3.1.15197, I am able to rotate all buttons globally via the 'Device Orientation' dropdown in the Preference window.
Options available are 'Standard', '90', '180', '240'. The may be preference unique to the StreamDeck Mk2.

**Comment by rmroc451** [comment]
> From Stream Deck software version 5.3.1.15197, I am able to rotate all buttons globally via the 'Device Orientation' dropdown in the Preference window. Options available are 'Standard', '90', '180', '240'. This preference may be unique to the StreamDeck Mk2.

Confirmed, I have this on my non mk2 streamdeck after updating the software version.
![image](https://user-images.githubusercontent.com/15070945/185249447-1d507efc-9f80-47f1-8158-e3dac9b98b09.png)



Closing this enhancement request.
