### ISSUE TITLE
Add missing anti-ice feedback for toggle buttons

### ISSUE THREAD

**Issue by SnugglePilot** [nguyenquyhy/Flight-Tracker-StreamDeck#14]
Recently a commit was made that adds `GENERAL ENG ANTI ICE POSITION:index` which is great for anti-ice solutions that have sliders (eg: plunger-pull carb heat), but there is also an engine anti-ice switch component that gives feedback on the variable `ENG ANTI ICE:index`. Can we get this added as well?

**Comment by nguyenquyhy** [comment]
I am a bit confused on the difference between the 2 variables. Do you know?

**Comment by SnugglePilot** [comment]
`ENG ANTI ICE` is the bool representing a toggle switch position, such as on an airliner. `GENERAL ENG ANTI ICE POSITION` is a percentage value that reports a lever position, such as the carb heat plunger on a Cub X.

**Comment by nguyenquyhy** [comment]
Hmm from what I can see, `GENERAL ENG ANTI ICE POSITION` is a bool too. We used it to show the light for Anti Ice before. I wonder if that changed.

**Comment by SnugglePilot** [comment]
Ah interesting. I could be wrong there!

I'm currently using GENERAL ENG ANTI ICE:1 without issue, so it's more of a nice-to-have/compatibility thing.

**Comment by ksarantakos** [comment]
I am trying to use that value for Carb Heat on C152 and not getting button state. What should I be using to get the correct feedback value?

![image](https://user-images.githubusercontent.com/211712/100526669-24144e80-3199-11eb-82bc-b09aaa781928.png)

**Comment by Crunchmeister1** [comment]
> What should I be using to get the correct feedback value?

This works to solve your problem, if you haven't already figured it out. 

![image](https://user-images.githubusercontent.com/75218511/101804827-01aafb00-3ae0-11eb-97d3-6e19cf6e7bd1.png)

**Comment by ksarantakos** [comment]
Thank you!

**Comment by nguyenquyhy** [comment]
I'm a bit confused here but I would guess this is ok now 😛.
