### ISSUE TITLE
Barometric pressure setting control for altimeters

### ISSUE THREAD

**Issue by beckerdo** [nguyenquyhy/Flight-Tracker-StreamDeck#144]
Feature request

I would like to see a control to adjust the barometric setting for the altimeter

For me, ideally, this would be like the COM and NAV control, that normally shows the current setting. When the button is pressed, a keypad comes up to set and enter the value.

I think the keypad and display should be able to display inches Hg (for example 29.92 or 30.11) or  millibars (for example 1013mB or 1020mB).

I've tried creating my own control with the Increase value and Decrease value controls, but it does not work well because of the range and number of button presses required.

**Comment by sn3akz** [comment]
Should be possible by reading value `KOHLSMAN SETTING MB`
And either use `KOHLSMAN_INC/DEC` or `KOHLSMAN_SET` (Millibars * 16)

**Comment by beckerdo** [comment]
Thanks. KOHLSMAN_SETTING_HG and KOHLSMAN_SETTING_MB both work for display. However the "Increase value" and "Decrease value" elements have defined functions in the Stream Deck user interface. KOHLSMAN_INC/DEC are not one of them. What control should we use for those?

**Comment by sn3akz** [comment]
> KOHLSMAN_INC/DEC are not one of them

Working on it ;)
