### ISSUE TITLE
DA62X

### ISSUE THREAD

**Issue by Andywmm9** [nguyenquyhy/Flight-Tracker-StreamDeck#148]
On the DA62X, looking in code I believe we need these two variables to be able to control de-icing.  

DEICE_MODE (1, 2, or 3, higher is more deicing)
DEICE_WINDSHIELD 

Also, has anyone researched found out how to turn on the AUX fuel pumps (to move fuel from the aux tanks to the main tanks?)  

I played around with all of these with keybindings, and wasn't able to find any that would accomplish these.   

I'm not sure if these are actually sim connect variables, I just found these in a file browsing the community folder for the DA62X mod.

**Comment by Andywmm9** [comment]
I might play around with my first pull request with this, after I figure out which are the right ones.  I just wanted to put this in as a log.

**Comment by Andywmm9** [comment]
It turns out these are not simconnect variables.  It seems there is absolutely no way to control these.  Am I missing something?

**Comment by nguyenquyhy** [comment]
Where did you find those variables? Can you give me more context on those?

**Comment by Keldane** [comment]
Hi,

The feedback value RECIP ENG ENGINE MASTER SWITCH:index doesn't work.
It's needed to check ENGINE_MASTER_index_TOGGLE on DA62X

Thanks for your work.
