### ISSUE TITLE
Add Flight Level Change On and Off Events to Structs.CS

### ISSUE THREAD

**Issue by jplewis01** [nguyenquyhy/Flight-Tracker-StreamDeck#149]
Flight Level Change On and Off Events are wrapped into the logic for the preset FLC Toggle. If the user is trying to contruct multi action commands for using flight level change there is presently no way to just turn FLC on and off.

As a user I want to have the ability to independently turn on and off FLC. This will allow multi -step buttons to be  created or other more complex scenarios.

**Comment by nguyenquyhy** [comment]
One of the reason I built the preset button is to embed some complicated logic that is not easy to express with configurations as what you would do with Generic button.

If you want to trigger the event manually, you can use `FLIGHT_LEVEL_CHANGE_ON` and `FLIGHT_LEVEL_CHANGE_OFF` in generic button (which is added the same time as the FLC preset button).
