### ISSUE TITLE
Loop in connecting to SimConnect

### ISSUE THREAD

**Issue by Andywmm9** [nguyenquyhy/Flight-Tracker-StreamDeck#152]
I have a new PC, and the latest version of the streamdeck software and flight tracker.  Every time I start MSFS and press a button on my streamdeck, I see on MSFS that it has connected to SimConnect, and the popup keeps reappearing, and the buttons on the streamdeck do nothing.  I have to close streamdeck, and restart it.  Then I continue to see the connected to simconnect popup in MSFS for a couple of minutes, but at least the streamdeck works.  

I have to do this every time.  Any ideas what is going on?

**Comment by nguyenquyhy** [comment]
Can you please upload the logs in `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin`?
Log file names are something like flightstreamdeck*.log.

**Comment by 0Thomas082** [comment]
Hello, 
i have the same problem with connecting to flight sim. i need to uninstall / reinstall the flighttracker addon to get it working again, and after a few minutes it is broken again.  Log is attached...
[flightstreamdeck20210115.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5821809/flightstreamdeck20210115.log)

**Comment by Andywmm9** [comment]
[flightstreamdeck20210117.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5827255/flightstreamdeck20210117.log)
Here is the most recent log.

**Comment by rug4ever** [comment]
i have with last Version same Problem but the 0.23 a little better but much more as before.
why that Problem?

**Comment by nguyenquyhy** [comment]
Version 0.25 has further improvement on this. Please update to that version and let me know if it helps.

**Comment by SaschaKliche** [comment]
@nguyenquyhy I am experiencing the same problem with 0.24 and 0.25, The gauges freeze, I get the connected to simconnect popup, sometimes every few seconds. I have to uninstall and install 0.23 to use it. 
Btw, thanks so much for providing this awesome plugin, much appreciated!

I have attached the log from today with 0.25
[flightstreamdeck20210207.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5938609/flightstreamdeck20210207.log)

**Comment by nguyenquyhy** [comment]
Thanks for sharing the log so quickly. Do you mind sharing an export of your profile too? I can't figure out much from the error log.

**Comment by SaschaKliche** [comment]
I have attached the profile, just tested it again with 0.25, immediately caused the issue. The log shows [ERR] Exception received: "EVENT_ID_DUPLICATE"
[C172 Test.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5938776/C172.Test.zip)

**Comment by nguyenquyhy** [comment]
Haven't figured out the issue yet, but I have to say the profile looks very nice.

**Comment by nguyenquyhy** [comment]
I think I found the issue. I updated a library that performs all the drawing in the plugin, and the updated version has a bug that is triggered by the Generic Gauge. I have reverted to previous version and release v0.26.

Please help me to test and let me know if the issue is fixed.

**Comment by SaschaKliche** [comment]
I think you nailed it! So far no dis-/reconnect issues with 0.26, thanks a lot for the quick fix!

The only thing I see in the log is lots of "Incompatible array count" but I guess that is connected to a problem with the ELECTRICAL_* and FUEL_* values. I also see "NAME_UNRECOGNIZED" in the log but I cannot see what name is unrecognized.

**Comment by nguyenquyhy** [comment]
"Incompatible array count" showing up a couple times when you switch pages/profiles is expected. It is due to a short lag between the time we send SimConnect new payload request and when SimConnect actually sends the requested payload.

"NAME_UNRECOGNIZED" is not expected though since currently we limit the variable and event names to what's in our structs file, and I normally test those names before releasing. If you give me the log with NAME_UNRECOGNIZED, I think I can figure that out.

And "EVENT_ID_DUPLICATE" is generally harmless. In some circumstances the plugin might mistakenly register the event multiple times, but that shouldn't create any problem.
