### ISSUE TITLE
Variable ADD request:  RECIP ENG MANIFOLD PRESSURE:index 

### ISSUE THREAD

**Issue by jplewis01** [nguyenquyhy/Flight-Tracker-StreamDeck#162]
**Describe the solution you'd like**
Please add the Value **RECIP ENG MANIFOLD PRESSURE**:index
The variable lists in both Prepar3d SDK and MSFS 2020 SDK and shows as responding
The Var name takes an index. I'm assuming it to be the engine number. 

**Additional context**

**Comment by nguyenquyhy** [comment]
I have added the variable for next update. Is there any aircraft that show that value so that I can do some tests?

**Comment by nguyenquyhy** [comment]
Added in v0.25
