### ISSUE TITLE
TURBINE_IGNITION_SWITCH_SET1 and TURBINE_IGNITION_SWITCH_SET2

### ISSUE THREAD

**Issue by maor561** [nguyenquyhy/Flight-Tracker-StreamDeck#163]
in MFS2020 A320 FBW

this command not working for me
1. i am using toggle button
2. toggle event:  TURBINE_IGNITION_SWITCH_SET2 ot TURBINE_IGNITION_SWITCH_SET1
try also 
 toggle event:  TURBINE_IGNITION_SWITCH_SET
toggle parameter: 1 or 2
![image](https://user-images.githubusercontent.com/71768165/105770893-76d77000-5f68-11eb-9527-98913078ee5a.png)

**Comment by nguyenquyhy** [comment]
Afaik, `TURBINE_IGNITION_SWITCH_SET1` `TURBINE_IGNITION_SWITCH_SET2` and  works only on the Longitude (and you have to use it with 2 other events). The 32NX and even the default A320 don't play well with SimConnect events, and it's nothing we can do here unless they react to the event.
