### ISSUE TITLE
Unable To Install Plugin

### ISSUE THREAD

**Issue by FozzyFlight** [nguyenquyhy/Flight-Tracker-StreamDeck#164]
Hello,

StreamDeck Version - 4.9.2.13193
Flight Tracker Version - 0.23

Sorry, I'm very new to this, however, I'm unable to install the FlightTracker PlugIn into Stream Deck, once I double click on the PlugIn installer I'm able to see it in:

%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin, but it never loads in StreamDeck, I've tried uninstalling StreamDeck and applying the Plugin again, it displays the message to install then nothing happens. I'm also unable to see any log files in the above folder. All other Plugins work in StreamDeck ok

Can somebody please point me in the right direction? I know this'll be me doing something wrong :)

Thank you

**Comment by nguyenquyhy** [comment]
So don't you see a new button group like this?
![image](https://user-images.githubusercontent.com/1560418/106205888-373d9d80-618d-11eb-81bf-14d57b282ee2.png)

Can you share the logs in %appdata%\Elgato\StreamDeck\logs\?

**Comment by FozzyFlight** [comment]
Hi,

Thanks for the help,

Correct, the plugin does not show:

Here are the latest log file lines:

`07:05:29.482                     epl                               dbgcommand():                                   using log file 'C:\Users\TEST\AppData\Roaming\Elgato\StreamDeck\logs\StreamDeck0.log'
07:05:29.482                     StreamDeck                        main():                                         Compiled with Qt 5.14.2 ; SSL: OpenSSL 1.1.1d  10 Sep 2019
07:05:29.485                     StreamDeck                        main():                                         Runtime SSL Supported: 1
07:05:29.485                     StreamDeck                        main():                                         Runtime SSL version used: OpenSSL 1.1.1d  10 Sep 2019
07:05:31.387                     StreamDeck                        EGQTTranslationManager::LoadLocalizations():    Could not load the 'en_GB' localization
07:05:31.390                     StreamDeck                        main():                                         Using preferences from \HKEY_CURRENT_USER\Software\Elgato Systems GmbH\StreamDeck
07:05:31.394                     StreamDeck                        ESDCustomPluginCommunication::start():          Using port 28196 to communicate with plugins
07:05:31.433                     StreamDeck                        ESDPluginManager::LoadPluginsInFolder():        Loading custom plugins...
07:05:31.433                     StreamDeck                        ESDPluginManager::LoadPluginsInFolder():        Loading tech.flighttracker.streamdeck.sdPlugin...
07:05:31.433                     StreamDeck                        ESDPluginManager::LoadPluginAtPath():           Plugin tech.flighttracker.streamdeck could not be loaded
07:05:31.763                     StreamDeck                        ESDVSDServer::init():                           ### [SERVER] init
07:05:31.764                     StreamDeck                        ESDCUEHub::init():                              ### [CUESDK] init
07:05:31.773                     StreamDeck                        AccountMgr::InitializeAccountMgr():             AccountMgr initialized
07:05:31.773                     StreamDeck                        AccountMgr::ReloadAllAccountsFromPreferences(): Reload all accounts
07:05:31.773                     StreamDeck                        AccountMgr::RecreateServiceInstancesForType():  Recreate service instances for Twitter
07:05:31.773                     StreamDeck                        AccountMgr::RecreateServiceInstancesForType():  Recreate service instances for YouTube
07:05:31.773                     StreamDeck                        AccountMgr::RecreateServiceInstancesForType():  Recreate service instances for Streamlabs
07:05:31.773                     StreamDeck                        AccountMgr::RecreateServiceInstancesForType():  Recreate service instances for Twitch
07:05:31.774                     StreamDeck                        EGCAPILiteDLL::LoadDLL():                       Could not load EGCAPILite.dll
07:05:31.774                     StreamDeck                        EGCAPILiteDLL::LoadDLL():                       Loading EGCAPILite.dll from: C:\Program Files\Elgato\GameCapture\EGCAPILite.dll, result: 0
07:05:31.774                     StreamDeck                        EGCAPILiteDLL::Initialize():                    mInitializeFunc is not set
07:05:31.774                     StreamDeck                        GameCaptureSync::GameCaptureSync():             Unable to initialize Game Capture integration.
07:05:31.774                     StreamDeck                        MainWindow::ReloadProfiles():                   Flattening profiles in C:\Users\TEST\AppData\Roaming\Elgato\StreamDeck\ProfilesV2
07:05:31.774                     StreamDeck                        MainWindow::ReloadProfiles():                   Loading profiles from C:\Users\TEST\AppData\Roaming\Elgato\StreamDeck\ProfilesV2
07:05:31.774                     StreamDeck                        ESDProfileManager::LoadProfileAtPath():         Loading profile at path C:\Users\TEST\AppData\Roaming\Elgato\StreamDeck\ProfilesV2\916E8D31-2E98-4478-AB08-0EEA0C820510.sdProfile
07:05:31.792                     StreamDeck                        ESDMultiDevicesModelManager::GetDeviceModelForDeviceUUID(): Device model is unknown: ''
07:05:31.792                     StreamDeck                        ESDMultiDevicesModelManager::GetDeviceModelForDeviceUUID(): Device model is unknown: ''
07:05:31.819                     StreamDeck                        ESDMultiDevicesModelManager::GetDeviceModelForDeviceUUID(): Device model is unknown: ''
07:05:31.826                     StreamDeck                        MainWindow::bootstrap():                        Start Stream Deck App -> Version: 4.9.2.13193
07:05:31.833                     StreamDeck                        ESDMultiDevicesModelManager::GetDeviceModelForDeviceUUID(): Device model is unknown: ''
07:05:31.834                     StreamDeck                        ESDMultiDevicesModelManager::GetDeviceModelForDeviceUUID(): Device model is unknown: ''
07:05:31.843                     StreamDeck                        ESDMultiDevicesModelManager::GetDeviceModelForDeviceUUID(): Device model is unknown: ''
07:05:31.843                     StreamDeck                        ESDMultiDevicesModelManager::GetDeviceModelForDeviceUUID(): Device model is unknown: ''
07:05:31.857                     StreamDeck                        MainWindow::bootstrap():                        All object init done!
07:05:31.857                     StreamDeck                        ESDMultiDevicesModelManager::GetDeviceModelForDeviceUUID(): Device model is unknown: ''
07:05:31.857                     StreamDeck                        MainWindow::bootstrap():                        Running in high dpi mode: 0
07:05:31.857                     StreamDeck                        ESDSharedFileServer::ESDSharedFileServer():     mapfile location C:\ProgramData\Elgato\StreamDeck\STREAMDECKINTERNALSHM
07:05:31.932                     StreamDeck                        MainWindow::event():                            Wake up keypad(s).
07:05:36.841                     StreamDeck                        EGQTSWUpdateDialog::checkForUpdate():           Check for update 2: https://gc-updates.elgato.com/windows/sd-update/final/app-version-check.json
07:05:36.841                     StreamDeck                        EGQTSWUpdateDownloader::startDownload():        Download task name: Update File, file URL: https://gc-updates.elgato.com/windows/sd-update/final/app-version-check.json
07:05:37.286                     StreamDeck                        EGQTSWUpdateDialog::shouldUpdate():             current SW Ver: 4.9.2.13193, remote SW Ver: 4.9.2.13193
07:05:37.286                     StreamDeck                        EGQTSWUpdateDialog::handleUpdateFileDownloaded(): No update available
07:05:52.029                     StreamDeck                        ESDAppStoreManager::UpdateAppStorePlugins():    Check for Plugin Store updates`

**Comment by nguyenquyhy** [comment]
Can you try to install it from the store instead? 
Press the More Actions button in the bottom right corner of Stream Deck. I have just put version 0.26 in there.

**Comment by nguyenquyhy** [comment]
I'll close this one for now. Please feel free to reopen if you still have issue.

**Comment by KrazySwede** [comment]
I had the same issue while trying to **reinstall** the plugin today from the store. I had previously installed and removed it. When reinstalling everything appeared to go well but the button group did not appear and I did not receive the message about pre-defined profiles.
I was able to resolve the issue by deleting the two folders below, restarting the Stream Deck app and resinstalling from the store. "...\AppData\Roaming\Elgato\StreamDeck\PluginStoreCache" and
"...\AppData\Roaming\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin".

Here are a few lines from a log while I was experiencing the issue.

```
11:32:43.947                     StreamDeck                        ESDPluginManager::LoadPluginsInFolder():        Loading tech.flighttracker.streamdeck.sdPlugin...
11:32:43.949                     StreamDeck                        ESDPluginParser::CreatePluginFromPath():        Could not find the Code Path: 
11:32:43.949                     StreamDeck                        ESDPluginManager::LoadPluginAtPath():           Plugin tech.flighttracker.streamdeck could not be loaded
[further down]
11:33:17.561                     StreamDeck                        ESDPluginManager::InstallPlugin():              Failed to install plugin from 'C:\Users\marku\AppData\Local\Temp\Stream Deck-icWvUP\tech.flighttracker.streamdeck.sdPlugin' to 'C:\Users\marku\AppData\Roaming\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin'
```

I assume FozzyFlight was able to resolve his/her issue as well but perhaps this can help someone in the future or give you some insight into a possible bug @nguyenquyhy . Please let me know if you would like any additional details.

**Comment by Gneu** [comment]
Hi all, I exactly have the same issue. And if I try to instal via the github file it says it is already installed...

**Comment by Sandman161** [comment]
Streamdeck launches an error at moment of installing the plugin. The logs show this:

2023-12-30T23:43:51.350Z                    StreamDeck                    wrn ESDPluginManager::InstallPlugin():              Failed to install plugin from 'C:\Users\Admin\AppData\Local\Temp\be09866a-7f46-40e3-a600-7af160e19f76\tech.flighttracker.streamdeck.sdPlugin' to 'C:\Users\Admin\AppData\Roaming\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin' with 'core failed to load plugin'
2023-12-30T23:43:51.350Z                    StreamDeck                    wrn ESDMarketplaceAssetManager::installLocal::<lambda_a891b71fb4c944f3fb1ea99cf6500c0e>::operator ()(): Local install failed with 'install terminate', Context: (InstallError) Plugin '?' (?) [dc3392de-e0e3-42de-9340-c1916e163dca][tech.flighttracker.streamdeck]

Can you tell me what is wrong here?
