### ISSUE TITLE
Custom-ranged Gauges

### ISSUE THREAD

**Issue by SnugglePilot** [nguyenquyhy/Flight-Tracker-StreamDeck#17]
The Generic Gauge works great, but it would be nice to have some control over what the "yellow" and the "red" range is (and maybe add a green range too? and white if you want to get fancy?)

My current use case is showing the current fuel left in the tank.

![image](https://user-images.githubusercontent.com/962291/92406882-04b3db00-f0ee-11ea-936d-255dd6705e47.png)

It shows "red" when the tank is full (and not always - probably a rounding error - see above). It should probably be green at the top end (easy fix: inverted colors checkbox).

I'd love to show a red value here when you are getting low on fuel, or a yellow value on warning. eg, here is the 172 fuel gauge in-cockpit:

![image](https://user-images.githubusercontent.com/962291/92406952-2ca33e80-f0ee-11ea-9077-c505bd5a5d93.png)

**Comment by nguyenquyhy** [comment]
Right now, it is red whenever the value reported by the sim is over your Maximum Value.

The gauge button is quite basic at the moment, but yes there are several possible improvements:
- [ ] Custom color range
- [ ] More indicator formats such as the horizontal line
- [ ] Dual values?

**Comment by rmroc451** [comment]
@SnugglePilot / @nguyenquyhy I'm tinkering with creating a gauge like the one posted above over on my repo.  Its easier than I thought to draw those out.  This might be more fun that I imagined.

I was going to try to dynamically do color bars like that in an arc, but it looks like the package we are using (SixLabors) for drawing doesn't like to draw arcs.  Hy, are you ok if I try to implement the arcs with the native system.drawing?

**Comment by nguyenquyhy** [comment]
I don't mind System.Drawing as long as we don't have to add reference to .NET Framework or all the GDI+ stuff 😛. 
But I always think System.Drawing is much more primitive than ImageSharp. Maybe I am too outdated 😂.

**Comment by rmroc451** [comment]
I was able to do this with the Six Labor stuff, thought @SnugglePilot & @nguyenquyhy?  Do we need the delinitations for every 10 or whatever?  I have the bars custom percentages you pass in as a csv of integers :)  so right now I have that as 12%, 24% and 64% for red/yellow/green.

I still have to handle vertical orientations and then getting the text to orient correctly when rotated. but, almost there.

![image](https://user-images.githubusercontent.com/15070945/93028437-a26d4580-f5d9-11ea-94b1-7f7cd26fb479.png)

**Comment by nguyenquyhy** [comment]
I think it looks really good 😄. Can we specify the color for each range or are they assumed somehow?

**Comment by rmroc451** [comment]
Right now, its assumed critical (first range) is red, warning (second range) is yellow, nominal (third range) is green and superb (the fourth range) is no color.  I can see about allowing an enum parse for color so you can specify it yourself. Was a quick exercise to see how it was going to work, I'm glad it looks halfway decent.

**Comment by dialogueCoder** [comment]
> I was able to do this with the Six Labor stuff, thoughts @SnugglePilot & @nguyenquyhy? Do we need the delinitations for every 10 or whatever? I have the bars custom percentages you pass in as a csv of integers :) so right now I have that as 12%, 24% and 64% for red/yellow/green.
> 
> I still have to handle vertical orientations and then getting the text to orient correctly when rotated. but, almost there.
> 
> ![image](https://user-images.githubusercontent.com/15070945/93028437-a26d4580-f5d9-11ea-94b1-7f7cd26fb479.png)

Really good job. I suppose the only issue might be the size of the font.

**Comment by rmroc451** [comment]
Text size is customizable, but there is a range before it gets too big and overlaps. But if you need it that big, you need it that big. ;)
