### ISSUE TITLE
Num Pad opens up XL view on normal StreamDeck

### ISSUE THREAD

**Issue by OzzyDE** [nguyenquyhy/Flight-Tracker-StreamDeck#173]
See screenshot this is what happens when you open up the numpad on my StreamDeck for some reason I think it opening up the XL Numpad and not the Normal Version

![image](https://user-images.githubusercontent.com/18222805/106772956-d4427f80-6640-11eb-8ecd-98838e2d5b58.png)

This is the profile streamdeck asks to install when you long press a button to open this feature.

**Comment by nguyenquyhy** [comment]
Can you try to delete that profile (and any profile named Numpad) and press the button again? The profile should be named numpad and readonly.

**Comment by OzzyDE** [comment]
Yes tried a few times and it always loads this one

**Comment by OzzyDE** [comment]
![image](https://user-images.githubusercontent.com/18222805/106774236-351e8780-6642-11eb-99c8-2473bcd3c087.png)
Version of Stream Deck, I tried rebuilding the Nav and Com buttons as well to see if it was an issue but same.

**Comment by nguyenquyhy** [comment]
Is there any profile named Numpad?

**Comment by OzzyDE** [comment]
Nope, no named Profiles called Numpad, and if i long press on the Nav Icon it switches to to this "Profile 1 Copy"

**Comment by nguyenquyhy** [comment]
So after you deleted that "Profile 1 Copy" and long press the Nav button, it asks you to create a new profile, and then re-create that "Profile 1 Copy". Is that correct?

**Comment by OzzyDE** [comment]
that is correct, 

OK i just got it to fix it self by long pressing Nav again after it installed "Profile 1 Copy" it installed "Numpad" and now it works!

**Comment by nguyenquyhy** [comment]
Close it for now since I think this is a problem with Stream Deck software not installing the correct profile.
