### ISSUE TITLE
0.26 version of the Plugin Crashes frequently, same as Version 0.25

### ISSUE THREAD

**Issue by jplewis01** [nguyenquyhy/Flight-Tracker-StreamDeck#178]
I'm seeing the Same Pluigin Crashing problem in version 0.26 as is seen in 0.25. Sadly it seems not fixed yet. 

Let me know if I can assist with testing a new version when one is available

**Comment by nguyenquyhy** [comment]
My build script didn't clean up properly and ended up include old files... I have reupload v0.26. Please try to download again.

**Comment by jplewis01** [comment]
I will try right now the problem if present is easily reproducible.

**Comment by jplewis01** [comment]
That seems to have fixed it!!! Well done!!!

**Comment by nguyenquyhy** [comment]
Awesome!
