### ISSUE TITLE
ELECTRICAL_BATTERY_IS_CHARGING is causing NAME_UNRECOGNIZED

### ISSUE THREAD

**Issue by SaschaKliche** [nguyenquyhy/Flight-Tracker-StreamDeck#179]
As mentioned in #152 I get the following message in the log with v0.26:
`[ERR] Exception received: "NAME_UNRECOGNIZED"`

It looks like the toggle value "ELECTRICAL_BATTERY_IS_CHARGING" being used in a generic toggle button is causing the issue.
I have attached the [flightstreamdeck20210209.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5953875/flightstreamdeck20210209.log) and a test profile [Engine.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5953877/Engine.zip)

You can see in the profile how it affects other values as well. As long as the toggle button with that value is present other buttons don't work as expected, e.g. fuel capacity is invalid.

Please let me know if you need further information.

**Comment by nguyenquyhy** [comment]
Thanks for checking. I'll remove the variable for now, so it won't affect other buttons.

**Comment by nguyenquyhy** [comment]
Fixed in version 0.27
