### ISSUE TITLE
Checkbox to invert feedback value

### ISSUE THREAD

**Issue by SnugglePilot** [nguyenquyhy/Flight-Tracker-StreamDeck#18]
I'm using a Generic Toggle Button to show the state of the "FUEL CUTOFF" valve in the C172. This is great with:

Toggle: `TOGGLE_FUEL_VALVE_ENG1`
Feedback: `GENERAL ENG FUEL VALVE:1`

but the button lights up when the fuel cutoff is false. This is a semantic problem probably present across several aircraft that just label their layouts differently (the same button is "fuel flow" on one plane and "fuel cutoff" on another plane).

To that end, it would be nice to have a simple "invert bool" checkbox on the feedback value for all generic toggle buttons.

nb; this would also be solved by evaluation, though this would be easier than a custom parser. ;) feel free to mark as a duplicate and close if this will do the trick: https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/issues/9

**Comment by nguyenquyhy** [comment]
I'll add an invert checkbox. This seems to be appropriate for many cases.

**Comment by SnugglePilot** [comment]
Works for me, and is a single step towards an evaluator anyway 👍

**Comment by nguyenquyhy** [comment]
Looking at the PR from @rmroc451 I think this one should be resolve by using the expression != 1 after his PR is merged, so yah I'll close this one and consider it a duplicated to #9 .

**Comment by rmroc451** [comment]
@SnugglePilot / @nguyenquyhy you also could just invert the on/off images, and accomplish the same effect without the expression logic. I just did that for my Fuel Valve thing, like SnugglePilot was having. That was driving me nuts 👍
