### ISSUE TITLE
Difference between onscreen instrument and simconnect variable

### ISSUE THREAD

**Issue by tmctiger1** [nguyenquyhy/Flight-Tracker-StreamDeck#187]
- Stream Deck Plugin and MSFS version
MSFS Version: latest (1.13.16.0, world update 3), Steamversion
Stream Deck Plugin Version: 0.27 (used stream deck store version)
- Description of the issue & expected behavior
I somewhat have a strange problem, or at least I do not understand why it is behaving this way. I am not sure if this ia a issue with the stream deck plugin or with simconnect.

I’d like to show my engine rpm in my stream deck. Stream deck connects via simconnet to the simulator - so far so good. But when I’d like to display the engine rpms using simconnect variable GENERAL_ENG_RPM__1 i have a missmatch between the instroment in the cockpit shown on the screen and the value read out via simconnect by the stream deck.

For example when my engine is idle the rpm counter in the cockpit says 880 but the value in GENERAL_ENG_RPM__1 is 1483. Same when I apply full throttle: 2300 rpm in cockpit view but 3889 rpm in GENERAL_ENG_RPM__1. See attached iamges.

So the questions: am I doing something wrong? Is the stream deck profile/plugin doing something wrong, or is the value provided by the simulator in GENERAL_ENG_RPM__1 wrong? I am a little puzzeld here honestly :man_shrugging:

Here you see the Missmatch:
Idle RPM:
![RPMmissmatch_1](https://user-images.githubusercontent.com/79407635/108627376-822d9680-7455-11eb-8c60-1dec4973553d.jpg)
Full throttle:
![RPMmissmatch_2](https://user-images.githubusercontent.com/79407635/108627378-83f75a00-7455-11eb-99fd-79a4a0979bb0.jpg)

BTW: this is the Diamond DA40 TDI, no plugins for this aircraft installed.
- Steps to reproduce the issue
use the DA40 TDI, use a genric gauge and use the simconnect variable GENERAL_ENG_RPM__1 --> you should see missmatching RPM values

- If the issue happens consistently, an export of your profile would help tremendously.
[DA40TDI.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6017801/DA40TDI.zip)
- Log files at `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log`
[flightstreamdeck20210221.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6017805/flightstreamdeck20210221.log)
There are some errors in the log file. I think they are related somehow to the GENERAL_ENG_RPM__1 variable.
- Screenshots
initially my gauge configuration was as follows:
![rpmgaugesetup_0](https://user-images.githubusercontent.com/79407635/108627055-e94a4b80-7453-11eb-8334-af094bdb421b.JPG)
![rpmgaugesetup_1](https://user-images.githubusercontent.com/79407635/108627059-ebaca580-7453-11eb-87bf-099e362a4f4f.JPG)
With this configuration I got this value missmatch. According to the answer from NguyenQHy ([answer given here](https://forums.flightsimulator.com/t/difference-between-onscreen-instrument-and-simconnect-variable/369069/5)) I removed the values in “Unit & Decimals”:
![rpmgaugesetup_2](https://user-images.githubusercontent.com/79407635/108627060-ecddd280-7453-11eb-9b33-fffff6aae81b.JPG)
But unfortunatly I still get the wrong values.

**Comment by rmroc451** [comment]
If you remove the values, and then change focus to a different textbook on the attributes, does it update to work?

We currently only update the streamdeck client with your updates on blur (leaving the textboxes).

Let me know if that works.

**Comment by nguyenquyhy** [comment]
I just checked the DA gauge. They actually use `PROP RPM:1` instead of engine RPM for that number. There are also some rounding involved `Round(value / 20) * 20`.

Right now we don't have support for `PROP RPM:index` yet. I'll add that in next update.

**Comment by tmctiger1** [comment]
> 
> 
> If you remove the values, and then change focus to a different textbook on the attributes, does it update to work?
> 
> We currently only update the streamdeck client with your updates on blur (leaving the textboxes).
> 
> Let me know if that works.

Hi, yes the issue persists also with empty fields.

**Comment by tmctiger1** [comment]
> 
> 
> I just checked the DA gauge. They actually use `PROP RPM:1` instead of engine RPM for that number. There are also some rounding involved `Round(value / 20) * 20`.
> 
> Right now we don't have support for `PROP RPM:index` yet. I'll add that in next update.

Ah thanks for the heads up about this issue.
That makes aktually total sense since the DA40 has a automatic variable pitch propeller and the rpm is given for the prop and also stays more or less the same since only the pitch  of the propeller is adjusted...

**Comment by tmctiger1** [comment]
Hi @nguyenquyhy 
I have currently checked version 0.29 and now it works like a charm! :) Thanks for adding the value to your Plugin! 

I am now using PROP_RPM__1 and receive the correct values.

Just a question regarding PROP_THRUST__1: what does this represent. I thought this should be someting between 0 and 100 percent but actually it is between 67 (idle) and 530 (fullthrottle)

Thanks and BR!

**Comment by nguyenquyhy** [comment]
`PROP THRUST:index` is thrust measure in pound 😀.

**Comment by tmctiger1** [comment]
> 
> 
> `PROP THRUST:index` is thrust measure in pound 😀.

Ah I understand - Thanks!
