### ISSUE TITLE
Add math operations to values

### ISSUE THREAD

**Issue by nzeppos** [nguyenquyhy/Flight-Tracker-StreamDeck#199]
An example would be FUEL_TANK_LEFT_MAIN_QUANTITY. Simconnect fuel quantities are generally defined as gallons, but it would be nice to be able to do some adhoc math in "Display value" field, so that we could convert them on the fly to lbs, kgs etc.

So instead of putting FUEL_TANK_LEFT_MAIN_QUANTITY in "Display value", we could put FUEL_TANK_LEFT_MAIN_QUANTITY*6.7 (or similar)

**Comment by nguyenquyhy** [comment]
Why bother when you can just type in the unit 😁

**Comment by nzeppos** [comment]
Ah, I had forgotten about that, I'll try it asap, thanks!

**Comment by nguyenquyhy** [comment]
You can try the ones in https://docs.flightsimulator.com/html/Programming_Tools/SimVars/Simulation_Variable_Units.htm. Maybe you can't translate from volume to weight. I am not very sure.

**Comment by nguyenquyhy** [comment]
I'll close this and will track in another issue #224.
