### ISSUE TITLE
Toggle for vertical speed

### ISSUE THREAD

**Issue by Der-Matze** [nguyenquyhy/Flight-Tracker-StreamDeck#20]
Hi guys, would it be possible to add a toggle for vertical speed hold? I took a look into flightsim.exe and may found some event-ids for vertical speed:

AP_VS_HOLD
AP_VS_ON
AP_VS_OFF
AP_VS_SET

I don't exactly know if this was the right place to look for it but all the other known ids can be found there too.

**Comment by nguyenquyhy** [comment]
I'll add those in. How did you get those IDs by the way?

**Comment by Der-Matze** [comment]
Thank you! Found them simply by searching inside the flightsim.exe with hex editor and some guessing for the name. I knew many of the ids are in the scheme AP_xx_HOLD or _ON/_OFF. In the end i found a block of ascii text with those ids and the VS ones where also there.

**Comment by nguyenquyhy** [comment]
AP_VS_HOLD, AP_VS_ON and AP_VS_OFF have been added in version 0.6.
