### ISSUE TITLE
MSFS time clock

### ISSUE THREAD

**Issue by 614NLV** [nguyenquyhy/Flight-Tracker-StreamDeck#201]
Hi all :)
I just got a 15b streamdeck and immediately installed Flight-Tracker; great job! 
As an idea to add I'd like to have a simple msfs time clock, because I don't always fly online
thank you ;)
![20210308_175845](https://user-images.githubusercontent.com/77018336/110362028-10eb0780-8041-11eb-8f3d-cbcae20652c2.jpg)

**Comment by nguyenquyhy** [comment]
I don't think this is something we can add to Generic Button and will to be added in Preset Button or a completely separate button. Is there any preferred display for this? (e.g. analog vs. digital)

**Comment by rmroc451** [comment]
> I don't think this is something we can add to Generic Button and will to be added in Preset Button or a completely separate button. Is there any preferred display for this? (e.g. analog vs. digital)

I see we have mention of it in thr flight connector, but never set it to anything on the aircraft status update. Can we hook in here some how?

**Comment by 614NLV** [comment]
personally I always prefer an analog one
simple, like the one pictured
but if this has to be redone from scratch
then you can draw them like the real ones
as 
![clock](https://user-images.githubusercontent.com/77018336/110365039-d2efe280-8044-11eb-97aa-14e657a66222.png)
this for the c172

**Comment by rmroc451** [comment]
Any chance you like this basic use in Toggle @nguyenquyhy or @614NLV?

doing a kind of "override" of display to parse apart the seconds in ZULU/LOCAL time variables, and using the decimal precision as a kind of flag to show if you want hh:mm:ss or hh:mm

I can be persuaded to fully blow this out into it's own button, but maybe this gets us basically what we need?

![image](https://user-images.githubusercontent.com/15070945/111428011-f1994d80-86c4-11eb-8aea-ca52912422ab.png)

**Comment by 614NLV** [comment]
great! yes, this basically gives us what we need: time ;)

**Comment by nguyenquyhy** [comment]
Released in v0.31

**Comment by 614NLV** [comment]
Great, thanks ;)
