### ISSUE TITLE
CJ4 variables

### ISSUE THREAD

**Issue by jFly123** [nguyenquyhy/Flight-Tracker-StreamDeck#202]
Would it be possible to implement Mobiflight CJ4 FMS variables as well?

Thanks!

CJ4_FMC_1_BTN_IDX
CJ4_FMC_1_BTN_MSG
CJ4_FMC_1_BTN_DIR
CJ4_FMC_1_BTN_TUN
CJ4_FMC_1_BTN_FPLN
CJ4_FMC_1_BTN_LEGS
CJ4_FMC_1_BTN_DEPARR
CJ4_FMC_1_BTN_PERF
CJ4_FMC_1_BTN_DSPL_MENU
CJ4_FMC_1_BTN_MFD_ADV
CJ4_FMC_1_BTN_MFD_DATA
CJ4_FMC_1_BTN_PREVPAGE
CJ4_FMC_1_BTN_NEXTPAGE
CJ4_FMC_1_BTN_EXEC
CJ4_FMC_1_BTN_CLR
CJ4_FMC_1_BTN_CLR_Long
CJ4_FMC_1_BTN_L1
CJ4_FMC_1_BTN_L2
CJ4_FMC_1_BTN_L3
CJ4_FMC_1_BTN_L4
CJ4_FMC_1_BTN_L5
CJ4_FMC_1_BTN_L6
CJ4_FMC_1_BTN_R1
CJ4_FMC_1_BTN_R2
CJ4_FMC_1_BTN_R3
CJ4_FMC_1_BTN_R4
CJ4_FMC_1_BTN_R5
CJ4_FMC_1_BTN_R6
CJ4_FMC_1_BTN_A
CJ4_FMC_1_BTN_B
CJ4_FMC_1_BTN_C
CJ4_FMC_1_BTN_D
CJ4_FMC_1_BTN_E
CJ4_FMC_1_BTN_F
CJ4_FMC_1_BTN_G
CJ4_FMC_1_BTN_H
CJ4_FMC_1_BTN_I
CJ4_FMC_1_BTN_J
CJ4_FMC_1_BTN_K
CJ4_FMC_1_BTN_L
CJ4_FMC_1_BTN_M
CJ4_FMC_1_BTN_N
CJ4_FMC_1_BTN_O
CJ4_FMC_1_BTN_P
CJ4_FMC_1_BTN_Q
CJ4_FMC_1_BTN_R
CJ4_FMC_1_BTN_S
CJ4_FMC_1_BTN_T
CJ4_FMC_1_BTN_U
CJ4_FMC_1_BTN_V
CJ4_FMC_1_BTN_W
CJ4_FMC_1_BTN_X
CJ4_FMC_1_BTN_Y
CJ4_FMC_1_BTN_Z
CJ4_FMC_1_BTN_0
CJ4_FMC_1_BTN_1
CJ4_FMC_1_BTN_2
CJ4_FMC_1_BTN_3
CJ4_FMC_1_BTN_4
CJ4_FMC_1_BTN_5
CJ4_FMC_1_BTN_6
CJ4_FMC_1_BTN_7
CJ4_FMC_1_BTN_8
CJ4_FMC_1_BTN_9
CJ4_FMC_1_BTN_DOT
CJ4_FMC_1_BTN_PLUSMINUS
CJ4_FMC_1_BTN_DIV

https://docs.google.com/spreadsheets/d/1jTXlcHaJWx0B7TB63Pmma7bKwpxsxXJO6EJ3ECt7zpc/edit#gid=842037543

**Comment by pjglewis** [comment]
They seem to already be in my Mobiflight events file.  Have you tried them as MOBIFLIGHT_CJ4_FMC_1_BTN_6 etc already?

**Comment by vicentezc** [comment]
> They seem to already be in my Mobiflight events file. Have you tried them as MOBIFLIGHT_CJ4_FMC_1_BTN_6 etc already?

Hello,
I am very interested by this one as well. Is it just a matter of adding these events to 'TOGGLE_EVENT.cs' and prefixing them with 'MOBIFLIGHT_'?
Thanks!

**Comment by jFly123** [comment]
Yes, I've tried MOBIFLIGHT_CJ4_FMC_1_BTN_6 already, but it won't work. G1000 commands work well. I don't see CJ4 commands on toggle_event.cs. Maybe that's the reason. If I add a line there, nothing happens. I'm not sure if I'm supposed to build some package to get it work...

**Comment by nguyenquyhy** [comment]
Yeah you need to compile it. I'll add those in next update.

**Comment by jFly123** [comment]
Ok, good to know. Thank you!
Do you have an estimate for next update?

**Comment by vicentezc** [comment]
Thanks @nguyenquyhy ! 👍

**Comment by nguyenquyhy** [comment]
Should be this weekend :D

**Comment by vicentezc** [comment]
For info, I tried adding one var in TOGGLE_EVENT.cs for testing (e.g. MOBIFLIGHT_Generic_Upr_Push_NAV), recompiled and deployed, but it's not working.
![Screenshot 2021-03-15 225452](https://user-images.githubusercontent.com/74352566/111226477-7c088100-85e1-11eb-8dd4-47e77115c02d.png)

I tried with one of the AS3000 MOBIFLIGHT vars and those ones are working fine.

**Comment by jFly123** [comment]
I actually got it working. Variables were missing from my Mobiflight WASM module event list.
I also added them to "toggle event.cs" and re-compiled. I'm not sure which was the right move but it works anyways.
I'm able to control FMC with Stream Deck. Its layout isn't the best, but it's way better than clicking with mouse.

**Comment by vicentezc** [comment]
@jFly123: cool! Is it just a matter of updating the 'events.txt' in the mobiflight-event-module folder/modules?
In the latest version I downloaded the CJ4 and A32NX vars were already there.

**Comment by rmroc451** [comment]
> @jFly123: cool! Is it just a matter of updating the 'events.txt' in the mobiflight-event-module folder/modules?
> In the latest version I downloaded the CJ4 vars were already there.

We'll have to get the new mobiflight events in our allowed list of events, which I think we'll add this weekend with @nguyenquyhy 's new release

**Comment by jFly123** [comment]
> @jFly123: cool! Is it just a matter of updating the 'events.txt' in the mobiflight-event-module folder/modules?
> In the latest version I downloaded the CJ4 vars were already there.

I updated events.txt and also compiled Flight Tracker with build.bat. I had some errors with incorrect .NET version. I updated it  and still got an error, so I'm not quite sure what happened on my computer, but anyways it is working.

**Comment by nguyenquyhy** [comment]
The CJ4 list above is added in v0.31.
