### ISSUE TITLE
NG % / TBM930

### ISSUE THREAD

**Issue by Kaledozor** [nguyenquyhy/Flight-Tracker-StreamDeck#205]
after trying everything with the ENG _... I can't find the value to display the NG % of the TBM930.

**Comment by Cotam57** [comment]
Interested also...

**Comment by diaznet** [comment]
I can access it with TURB ENG CORRECTED N1

**Comment by nguyenquyhy** [comment]
Please feel free to reopen this if the suggestion above doesn't work for you.
