### ISSUE TITLE
Feedback value comparison operators - Addition of 'AND'

### ISSUE THREAD

**Issue by pjglewis** [nguyenquyhy/Flight-Tracker-StreamDeck#209]
Hi
Would it be possible to add 'and' to the feedback value comparison operators?

![Capture 6](https://user-images.githubusercontent.com/80406959/110665691-8204f900-81c0-11eb-9300-9928c3757e1e.PNG)

This would enable me to pin down (and display as 'on') feedback results with recurring decimal places e.g. FLAPS_HANDLE_PERCENT>66 AND<67 where the actual value on FLAPS_2 is 66.666etc. (on the Cessna 172)

Thanks
Peter

**Comment by nguyenquyhy** [comment]
Boolean is a bit complicated to do, especially for this purpose. How about a new ~ operator that will round up the number before comparing?

**Comment by pjglewis** [comment]
Wow that was quick
That would work. 
I tried fiddling with the existing decimal places field to see if it had that effect, but it just changed what was visible. An operator like the INT function in Excel would be perfect.
Thanks
Peter

**Comment by nguyenquyhy** [comment]
`~` operator is released in v0.31.
