### ISSUE TITLE
Not getting results for FUEL TANK SELECTOR 

### ISSUE THREAD

**Issue by SnugglePilot** [nguyenquyhy/Flight-Tracker-StreamDeck#21]
(with v0.5)

In the C172, I'm trying to get a Generic Toggle Button to light up if the fuel selector is set to both. This should be `FUEL TANK SELECTOR:1==16` as indicated in the example docs, but it doesn't seem to be working - nor can I get it to work with any other value than 16. 0 works but I'm guessing this is a default/null return.

I tried to "debug" using a gauge and setting the display value to `FUEL TANK SELECTOR:1` but it is always reporting zero as well. I'm not sure if gauges are set up to display these things. I also tried to output the value in the "display value" field of the generic button but no luck there.

I also tried `GENERAL ENG FUEL VALVE:1` and `RECIP ENG TANK SELECTOR:1` but I'm not getting any results from these either.

From all aspects it seems like these should work - considering you put examples in the documentation though, maybe I just have the setup wrong. Can you show me how you did it there?

My current setup:

![image](https://user-images.githubusercontent.com/962291/92537776-dae3dc80-f1f1-11ea-8137-5a396bbaa320.png)

**Comment by SnugglePilot** [comment]
(also; "both" is technically an index of `==1` and "all" is `==16`, not sure if either or both works, but once I get these values showing anything other than zero I'll be able to dig in there)

**Comment by nguyenquyhy** [comment]
FUEL TANK SELECTOR:index actually works. We just haven't added that in yet. I'll add it in the next update.

By the way, the value for both would be 1, off is 0, left is 2 and right is 3.

**Comment by nguyenquyhy** [comment]
`FUEL TANK SELECTOR:index` is added in 0.9.
