### ISSUE TITLE
Is it possible to enable the issuing of 'repeating' commands by holding down the 'event key?

### ISSUE THREAD

**Issue by pjglewis** [nguyenquyhy/Flight-Tracker-StreamDeck#210]
Hi
Me again. I was just wondering if it was possible to make an event such as ELEV_TRIM_DN keep incrementing until the max/min is reached simply by holding down the key, as opposed to the current method of having to keep jabbing at it a few hundred times?
Thanks
Peter

**Comment by nguyenquyhy** [comment]
Coming up next update ;)

**Comment by pjglewis** [comment]
Excellent. Can't wait
Thanks
Peter

**Comment by nguyenquyhy** [comment]
Released in 0.30
