### ISSUE TITLE
Add  GPS_OBS    inc & Dec  to the +  & -  Button Functions

### ISSUE THREAD

**Issue by N6722C** [nguyenquyhy/Flight-Tracker-StreamDeck#211]
Add  GPS_OBS    Inc & Dec  to the +  & -  Button Functions

ie  so  they act like say  VOR  or HEADING,  (   (short press 1,  Long press 10)  but  on Event  "GPS_OBS_INC"     and  "GPS_OBS_DEC"

**Comment by nguyenquyhy** [comment]
Released the events for generic buttons in v0.31
