### ISSUE TITLE
Custom Guage  -  Display value out of range -  below MIN

### ISSUE THREAD

**Issue by N6722C** [nguyenquyhy/Flight-Tracker-StreamDeck#212]
Below are some useful information that you can include to help with troubleshooting the issue:
- Stream Deck Plugin and MSFS version
- Description of the issue & expected behavior
- Steps to reproduce the issue
- If the issue happens consistently, an export of your profile would help tremendously.
- Log files at `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log`
- Screenshots

**Comment by N6722C** [comment]
Custom Gauge -  
When Display value > MAX, value turns red   (CORRECT)

When Display value < MIN  value **DOES NOT** turn Red  (but  it's out of range)

If its out of range  MAX  or **MIN**,  it should turn Red.

**Comment by nguyenquyhy** [comment]
Released in v0.32.
