### ISSUE TITLE
SimConnect Variable(s) Addition: FUEL_SELECTOR_#_SET

### ISSUE THREAD

**Issue by Epidurality** [nguyenquyhy/Flight-Tracker-StreamDeck#213]
SimConnect successfully (tested with SPAD) monitors and obeys the FUEL_SELECTOR_2_SET event, but this doesn't appear to be implemented in the TOGGLE_EVENT.cs yet. I assume the same would go for FUEL_SELECTOR_3 and 4_SET. Tested in the DA62.

FUEL_SELECTOR_SET (aka, for the first selector) works flawlessly, sets the values using Toggle Parameter, etc. The FUEL_SELECTOR_2_OFF, LEFT etc all work, but there's a handful of selection modes that are only accessible through their SET indexes.

Is it possible to add these values ourselves as we come across them? Tried looking for a place in the plugin to modify the TOGGLE_EVENT file but I don't know anything about how these plugins work.

**Comment by nguyenquyhy** [comment]
I'll add in the next version this weekend if you can wait a bit 😁.

**Comment by Epidurality** [comment]
> if you can wait a bit 😁.

Of course! Glad to see you're still making updates to this. It's by far the best use of the streamdeck for MSFS already, and you're only making it better!

**Comment by nguyenquyhy** [comment]
Haha if you look at the issue list, I still have a lot to do 😂. Just that I have to spread my weekend time among Flight Recorder, Flight Events and this (and several other upcoming stuffs 😋) so I have to alternate from time to time.

**Comment by Epidurality** [comment]
Ah! Figured out how to edit the TOGGLE_EVENT.cs and rebuild the plugin after getting Dotnet installed. You've made it idiot-proof, almost (at least one idiot missed the obvious .bat files you gave). Added the events myself and they work. 

Do you have a preferred way for us to suggest events and data that we verify but have not yet been added to main? Just pull the TOGGLE_EVENT.cs and TOGGLE_VALUE.cs to make the changes (new to the GitHub process, sorry)?

**Comment by rmroc451** [comment]
take a screenshot of your `toggle_event.cs` and paste it here, I'll add them in for you!

I tried tinkering with them last night, but wasn't making progress on how they interacted with teh DA62 :)

**Comment by Epidurality** [comment]
I'll post my additions once I'm done adding and testing them. Managed to get the AUX fuel transfer pump events/values working for the DA62, which are some pretty weird MSFS-specific simconnect values, so I assume this plugin is fairly flexible with what it allows and is able to grab from the sim; seems like it can grab everything that SPAD.next sees, which is a lot.

**Comment by rmroc451** [comment]
if you are up for attempting to create a branch and a subsequent PR, be my guest. I know that discourages a lot of folks though :)

**Comment by Epidurality** [comment]
Would it make sense to just export what SPAD.next has listed, convert the format to what the .cs files need, and use that as the master list of events and values? It would certainly make any drop-down-list implementation dirty since it's thousands of values, but it would cover everything.

**Comment by nguyenquyhy** [comment]
Since I am working on allowing arbitrary event, I would prefer the list in TOGGLE_EVENTS.cs to be exclusively what has been tested that really has some effect in the sim. If everything went well, eventually the list will be mainly for autocompletion 😄.

**Comment by Epidurality** [comment]
> Since I am working on allowing arbitrary event

Excellent. I'm already halfway through exporting the list from SPAD, so I can post it as a temporary thing for anybody else who wants it when I'm finished (might also be the only list of its type? couldn't find any lists online that included as many as SPAD has listed), but I'm glad to hear about arbitrary values being supported eventually.

**Comment by nguyenquyhy** [comment]
Released in v0.31.
