### ISSUE TITLE
FLC Increase/Decrease Only Increments by 10s

### ISSUE THREAD

**Issue by Epidurality** [nguyenquyhy/Flight-Tracker-StreamDeck#214]
The Press and Hold functions of the "Air Speed" and "Vertical Air Speed/AirSpeed" increase and decrease value buttons only go by increments of 10, instead of increments of 1 (on press) and of 10 (on hold) as would be expected based on behavior of the other incr/decr buttons.

**Comment by nguyenquyhy** [comment]
Yah I didn't add acceleration for VS and AS. Is it needed?

**Comment by Epidurality** [comment]
> Is it needed?
For the vertical speed, probably not. 10 knots is a fairly big jump for something like the C172 though, would be nice to have the granularity. I thought it may have been a bug since the other inc/decr buttons had acceleration.

**Comment by nguyenquyhy** [comment]
For Airspeed, it is possible that it's the 10/1 bug issue in the sim because the plugin just call increase/decrease event in SimConnect.

For vertical speed, the plugin does its own calculation so the increment is fixed at 100ft/s.
