### ISSUE TITLE
Events no longer working

### ISSUE THREAD

**Issue by Virtual-Chris** [nguyenquyhy/Flight-Tracker-StreamDeck#220]
After a while away from the sim, I'm back and my previous profile that used  PITOT_HEAT_TOGGLE and  ANTI_ICE_TOGGLE is no longer working with these two events.  The two related feedback values still work for PITOT HEAT and STRUCTURAL DEICE SWITCH  (if I toggle the buttons in the sim using the mouse)

**Comment by nguyenquyhy** [comment]
I just checked and both events are still in the list, so it's just up to the aircraft to support those events. However, there might be some other problem with the profile. If you don't mind attaching the log file at `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin` (file name is like flightstreamdeck{date}.log), I'll take a look.

**Comment by Virtual-Chris** [comment]
Hi, I found the problem... there were spaces in front of these event entries in the Stream Deck fields.  Either somehow spaces got added or they were always there and at some point that made them stop working :)  Anyway, all good now!

**Comment by nguyenquyhy** [comment]
Oh I usually have that same issue with extra spaces when copy the variables from the web. Maybe I should do something about that.

**Comment by nguyenquyhy** [comment]
Close this and the enhancement is tracked in #228
