### ISSUE TITLE
Using a simulation variable to modify an event button

### ISSUE THREAD

**Issue by schuey97** [nguyenquyhy/Flight-Tracker-StreamDeck#223]
Is it possible to use a value from a variable retrieved by the sim to modify how a toggle button will perform?

For example.
Currently able to work the pushback with event "TOGGLE_PUSHBACK" and stop the pushback with "TUG_DISABLE". However when wanting to setup a button to perform a pushback left or right using KEY_TUG_HEADING, this appears to require the current heading of the aircraft subtracting a 32bit integer which represents 0-360 degrees. 

So I'm guessing a toggle button would need to be set with a toggle event "KEY_TUG_HEADING", then the ability to pass a parameter  {SIM Variable: PLANE HEADING DEGREES MAGNETIC} - (4294967295 / 8) to perform a 45 degree angle turn from the current heading.

I know there are other programs out there to perform this task, just thought it would be handy to have it possible in one place as I can already start/stop the pushback.

If not possible, all good :)

**Comment by nguyenquyhy** [comment]
Right now you can put a variable as the parameter of a toggle event, but no maths is supported yet.

**Comment by nguyenquyhy** [comment]
I'll close this and will track in another issue #224.
