### ISSUE TITLE
Image Glitches after update to 0.31

### ISSUE THREAD

**Issue by schuey97** [nguyenquyhy/Flight-Tracker-StreamDeck#225]
Hey All
Have noticed a strange issue after updating from 0.30 to 0.31.
As per below screenshot, the streamdeck icons appearing to be glitching and after a while the headings of certain buttons will overlay other buttons and then become a huge mess no longer being able to read what each button is.
![20210402_130016](https://user-images.githubusercontent.com/77967212/113374174-090a5300-93b4-11eb-91bf-db107eab86c5.jpg)

-At first I proceeded to remove all community folders and run the game as vanilla. Issue continued to happen. (Even found the buttons would start to have issues while in the World Map before even getting into the game)
-Uninstalled the Flight-Tracker addon and also the Streamdeck software. 
-Reinstalled Streamdeck software, then the Flight-Tracker addon. Did not load my profile back into Streamdeck and just used the basic COM/NAV frequency profile. The picture attached above was taken during the phase.
-Decided to uninstall the Flight-Tracker addon again and this time install version 0.30
-This time using the COM/NAV frequency profile everything worked fine with no issues.
-Updated to version 0.31 again and the issue re-appeared.
-Downgraded to 0.30 again and COM/NAV frequency profile worked. This time re-imported my stream deck profile back in with all of my buttons and all worked with no issues.
-Upgraded to version 0.31 and the issue presented itself again.

Attached is the log files as well.
[flightstreamdeck20210402.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6247395/flightstreamdeck20210402.log)

**Comment by rmroc451** [comment]
Can you try clearing a button background and reuploading?

Are you embedding or just linking to an image file on your machine? 

Can you also export the profile and attach it here as well? You might have to zip it to attach.

**Comment by Santamaria13** [comment]
I‘ve the same issues, artifacts and yellow gauges on toggle buttons. Back to v 0.30 and it works again.
My settings: MSFS2020, streamdeck XL, flighttracker and AAO, a lot of Profiles, less folders

**Comment by schuey97** [comment]
Hi rmroc451

I have found that the majority of glitches happen on buttons without a background. (Just to note, all background images are linked from my computer and not embedded)

I'm able to get the issue to repeat itself by creating a brand new profile. When testing to determine the issue, I uninstalled all of my stream deck software and started fresh with a very simple profile.  (At this time my original profile had not been reimported back into Streamdeck) The profile basically had two preset buttons (COM1, COM2) that would open up the COM/NAV frequency profile page. 

The glitch would happen on all the COM/NAV frequency profile page buttons and the two preset COM1 and COM2 buttons. 

No background images were applied.

If you still need my main profile, let me know and will organize to upload it.

**Comment by rmroc451** [comment]
I'll give this a look tonight or tomorrow. We are doing some resize constraining of the background (regardless if you have one or not, since we have the default).

That now protects us from folks setting huge dpi images as their background and getting suuuuuper small text on the image, as it scales it to fit in the button window.

I wonder, you both have XLs, and I only have the 15 button. I have to look of the dpi is higher on the XL and me trying to scale it to 72 pixels when it might be double is an issue.

It's a place to start. :)

**Comment by nguyenquyhy** [comment]
It doesn't have to be XL. I got this issue too but I couldn't figure out what I did 😂. A restart of the stream deck software (hence the plugin) would fix this issue so I didn't think much about it before.

**Comment by rmroc451** [comment]
Thanks for the info Hy! I hadn't seen it in my local dev, or the install I got after. Odd.

I do have backgrounds on most of my buttons though (a slate grey).

**Comment by Santamaria13** [comment]
Hi Hy, another hint to localize the bug, at the generic toggle button appears instead of the black and green sign the yellow arc of the gauge.
Maybe it helps ;-)

**Comment by nguyenquyhy** [comment]
I think I found the issue. I'll release an update late tonight. 😄

**Comment by nguyenquyhy** [comment]
Released in v0.32.
