### ISSUE TITLE
Display problems

### ISSUE THREAD

**Issue by jaguaaaar** [nguyenquyhy/Flight-Tracker-StreamDeck#233]
Hi, i frequently have many display issues with flight tracker on my streamdeck, I honestly don't know if these are flight tracker issues or stream deck issues (I've bought it a few days ago and use it only for MSFS with Flight Tracker)
My issues concern only  generic and preset toggle buttons.
I join some pitures to show you the problems.
I precise that I see the same display problems in the stream deck software AND on the stream deck itself.

Thanks a lot, and despite everything, great job !! :)

![1617727060443](https://user-images.githubusercontent.com/17533305/113748728-223f3680-9709-11eb-9f13-0688708dd81d.jpg)
![1617727060440](https://user-images.githubusercontent.com/17533305/113748729-22d7cd00-9709-11eb-849a-a6ef9ef958f0.jpg)
![3bug stream2](https://user-images.githubusercontent.com/17533305/113748730-23706380-9709-11eb-9308-869f16e9ad89.png)
![bug stream2](https://user-images.githubusercontent.com/17533305/113748732-23706380-9709-11eb-8e31-663535189bad.png)
![bug stream](https://user-images.githubusercontent.com/17533305/113748733-23706380-9709-11eb-87f1-9e3f1b373cfc.png)
![1617727060445](https://user-images.githubusercontent.com/17533305/113748735-2408fa00-9709-11eb-8f26-d91f4863a3ab.jpg)

**Comment by nguyenquyhy** [comment]
The pink mess should be fixed in the latest version (you are using 0.31, right?). I'm still investigating the mixed-up background where one button seems to get to all other buttons.

**Comment by jaguaaaar** [comment]
Yes I'm in 0.31. I use simconnect in network configuration (stream deck not on the MSFS machine), but i had already the problem when the deck was connected to the same machine too...
Thanks !

**Comment by jaguaaaar** [comment]
Juste to add some informations, I have downgraded to the 0.29, and the issues are all solved, no display bug at all... 
I'll try tomorrow différent versions, including the 0.32 to give you some clue and help to find the guilty commit ;)

**Comment by nguyenquyhy** [comment]
Can anyone try again in 0.34? I'm still not too sure about the cause but the latest version seems to fix this issue.

**Comment by jaguaaaar** [comment]
Hello, the 0.33 was not ok, I didn't have much time to check but it seems to be ok now with the 0.34, give me some time to be sure but I'm confident :)
Thanks

**Comment by jaguaaaar** [comment]
It's ok for me, no more problem !
Thanks a lot :)
