### ISSUE TITLE
WT-CJ4 Mobiflight Events List

### ISSUE THREAD

**Issue by juyttewaal** [nguyenquyhy/Flight-Tracker-StreamDeck#237]
Please add the attached list of Mobiflight WT-CJ4 events to the next release of TOGGLE-EVENTS.cs.
Thank you,

Johan
![WT-CJ4](https://user-images.githubusercontent.com/79478405/115583839-1dd55a80-a27f-11eb-9646-cb0bb486ca03.JPG)

**Comment by nguyenquyhy** [comment]
This is added in 0.34. Sorry it takes quite long 😄.

**Comment by juyttewaal** [comment]
Thank you so much! This is a great addition for the CJ4.
