### ISSUE TITLE
Ocasionally multiple instances of the addon open at boot

### ISSUE THREAD

**Issue by SamGreenwood1** [nguyenquyhy/Flight-Tracker-StreamDeck#239]
I've noticed that sometimes when I boot up my system there are multiple instances of the addon in my system tray. I'm running v0.29 of the addon, v4.93 of Stream Deck software and Windows 10 Pro 20H2 build 19042.

**Comment by nguyenquyhy** [comment]
Can you try again with latest version 0.34? We have fixed many crashes since 0.29.

**Comment by nguyenquyhy** [comment]
You can download the new version in Release section of this repository, or from flightsim.to https://flightsim.to/file/3178/flight-tracker-streamdeck-plugin. Then just double click the .streamDeckPlugin file.

**Comment by nguyenquyhy** [comment]
Please reopen if this still happens in latest version. Close for now 😄
