### ISSUE TITLE
Flight Tracker Stream Deck Plugin and P3D V5 

### ISSUE THREAD

**Issue by FalconBlock50** [nguyenquyhy/Flight-Tracker-StreamDeck#241]
Is the Flight Tracker Stream Deck Plugin a MSFS2020-only connection?
I tried to connect to P3D V5 but there is no response.
No commands can be communicated.
The green light on the Flight Tracker Stream Deck icon is lit.
Is the version of SimConnect different?

**Comment by nguyenquyhy** [comment]
You can find a similar question on this in the Discussion section of this repository. 

Technically you just need to change the library and rebuild. Most stuffs should work, but I already stopped playing P3D for so long and I generally don't want to provide anything that I don't test.

**Comment by FalconBlock50** [comment]
I found a thread called Compile for P3D V5 from the discussion page.
I stopped the method of compiling to the point because I sometimes use FS2020.
I also tried the CFG method, but it didn't work.
In the next version upgrade, I would be happy if there was a SimConnect switching function in the program.

**Comment by rkantos** [comment]
> I found a thread called Compile for P3D V5 from the discussion page.
> I stopped the method of compiling to the point because I sometimes use FS2020.
> I also tried the CFG method, but it didn't work.
> In the next version upgrade, I would be happy if there was a SimConnect switching function in the program.

I recommend you to also try https://github.com/Fragtality/PilotsDeck/releases - which supports P3D quite well (also MSFS), but using FSUIPC.
