### ISSUE TITLE
AoA indicator

### ISSUE THREAD

**Issue by falkeblikket** [nguyenquyhy/Flight-Tracker-StreamDeck#249]
Angle of attack is listed in the SimConnect SDK as ANGLE_OF_ATTACK_INDICATOR (Units:Radians, Type:TYPE_SINT16). It would be wonderful to have it implemented into the Flight-Tracker-StreamDeck plugin.

**Comment by nguyenquyhy** [comment]
Added in v0.35

**Comment by diaznet** [comment]
At least on the TBM, the AOA value is strange. I see it at = in the sim, but the value returned is 3.
Also this value never changes outside of 3 (normal) or 2 (stall).

**Comment by falkeblikket** [comment]
Yup, I think it,s radians, so you need decimals to see changes. I think 180 degrees = 3,1415 radians is equivalent to 0 degrees on the pitch axis relative to airspeed, but i have not figured out the exact conversion  to AoA seen on instruments in the cockpit, maybe it differs from aircraft to aircraft.

**Comment by diaznet** [comment]
> Yup, I think it,s radians, so you need decimals to see changes. I think 180 degrees = 3,1415 radians is equivalent to 0 degrees on the pitch axis relative to airspeed, but i have not figured out the exact conversion to AoA seen on instruments in the cockpit, maybe it differs from aircraft to aircraft.

Yes you are right, thanks a lot, I had missed this.
Until we have the ability to do math operation (#224) I will stick with the degrees display.
