### ISSUE TITLE
Stream Deck Unresponsive Problem

### ISSUE THREAD

**Issue by tmbailey70** [nguyenquyhy/Flight-Tracker-StreamDeck#252]
Every time I try to create or edit Flight Tracker buttons when MSFS2020 is running the Stream Deck application becomes unresponsive and must be restarted.

The only way I can use the Flight Tracker plugin to create or edit buttons is if the simulator isn't running, which makes things difficult in having to continually quit and restart to check functionality.

If a button has been created prior to the simulator starting everything works ok.

Appreciate any help.

**Comment by nguyenquyhy** [comment]
This is strange. Can you please share the log files in `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin` (normally named like flightstreamdeck20210601.log)

**Comment by tmbailey70** [comment]
Log files attached.
MSFS2020 is most recent version.  Stream Deck version is 4.9.4.13228.
Computer is clean install with windows 10 fully updated.

[flightstreamdeck20210602_001.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582055/flightstreamdeck20210602_001.log)
[flightstreamdeck20210602_002.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582057/flightstreamdeck20210602_002.log)
[flightstreamdeck20210602_003.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582058/flightstreamdeck20210602_003.log)

**Comment by nguyenquyhy** [comment]
The log files are very weird. They are almost empty and with a strange file name format. 
Do you have any logs on the day you have all those hangs?

**Comment by tmbailey70** [comment]
Have found the issue through a lot of testing and searching the web.  The problem exists when using the Stream Deck application and the Flight Tracker plugin on a 2nd monitor.  

If using on primary monitor there is no problem and everything works fine.

Drag to second monitor and application goes to 'not responding' when trying to create /edit buttons etc.

This doesn't appear to be an issue with plugins not associated with MSFS2020.  The same problem occurs when using the Lorby AxisAndOhs plugin.

**Comment by nguyenquyhy** [comment]
Are you using monitors with G-Sync/Free Sync? I am also using 2 monitors but I have never noticed that. I'll do some more testing.

**Comment by tmbailey70** [comment]
Primary monitor is G-Sync.  2nd monitor isn't.

**Comment by nguyenquyhy** [comment]
That's even more strange since I have the exact same setup and I still can't reproduce it. Did you find anything on the Internet describing the cause or something related?

**Comment by tmbailey70** [comment]
Found this which is what made me test it.

https://www.reddit.com/r/ElgatoGaming/comments/eag586/streamdeck_software_not_responding_when_adding/

Found these logs.  Not sure if they help.

[StreamDeck0.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582534/StreamDeck0.log)
[StreamDeck2.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582536/StreamDeck2.log)
[StreamDeck3.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582537/StreamDeck3.log)
[StreamDeck4.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582538/StreamDeck4.log)
[StreamDeck5.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582539/StreamDeck5.log)
[StreamDeck6.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582540/StreamDeck6.log)
[StreamDeck7.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582541/StreamDeck7.log)
[StreamDeck8.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582542/StreamDeck8.log)
[tech.flighttracker.streamdeck0.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6582543/tech.flighttracker.streamdeck0.log)

**Comment by craigusus** [comment]
Any luck on this? I'm getting the same issue. Every since SU5, StreamDeck just becomes unresponsive or takes a few seconds to respond. Remove the plugin and it's back to normal, reinstall the plugin and back to unresponsive.

**Comment by craigusus** [comment]
@tmbailey70 @thestonefox, Just out of interest is your StreamDeck plugged direct into your PC or via a USB hub?

**Comment by thestonefox** [comment]
> @tmbailey70 @thestonefox, Just out of interest is your StreamDeck plugged direct into your PC or via a USB hub?

Mine is plugged directly into the PC

**Comment by craigusus** [comment]
> > @tmbailey70 @thestonefox, Just out of interest is your StreamDeck plugged direct into your PC or via a USB hub?
> 
> Mine is plugged directly into the PC

Great thanks. It seems to have reared its head again for me in SU7. I'm just doing some tests with the StreamDeck plugged directly into a USB 2.0 port on the front of my PC (opposed to a powered USB 3.0 hub). Seems stable so far...  🤞🏻

**Comment by craigusus** [comment]
So I've purchased a [PCI-E to USB 3.0](https://amazon.co.uk/gp/product/B08PF8XR73) card and plugged my StreamDeck directly into that. I've had no slow/unresponsive issues since.

**Comment by noblackthunder** [comment]
Howdy ! i see this closed as "notAbug" Sadly i think what Craigusus did is not working for us others that have the issue. I pluged mine directly into my pc too .. and not matter if the sim runs or not .. each time i click now a button the elgato software just stops responding ( hard locked up) i had a look at the loog files but it does not seem to log anything if interrest.. The buttons i managed to setup work fine ( as long as i dont make the stream deck software to lock up)


i can replicated it prett easily ... sadly its also a bit random. the only thing for sure is that when it happens i have to uninstall the plugin and reinstall it to make it work for a short while.  Even restarting my pc is not solving the issue

**Comment by nguyenquyhy** [comment]
This is really strange. The plugin doesn't save any data, so restarting Stream Deck app (or your PC) should be exactly the same as reinstall. 

Also, I was suspecting that the issue maybe because the plugin sends data too frequently for certain USB cable, but if this happens even without the sim running, it shouldn't be the case. When the sim is not running the plugin doesn't send any image to the Stream Deck other than an initial blank one.

**Comment by noblackthunder** [comment]
![image](https://user-images.githubusercontent.com/1668416/171981840-e807cb83-e4d0-47ed-8bc4-8444f8c66ed4.png)
![image](https://user-images.githubusercontent.com/1668416/171981849-59740329-45e9-453a-92ee-d792570369d1.png)


all i did ( while the sim was off ) was click on the generic toggle button APU/O ( the last one) and as you can see stream deck instantly crashes .. So i cant even configure buttons .. the only way for me to solve this is to reinstall the plugin after delelitng it .. sadly thats all i know how to cause it :-/

**Comment by nguyenquyhy** [comment]
After the stream deck crashes, what happens when you open it again?

**Comment by noblackthunder** [comment]
I get back to the normal window .. all buttons work but if i try to edit any of the buttons or add any the stream deck software crases again .. this only happens if i try to edit a button

**Comment by noblackthunder** [comment]
![image](https://user-images.githubusercontent.com/1668416/171982527-e7bb7a0d-836e-4fbf-95c2-652dfbd8d3c5.png)
as an example.. i draged this button to the stream deck .. the stream deck crashed .. if i click it again to try to edit it the streamdeck software crashes again

**Comment by noblackthunder** [comment]
https://www.reddit.com/r/ElgatoGaming/comments/f6z5tq/stream_deck_crashes_whenever_i_try_to_add/

ok maybe ignore my request .. maybe it is a 3rd party issue ... i will have to test this .. could be stream deck software issue with nvidia drivers ? LOL
