### ISSUE TITLE
Not get values from MSFS

### ISSUE THREAD

**Issue by UnsafeAtAnySpeed** [nguyenquyhy/Flight-Tracker-StreamDeck#263]
I have an issue where I am no longer getting values from MSFS to display on my Stream Deck.
I can send commands to perform actions like switch lights on/off, raise and lower flaps and landing gear, and adjust trim with my Stream Deck, but I cannot get values back from the sim.

For example, I use Generic Gauges to display:

Compass          (PLANE_HEADING_DEGREES_MAGNETIC)
Flaps                (TRAILING_EDGE_FLAPS_LEFT_PERCENT)
Trim                 ( ELEVATOR_TRIM_POSITION)
RPM                ( GENERAL_ENG_RPM__1)
Throttle            (GENERAL ENG THROTTLE LEVER POSITION:1)
Propeller          (GENERAL_ENG_PROPELLER_LEVER_POSITION__1)
Mixture            (GENERAL ENG MIXTURE LEVER POSITION:1)
etc.,

all I see are zeroes or no values at all (just the Header).

The NAV & COM buttons used to display frequencies, now all I see is the type, i.e., "COM1" or "NAV1" on the button.
Clicking on it used to open the Numpad, but now it does not.

This all worked in the past, but since I have not used my Stream Deck in a few months, I don't know when it actually stopped working.  As a test, I installed a couple of new profiles from flightsim.to and I get the same results -- no output to the gauges.
I even recreated the first example from the user's guide to display the current value of the autopilot heading bug and that didn't work -- all you see is "HDG".  I also removed everything from the Community folder and re-tested with no change.

I am using:
  MSFS version is 1.17.3.0 (the latest Nordics mod).
  Stream Deck software version 5.0.1
  Flight Tracker plugin version 0.35

I've also attached a profile and couple of log files.
Let me know if you need more information.

Thanks!

[Test Profile.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6678948/Test.Profile.zip)
[flightstreamdeck20210618.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6678940/flightstreamdeck20210618.log)
[flightstreamdeck20210617.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/6678941/flightstreamdeck20210617.log)

**Comment by nguyenquyhy** [comment]
From the log I can see the error is from this button:
- `ANGLE OF ATTACK INDICATOR` with unit of `Units:Radians`

`Units:Radians` is an invalid value for unit so it will cause issue for the whole page. You can change it to `Radian` or `Radians` instead, although I believe for that variable `ANGLE OF ATTACK INDICATOR`, rad is alsready the default unit.

The strange thing is that I cannot find that button in your profile, so your profile works perfectly for me.

**Comment by nguyenquyhy** [comment]
Please let me know if that fixes your issue, and feel free to reopen this if it does not.

**Comment by UnsafeAtAnySpeed** [comment]
I went through my profiles a double-checked them for any incorrect values and it all seems to be working now. 
Thanks for your help.
