### ISSUE TITLE
A320 FLYBYWIRE PKG BRAKE/AUTOPILOT

### ISSUE THREAD

**Issue by Kaledozor** [nguyenquyhy/Flight-Tracker-StreamDeck#265]
since the last MSFS update, on the A320 Flybywire,
the feedback values no  work:

BRAKE_PARKING_INDICATOR
APMASTER
SPOILERS ARM ON

version streamdek 5.0.1.14252
plugin 0.35

**Comment by nguyenquyhy** [comment]
Unfortunately FBW team devices to go further and further away from SimConnect support, which is the official way for external plugins to interact with the sim. This is not something we can fix.

You can workaround that by using MobiFlight WASM module, which will translate many internal events into SimConnect events. We are adding a bunch of those in the next version https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/commit/1c7d0d6bcf1ab4a200af35b1a53ea2759ca9ebb9 (probably will release this week).

**Comment by Kaledozor** [comment]
Thank you for your answer.
I don't see how MOBIFLIGHT could work with simconnect commands which are no longer recognized.
I haven't found any MOBIFLIGHT controls that work with the A320 FBW.
I tried to manage the APU pages, FUEL nothing is responding.

**Comment by nguyenquyhy** [comment]
A lot of the MobiFlight events are added to this plugin by imodude, and I will release them later today in version 0.36. With the new version you will be able to use the MobiFlight events for 32NX at the bottom of this list https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/main/FlightStreamDeck.Core/TOGGLE_EVENT.cs.

**Comment by Kaledozor** [comment]
Thank you very much for this new version, sacred work!
The TOGGLE are finally working !!
But a question about return values:

TOGGLE EVENT: MOBIFLIGHT_SEATBELT_SWITCH
FEEDBACK VALUE: CABIN SEATBELTS ALERT SWITCH (not working).

Are there any new return values with MOBIFLIGHT?
