### ISSUE TITLE
FLAPS_HANDLE_INDEX skips "1" and goes from "0" to "2"

### ISSUE THREAD

**Issue by thekalbb** [nguyenquyhy/Flight-Tracker-StreamDeck#266]
Using a generic guage and setting FLAPS_HANDLE_INDEX in the display value field - 1 press on flaps button makes guage go to "2"

-Using A320

**Comment by nguyenquyhy** [comment]
Can you provide us with some more information?
- Does it happen on any other aircraft?
- Is it the default A320 or the FBS 32NX?
- Which flap button are you using?

**Comment by thekalbb** [comment]
Just tried g1000 cessna, and it worked as expected - shows 1 on gauge, on 1 lvl of flaps

In a320 fbw it shows "2" on gauge - on 1 lvl of flaps

I tried both the togglebutton flaps toggleevent - and the ingame keybing for flaps down - same result

**Comment by nguyenquyhy** [comment]
I would say that's a bug in the 32NX. Not much we can do in the plugin to fix that.
