### ISSUE TITLE
XPRD keypad is missing numbers [image]

### ISSUE THREAD

**Issue by thekalbb** [nguyenquyhy/Flight-Tracker-StreamDeck#268]
XPRD keypad is missing numbers [image] 

 [Com1 - as intented](https://ibb.co/1n7yBPr)
 [XPDR - missing "8"+"9"](https://ibb.co/vjvv37b)

**Comment by rmroc451** [comment]
You can't set 8 or 9 on a Transponder, that's whybthey are omitted.

**Comment by thekalbb** [comment]
Im an idiot - sorry

**Comment by rmroc451** [comment]
No worries!
