### ISSUE TITLE
Toggle Prebuilt Text Overlay

### ISSUE THREAD

**Issue by chewbaccaslim** [nguyenquyhy/Flight-Tracker-StreamDeck#27]
It would be great to be able to disable the Text overlay on the prebuilt buttons. I am running into all kinds of limitations for buttons like FLC, VS, VNAV, and especially ALT that I want to have an on off button for but the stock commands and/or feedback dont work.

![image](https://user-images.githubusercontent.com/71677396/94064701-4e1b5000-fda7-11ea-8fdc-7426c384e5b5.png)

**Comment by nguyenquyhy** [comment]
Have you tried the Generic Toggle Button? The pre-build AP button was added with a specific design in mind, so it is not very flexible. The generic button however does not have "hold to sync" function yet, as it is a bit more difficult to setup, but we are looking at adding that in the future.

**Comment by nguyenquyhy** [comment]
A new checkbox will be added to allow you to hide the header of the prebuilt buttons.

**Comment by nguyenquyhy** [comment]
Done in version 0.12 😄.
