### ISSUE TITLE
Elevator trim and Directional Gyro events

### ISSUE THREAD

**Issue by dieharder** [nguyenquyhy/Flight-Tracker-StreamDeck#280]
Hi! If you have a moment, could you add the following (if they work and exist in MSFS that is)? Many thanks!!

**events**:
- AXIS_ELEV_TRIM_SET 
- and/or ELEVATOR_TRIM_SET  
   (so I can make a button to reset Elevator trim to neutral)

and 

**events**:
- HEADING_GYRO_SET
- KEY_GYRO_DRIFT_SET

**values**:
- GYRO_DRIFT_ERROR
- HEADING_INDICATOR
(to show, and change gyro settings and drift)

**Comment by nguyenquyhy** [comment]
Released in v0.37.
