### ISSUE TITLE
Where can I find the variables for custom toggles / gauges?

### ISSUE THREAD

**Issue by pilotkid** [nguyenquyhy/Flight-Tracker-StreamDeck#285]
Hello, simple question. Where can I find a list of the variables I can input into fields such as toggles and display values?

**Comment by Kirikou974** [comment]
Hey you can find them all in the TOGGLE_VALUE.cs enum : https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/main/FlightStreamDeck.Core/TOGGLE_VALUE.cs

**Comment by Kirikou974** [comment]
And TOGGLE_EVENT.cs too : https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/main/FlightStreamDeck.Core/TOGGLE_EVENT.cs

**Comment by pilotkid** [comment]
Awesome thank you! Would you mind if I did a PR for documentation?

**Comment by nguyenquyhy** [comment]
Please feel free to improve our user guide https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/main/docs/USERGUIDE.md. Or let us know if you have other suggestion.

**Comment by JuhlWeb** [comment]
Seems like the file TOGGLE_EVENT.cs too has dropped of the great old Internet - can not seem to find it anywhere!! Any clues or pointers would be highly appreciated... ;-)

**Comment by nguyenquyhy** [comment]
@JuhlWeb I moved it to https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/main/FlightStreamDeck.Logics/KnownEvents.cs as it is no longer a restriction. From version 0.39, you can use any valid SimConnect event. I'll update the user guide shortly on this.
