### ISSUE TITLE
g1000nxi alpha keyboard on stream deck

### ISSUE THREAD

**Issue by beau76** [nguyenquyhy/Flight-Tracker-StreamDeck#287]
Hi on the g1000nxi you can click on it and use the keyboard to enter  your route can add an alpha keyboard on the stream deck link the nav number pad

**Comment by Kirikou974** [comment]
Isn't it just a matter of mapping the stream deck actions with the num pad ? Or am I missing the point ? 
![image](https://user-images.githubusercontent.com/21690437/128642656-f180709e-6d40-4e12-95f3-91c549d91b6e.png)

**Comment by beau76** [comment]
what I was looking for is more like the com number pad but instead on numbers have letters

**Comment by nguyenquyhy** [comment]
The numpad of this plugin works separately from the sim. When you press a number in the numpad, nothing is transmit to the sim. Only when you click Enter or Transfer, the whole frequency will be set with a SimConnect event. I don't think there is any SimConnect events to set the next waypoint nor any to transmit a single key to the G1000. That would be a big hurdle in implementing this feature.
