### ISSUE TITLE
Possible to add Auto Pilot FLC Preset Toggle Button?

### ISSUE THREAD

**Issue by Virtual-Chris** [nguyenquyhy/Flight-Tracker-StreamDeck#29]
Is it possible to add a preset toggle button for Auto Pilot FLC (Flight Level Change) mode?  I looked through the toggle values and simulation variables and couldn't see anything that looked applicable.

PS.  Thank you very much for this great add-on... I was doing AP modes on my Stream Deck by simply using keyboard commands but the mode toggles were often out of sync with the aircraft AP state. This is much better!

**Comment by nguyenquyhy** [comment]
Problem is the preset buttons also rely on SimConnect events. I have tried to add FLC to the Preset button, but just like you, I can't find any events nor variables. Once Asobo adds those to SimConnect docs, I'll update the Preset button with FLC.

**Comment by g33z3r-hd** [comment]
What I have found, but not completely figured out, is that FLC isn't listed but when you use the display value of AUTOPILOT AIRSPEED HOLD VAR this value matches the FLC speed in the sim.  That said, using AUTOPILOT AIRSPEED HOLD for the feedback value does NOT indicate when FLC is active.  Also, the Toggle value of AP_AIRSPEED_HOLD sets the AUTOPILOT AIRSPEED HOLD VAR to 990.  I was able to use the Toggle values of AP_SPD_VAR_INC and AP_SPD_VAR_DEC to increase/decrease the FLC speed but it was iffy...sometimes would increase/decrease by 1, other times by 10.  

I have only tested this flying the King Air 350i, I don't know if that matters.  Going to keep playing with it.

**Comment by Virtual-Chris** [comment]
I see you added FLC to the preset buttons in the latest release, but how to you increment or decrement the airspeed?

**Comment by nguyenquyhy** [comment]
I based that on the way FLC work on TBM. Is there a way you can increase/decrease the airspeed in the virtual cockpit?

**Comment by Virtual-Chris** [comment]
Yes, of course you can increase or decrease the speed using the mouse in the cockpit, but the whole point of this is to use the Stream Deck instead.  I guess we should try AP_SPD_VAR_INC and AP_SPD_VAR_DEC as per @g33z3r-hd  comment above... can you try creating a +/- button set for FLC using those values?

**Comment by nguyenquyhy** [comment]
Oh I didn't know 😂. I'll check and add.

**Comment by nguyenquyhy** [comment]
FLC is added in 0.9 and changing airspeed is added in 0.10.
