### ISSUE TITLE
Include missing mobiflight TBM930 variables

### ISSUE THREAD

**Issue by BAF54SQN** [nguyenquyhy/Flight-Tracker-StreamDeck#292]
There seem to be a number of new variables in the latest mobiflight event list (anti ice, electrical,…) could you possibly include them in a future release?

**Comment by WJS11** [comment]
To this, I think a few existing variables have been changed. The Approach toggle no longer returns its state, and the Altitude numerical displays a static number.

**Comment by chiika** [comment]
+1 for this. I was trying to setup gauges for single engine turbo props, ITT and prop RPM are working, but the engine torque variables doesn't seem to exist. And thank you for all your hard work. Love this plugin.

**Comment by nguyenquyhy** [comment]
I just added `TURB ENG CORRECTED N1:index` in v0.39. Would that be enough, or do we still looking for some additional variables?

**Comment by BAF54SQN** [comment]
Hi Nguyen,

I’m also thinking about a number of events to control for example the overhead switches (ex elt)

If you look on https://hubhop.mobiflight.com/#/list and select the TBM930, you get the list of all inputs/outputs implemented in mobiflight 

Have a nice evening,
Robert

**Comment by BAF54SQN** [comment]
Ok that sound fantastic ,👍 thank you !🙏

**Comment by jplewis01** [comment]
> I just added `TURB ENG CORRECTED N1:index` in v0.39. Would that be enough, or do we still looking for some additional variables?

This will work great for NG Thank You! I've not yet yet had time to explore the updated version, but if the change covers 4 engines this will provide support for all all 4 NG vars that would be needed. Now all we need is a C130 Aircraft in the SIM ;-)

I was looking tonight for Events that are needed for Turbo Props and some that lept out are:
THROTTLE_REVERSE_THRUST_TOGGLE
THROTTLE_REVERSE_THRUST_HOLD
PROPELLER_REVERSE_THRUST_TOGGLE
PROPELLER_REVERSE_THRUST_HOLD
TURBINE_IGNITION_SWITCH_TOGGLE
TURBINE_IGNITION_SWITCH_SET

The TBM Throttle system makes reverse thrust problematic to say the least and using buttons to set key states makes simulation a little easier.

**Comment by nguyenquyhy** [comment]
All toggle and hold events should work with latest version of the plugin.

There is no support for Set events yet though as they usually require a bit of custom logic to keep track of the value.
