### ISSUE TITLE
G1000 Workingtitle nxi

### ISSUE THREAD

**Issue by xabim** [nguyenquyhy/Flight-Tracker-StreamDeck#293]
I don't know if I'm missing something or doing something wrong, but the buttons of the g1000 with Workingtitle Nxi are not working is this a known issue? Where is the problem? In this project or in the other one? How can I help?

The system is tested in:
Steamedck 15 buttons MK2
Msfs2020 1.19.8.0
Using 
G1000_PFD_ENTER_BUTTON as Toggle button

Thanks in advance

**Comment by craigusus** [comment]
I'm having a similar issue with the NXi.
Loading in the plane shows 99000 on the Altitude Preset Toggle Button.
![image](https://user-images.githubusercontent.com/6324863/134768064-752bf2bb-ee8b-404d-9c23-cd96986a85a4.png)
But -1200 on the Garmin screen. Also, the Altitude Increase and Decrease buttons do not function.

Removing the NXi from the game, everything goes back to working correctly.

**Comment by nguyenquyhy** [comment]
The workaround is added in v0.38.
