### ISSUE TITLE
Gauges suddenly stopped working

### ISSUE THREAD

**Issue by craigusus** [nguyenquyhy/Flight-Tracker-StreamDeck#294]
- Stream Deck Plugin version: **037**
- MSFS version: **1.19.9.0**
- Description of the issue & expected behaviour:
**No gauges are registering any data as of yesterday (17th Sept 2021)
I flew 2 flights after the 1.19.9.0 hotfix and they were working fine. I loaded up the game today and the gauges no longer work.**

- If the issue happens consistently, an export of your profile would help tremendously:
**[Flight Simulator.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/7189854/Flight.Simulator.zip)**

- Log files at `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log`:
**[flightstreamdeck20210918.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/7189853/flightstreamdeck20210918.log)**

**Comment by rmroc451** [comment]
Did you recently add the flap handle percent to your profile?

% isn't a valid unit, try spelling out the word percent and see if that works.

![Screenshot_20210918-081605_Chrome Beta](https://user-images.githubusercontent.com/15070945/133890322-ae0bb01d-3223-4ca0-89bf-2b426ea02c51.jpg)

**Comment by rmroc451** [comment]
> I wonder if % isn't a valid unit, try spelling out the word percent and see if that works.


Yup, percent or percentage: https://www.prepar3d.com/SDKv5/sdk/references/variables/units_of_measurement.html

**Comment by craigusus** [comment]
@rmroc451 Thank you for the quick reply!
You are correct, changing '%' to 'PERCENTAGE' makes them all work again! Which is odd as they were working yesterday.

![image](https://user-images.githubusercontent.com/6324863/133893753-a57c12ae-c56c-4590-8c3f-ed7c7931ce0b.png)

Anyway, all working now. Thanks again!
Closing.
