### ISSUE TITLE
Separate Taxi Light Toggles

### ISSUE THREAD

**Issue by justadaniel** [nguyenquyhy/Flight-Tracker-StreamDeck#298]
**Description**
Thanks for a great plugin! I think it would be really nice to have a toggle to turn on/off nose landing gear separate from runway turnoff lights. On the A320, 787, and 747, toggling the taxi lights toggles both. 

**Additional context**
Here's the lighting panel for the 747...
![747-lightingpanel](https://user-images.githubusercontent.com/1112585/135494985-e75e3fe9-74f9-4ee1-9c56-8ea83f49eb19.jpg)

and the A320...
![82b823debbbc74c1364b2b5f72b645edfabf83fe](https://user-images.githubusercontent.com/1112585/135495218-9edcf336-4d2f-4d1b-8054-2ce7e4ba64a7.jpeg)

**Comment by egpd1701** [comment]
Hi - I managed to get that to work with Kirikou's L/HVAR Fork and mobiflight - Took a bit of programming but i've got them working.

**Comment by nguyenquyhy** [comment]
You can use MobiFlight module to translate some internal events into SimConnect events, which can then be triggered by the plugin.
