### ISSUE TITLE
Autopilot doesn´t work correctly (after FS2020 update?)

### ISSUE THREAD

**Issue by johans1234** [nguyenquyhy/Flight-Tracker-StreamDeck#302]
After a long time not flying with my FS2020, I wanted to make a relaxed flight this evening. Unfortunately, the Autopilot does not work correctly with my stream deck profile. I can not exactly explain what problem I have, because the state is somehow unclear.

example:
ALT-Hold doesn´t work all the time and if it works, it doesn´t toggle back after activating

I thing I have updated all pieces since my last flight, so it is hard for me to figure out, which component the issues creates.

**Comment by nguyenquyhy** [comment]
I'll try to take a look tonight 😥.

**Comment by nguyenquyhy** [comment]
The ALT issue in SU5 is the main reason I don't let everyone upgrade to 0.38. It's understandable that most will still be on 0.35.

ALT mode in general is quite troublesome though as each avionics in the sim behave slightly differently when we turn on/off this mode.

**Comment by johans1234** [comment]
two things, just realized 
a) even a simple hot key within the simulator doesn`t work for "Autopilot ALT-Hold". 
b) if you didn´t use the stream deck button "ALT-HOLD" or the corresponding hot key within the simulator for some minutes, the toggle works fine (but only once until you wait again for some minutes)
c) sometimes - GEAR UP via Stream Deck doesn´t work immediately after lift off. I have to wait a minute or so, than GEAR UP works 

This very fuzzy behavior indicates to me, that there obviously is something very wrong within the FS2020. gggg

**Comment by MSFLYER5856** [comment]
Ok I'm not going crazy. The Mooney is my favorit plane and have a mobiflight panel ans SD panel set up with it. The Alt has me searching all over to see if others are having issues also.

The native altitude works using the  KAS-297. I can program part of it with moniflights news Carenado M20R events but the leave out the  KAS-297 VS part. 

MSFS has another way to operate the AP ALT/VS via its own native events. So you have 2 ways to operate the AP.

I think asbo or Carenado made a refinement to the  KAS-297 making it so usinf both systems at the same time buggy. If I stricktly use the  KAS-297 and  KAS-297 events via mobiflight and my adruino panel, all works well. But if start using the Stream Deck buttons then ALT doesnt allow toggle on/off.

I would not mind just using my panel but then I have to be in the cockpit to see the changes to ALT as it wont diplay correctly on the SD untill I hit ARM then the correct ALT shows up.  But I like flying in chase view and cant see the ALT changing unless Im in the cockpit. **So I need to find a way to display the ALT as its changing on the  KAS-297 on the Stream Deck.**

So thise are the 2 issues: ALT Hold toggle not working well or giving proper display and ALT not displaying as it changing and only displayed properly when the ARM button on the  KAS-297 is pressed.

Great addon BTW and thanks for all your hard work.
