### ISSUE TITLE
Request for new SIM Connect Variables

### ISSUE THREAD

**Issue by jplewis01** [nguyenquyhy/Flight-Tracker-StreamDeck#305]
Please add support for the Following Data Variables:

- SIMCONNECT: TURB ENG CORRECTED N1:1

I'm working on a TBM930 panel in StreamDeck and I searched through the current list of variables but could not find this Value.  
These variable is present in SPAD.Next and is listed in the SDK.

**Comment by nguyenquyhy** [comment]
I think only `TURB ENG CORRECTED N1` is missing. The other two are there.

**Comment by jplewis01** [comment]
I have corrected my request, you are correct Only `TURB ENG CORRECTED N1` values for each engine are missing.

**Comment by nguyenquyhy** [comment]
Added in v0.39
