### ISSUE TITLE
numpad on steam deck plugin only allows you to put freq to 2 decimal places. 

### ISSUE THREAD

**Issue by helpluss** [nguyenquyhy/Flight-Tracker-StreamDeck#315]
when typing in frequency using the numpad plugin you can only set frequencies to 2 decimal places.  it should be 3

for example if my air port freq is 128.005    it shows 128.00 and it fails to connect to atc.

Is this a bug or am i missing something.  
flight tracker 0.35  latest msfs update 1.21.13.0 game of year

**Comment by rmroc451** [comment]
We've had this discussion before. 
The sim houses the frequencies as bcod16, which doesn't have space for that lady digit.

The sim knows that and can display it properly, we just haven't invested any time to mimic that.

We are waiting for that to be handled via simconnect outright.

https://forums.flightsimulator.com/t/stream-deck-button-box-my-c172-implementation/229137/231?u=rmroc451

**Comment by helpluss** [comment]
thank you for the reply. 
as im new pls forgive me for asking again

**Comment by rmroc451** [comment]
> thank you for the reply. 
> as im new pls forgive me for asking again 

No worries,  welcome & enjoy

**Comment by nguyenquyhy** [comment]
This is done in v0.42 with some new support from the sim.
