### ISSUE TITLE
Multiple conditions (Feedback values)

### ISSUE THREAD

**Issue by vader75** [nguyenquyhy/Flight-Tracker-StreamDeck#32]
Hi,

Is there a possibility to add multiple conditions (Feedback values) with a Generic Toggle button?

Example:

A320 3 landing gears and 3 feedback values (on three buttons, for visuals): 

GEAR_LEFT_POSITION==100
GEAR_CENTER_POSITION==100
GEAR_RIGHT_POSITION==100

Then gear button with feedback value (the button uses GEAR_TOGGLE as Toggle Value):

GEAR_LEFT_POSITION==100 AND GEAR_CENTER_POSITION==100 AND GEAR_RIGHT_POSITION==100

This would make the gear button on (green) after all three gears are 100% extended.

This may now go into scripting, but seems multi (panel indicator) actions are present in airliners.

**Comment by nguyenquyhy** [comment]
I'll close this and will track in another issue #224.
