### ISSUE TITLE
Factor to be applied on raw value

### ISSUE THREAD

**Issue by nhoudement** [nguyenquyhy/Flight-Tracker-StreamDeck#326]
Hello,
First of all, thank you for the great job you do with this plugin !!!

I'm actually having some problems with some aircrafts in FS2020 (like Cessna 182 from carenado) where, for some reason, the raw value received from FS2020 (and displayed on the stream deck) does not match the value displayed by the gauge on the dashboard into FS2020 (ie: RPM value)

I think it would be great if the plugin gives us the opportunity to apply a factor on the raw value received from FS2020 before the value is displayed on the stream deck. That way, the value displayed on the stream deck would match the value displayed on the gauge in FS2020.

Thanks.

**Comment by nguyenquyhy** [comment]
Hi there,

If it is off by a certain factor, I would guess that you would have to use another variable, or another unit. SimConnect has built-in unit conversion, and that usually helps to solve most of those offset issues.

Can you give me more specifics on what variable and unit you used?

Thanks,
Nguyen Quy Hy

From: ***@***.***>
Sent: Tuesday, January 18, 2022 11:01 AM
To: ***@***.***>
Cc: ***@***.***>
Subject: [nguyenquyhy/Flight-Tracker-StreamDeck] Factor to be applied on raw value (Issue #326)


Hello,
First of all, thank you for the great job you do with this plugin !!!

I'm actually having some problems with some aircrafts in FS2020 (like Cessna 182 from carenado) where, for some reason, the raw value received from FS2020 (and displayed on the stream deck) does not match the value displayed by the gauge on the dashboard into FS2020 (ie: RPM value)

I think it would be great if the plugin gives us the opportunity to apply a factor on the raw value received from FS2020 before the value is displayed on the stream deck. That way, the value displayed on the stream deck would match the value displayed on the gauge in FS2020.

Thanks.

**Comment by nhoudement** [comment]
Hello,
Thank you for your reply.
The problem I'm facing is with engine RPM with C182 from Carenado.
So I don't think this is a matter of unit in this case.
So far, this is the only aircraft which causes this problem (but I didn't fly all available aircraft in FS2020 yet).

Thanks.

**Comment by nguyenquyhy** [comment]
As requested from the email, can you please provide me with the variable you used for this? And maybe also screenshot of what shows in Stream Deck vs. the sim.

**Comment by nhoudement** [comment]
Hello,
I tried to reproduce the problem this evening in order to take a screenshot but for some reason, both values not match.
May be there was an update of the sim or from Carenado in the mean time.
Anyway, now it's ok so I will close this point.

Sorry for that and once again, thank you very much for the great job you do with this amazing plugin !!
