### ISSUE TITLE
Text size/placement when using 144x144 images

### ISSUE THREAD

**Issue by nikkoa** [nguyenquyhy/Flight-Tracker-StreamDeck#33]
Is there a way to have these labels sized properly when using 144x144 images? Currently, it seems they don't scale. They're stuck on the upper half, very tiny, although they're centered properly. I'll try to include a photo next time I am able to. Whenever I use 72x72 images on the Steam Deck XL, the buttons are horribly blurry, hence I use 144px. Cheers!

**Comment by nguyenquyhy** [comment]
Is it possible to post some screenshot to demonstrate the issue?

**Comment by nikkoa** [comment]
![Capture](https://user-images.githubusercontent.com/25129574/96610562-588d2300-132e-11eb-8814-0b8ab4bb41fb.PNG)

Here it is. My icons are designed to mimic the A320 toggle button style. Instead of the headers, I put normal titles, centered, starting with one line break before the letters. The numbers are miniscule. The resolution is much better on the Stream Deck XL itself, the app's preview is blurry but exhibits the behavior in question.

**Comment by nguyenquyhy** [comment]
I see. I'll fix it soon. There will also be a checkbox for you to hide the header text.

**Comment by nguyenquyhy** [comment]
Done in version 0.12 😄.
