### ISSUE TITLE
StreamDeck does not update if master battery is not on.

### ISSUE THREAD

**Issue by LostALife** [nguyenquyhy/Flight-Tracker-StreamDeck#333]
Quite simply, In the vanilla Cessna 172, if the master alt and battery are not on and you use a generic button to switch on any of the lights, fuel pump, pitot heat, etc, the streamdeck wont recieve feedback on if its on or off. Or rather, it seems to have the requirement of the master power being on before it will show a switch as on. Similar to the way the dependencies works for the nav and com button set to "Must be on". It would be nice to have the same "dependencies" option on the generic switch as well.

**Comment by rmroc451** [comment]
Can you please share the log files in %appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin (normally named like flightstreamdeck20220201.log)

**Comment by LostALife** [comment]
I have two so here is both.
[flightstreamdeck20220202.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/7983092/flightstreamdeck20220202.log)
[flightstreamdeck20220201.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/7983093/flightstreamdeck20220201.log)

**Comment by nguyenquyhy** [comment]
I believe that was a limitation from FSX where SimConnect was tied to master battery. I just did a test and it is no longer the case, so probably Asobo has fixed this in recent update.
