### ISSUE TITLE
New Toggle Values TBM930

### ISSUE THREAD

**Issue by diaznet** [nguyenquyhy/Flight-Tracker-StreamDeck#335]
Hello,

I'm working on the TBM.
Could you please add the following in TOGGLE_VALUE ? I cannot access them.

AUTOPILOT DISENGAGED
PRESSURIZATION_PRESSURE_DIFFERENTIAL
PRESSURIZATION_CABIN_ALTITUDE
GENERAL ENG FUEL PUMP SWITCH EX1:index

TURB ENG CORRECTED N2:{index}

- Also how can I access Mobiflight Output variables ? Do they need to be wildcarded in the code as well?

**Comment by nguyenquyhy** [comment]
I'll test those TBM variables and add them in v0.43 if they are working in the sim.

Regarding MobiFlight variables, they require a different way to retrieve, which is not implemented yet in the plugin.

**Comment by nguyenquyhy** [comment]
Added `AUTOPILOT DISENGAGED`, `GENERAL ENG FUEL PUMP SWITCH EX1:{index}` and `TURB ENG CORRECTED N2:{index}` in v0.43. The rest is already in the plugin.
