### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by flyingmanu** [nguyenquyhy/Flight-Tracker-StreamDeck#344]
Below are some useful information that you can include to help with troubleshooting the issue:
- Stream Deck Plugin (5.2.1.15025) and MSFS version (1.24.5.0)
- Description of the issue & expected behavior: Flight Tracker used to work. After an update of the stream dek software, Flight tracker was not available anymore in my plug-ins list. From now on, when I try to install it, the installation proceeds but when I look at my plug-ins list, it is not available and when I go back the the stream deck store, Flight Tracker appears to not be installed.
- If the issue happens consistently, an export of your profile would help tremend
[flightstreamdeck20220118.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/8380297/flightstreamdeck20220118.log)
[flightstreamdeck20220116.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/8380298/flightstreamdeck20220116.log)
[flightstreamdeck20220115.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/8380299/flightstreamdeck20220115.log)
ously.
- Log files at `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log`
- Screenshots
![Capture1](https://user-images.githubusercontent.com/102668633/160832380-c46da64b-40c1-4b16-ac9a-142b920dfbd3.PNG)
![Capture2](https://user-images.githubusercontent.com/102668633/160832383-b393ff08-3655-4cde-a99b-0adcc55b436e.PNG)
![Capture3](https://user-images.githubusercontent.com/102668633/160832384-669d5597-aaf2-4f89-b312-5f83add00948.PNG)
![Capture4](https://user-images.githubusercontent.com/102668633/160832385-9f3b0b2d-4b6a-43c6-b5b3-7ad0f8d4ad37.PNG)

**Comment by VerreyckenGerd** [comment]
Having the same issue here.

**Comment by nguyenquyhy** [comment]
Maybe you can try to delete the folder `tech.flighttracker.streamdeck.sdPlugin` and try install again.

**Comment by VerreyckenGerd** [comment]
Hi, that worked for me thanks a lot!
