### ISSUE TITLE
FLC Preset Increase/Decrease change amount changes when airborne / no hold function.

### ISSUE THREAD

**Issue by plehton** [nguyenquyhy/Flight-Tracker-StreamDeck#346]
Stream deck buttons assigned to Vertical Speed/Air Speed changes.

FLC Preset Increase/Decrease changes by 1 when on the ground and changes to change by 10 when airborne.  Holding button does not affect to the change amount as it does in the other Presets (altitude, vs, hdg).

**Comment by nguyenquyhy** [comment]
Added in 0.43
