### ISSUE TITLE
ADF not working

### ISSUE THREAD

**Issue by ChrisPUA320** [nguyenquyhy/Flight-Tracker-StreamDeck#354]
ADF1/2 buttons are not working. They only show the active frequency and not standby. Also it is not possible to switch to the numpad to enter any freqs. COM/NAV is working fine. Any clue on this?
regards

**Comment by nguyenquyhy** [comment]
Any specific aircraft?

**Comment by ChrisPUA320** [comment]
I was trying with the Generic C172. Didn’t try any other yet to check if the issue is also there…

Regards 
Chris 

Von meinem iPhone gesendet

**Comment by ChrisPUA320** [comment]
Hi,

also tried it with other models. Same issue, when pressed nothing happens. Neither swap nor numpad functions…

Regards
Chris 

Von meinem iPhone gesendet

**Comment by ChrisPUA320** [comment]
Hi Nguyen,any updates on this issue? regardsChris Von meinem iPhone gesendetAm 11.09.2022 um 21:30 schrieb Nguyễn Quý Hy ***@***.***>:﻿
Any specific aircraft?

**Comment by ChrisPUA320** [comment]
Hi Nguyen,meanwhile I talked to other simmers who are using the flighttracker plugin and all of them told me that they have the same issue with the ADF. So it would be very kind if you could fix this.regardsChris PU // A320Von meinem iPhone gesendetAm 11.09.2022 um 21:30 schrieb Nguyễn Quý Hy ***@***.***>:﻿
Any specific aircraft?

**Comment by nguyenquyhy** [comment]
Strange. The ADF display is fine for me. Are you using any mods for avionics?
![image](https://user-images.githubusercontent.com/1560418/194725638-1ae28738-2d92-43a9-8b48-9e31ef6193ed.png)

> Also it is not possible to switch to the numpad to enter any freqs.

I think that was the intention. It seems to be broken at the moment. I'll take a look again.

> Same issue, when pressed nothing happens. Neither swap nor numpad functions…

Yah this should not happen.

**Comment by nguyenquyhy** [comment]
Turn out pressing and holding ADF buttons weren't implemented at all. I'll see if I can add that in this weekend.

**Comment by ChrisPUA320** [comment]
Hi,thanks for answer. Yeah the indication/read of the values is fine. But just when you want to swap or go to numpad nothing happens…No mods for avionics used…cheersChrisVon meinem iPhone gesendetAm 08.10.2022 um 21:55 schrieb Nguyễn Quý Hy ***@***.***>:﻿
Strange. The ADF display is fine for me. Are you using any mods for avionics?


Also it is not possible to switch to the numpad to enter any freqs.

I think that was the intention. It seems to be broken at the moment. I'll take a look again.

Same issue, when pressed nothing happens. Neither swap nor numpad functions…

Yah this should not happen.

**Comment by nguyenquyhy** [comment]
This is released in v0.45.

**Comment by ChrisPUA320** [comment]
Hi Nguyen,thanks for the effort in making the ADF working. But unfortunately I faced another issue with the ADF:ADF 2 only swaps the frequency of ADF 1. ADF 2 is not swapable. Also entering frequencies for ADF (1+2) via the numpad is not working correctly. I deinstalled and reinstalled the plugin but the issue persists.Could you please check on that because ADF is not usable so far.Thank you and best regards ChrisAm 10.10.2022 um 02:36 schrieb Nguyễn Quý Hy ***@***.***>:﻿
This is released in v0.45.
