### ISSUE TITLE
Numpad: Nothing works

### ISSUE THREAD

**Issue by EisernUnion** [nguyenquyhy/Flight-Tracker-StreamDeck#358]
When pressing any Number or other Key ... nothing happens ; the COM1, COM2, NAV1, NAV2 Buttons to swap are working. Just installed from the SD Plugin Store

**Comment by nguyenquyhy** [comment]
Please check if you have a profile named Numpad. When you install the plugin, Stream Deck should ask you to automatically install this profile.

**Comment by nguyenquyhy** [comment]
Please feel free to reopen if there is any additional information.
