### ISSUE TITLE
Are any of the G1000 Garmin event triggers implemented?

### ISSUE THREAD

**Issue by Virtual-Chris** [nguyenquyhy/Flight-Tracker-StreamDeck#36]
There is an impressive list of G1000 events in the docs... are any of them implemented?

 G1000_PFD_FLIGHTPLAN_BUTTON,
        G1000_PFD_PROCEDURE_BUTTON,
        G1000_PFD_ZOOMIN_BUTTON,
        G1000_PFD_ZOOMOUT_BUTTON,
        G1000_PFD_DIRECTTO_BUTTON,
        G1000_PFD_MENU_BUTTON,
        G1000_PFD_CLEAR_BUTTON,
        G1000_PFD_ENTER_BUTTON,
        G1000_PFD_CURSOR_BUTTON,
        G1000_PFD_GROUP_KNOB_INC,
        G1000_PFD_GROUP_KNOB_DEC,
        G1000_PFD_PAGE_KNOB_INC,
        G1000_PFD_PAGE_KNOB_DEC,
        G1000_PFD_SOFTKEY1,
        G1000_PFD_SOFTKEY2,
        G1000_PFD_SOFTKEY3,
        G1000_PFD_SOFTKEY4,
        G1000_PFD_SOFTKEY5,
        G1000_PFD_SOFTKEY6,
        G1000_PFD_SOFTKEY7,
        G1000_PFD_SOFTKEY8,
        G1000_PFD_SOFTKEY9,
        G1000_PFD_SOFTKEY10,
        G1000_PFD_SOFTKEY11,
        G1000_PFD_SOFTKEY12,
        G1000_MFD_FLIGHTPLAN_BUTTON,
        G1000_MFD_PROCEDURE_BUTTON,
        G1000_MFD_ZOOMIN_BUTTON,
        G1000_MFD_ZOOMOUT_BUTTON,
        G1000_MFD_DIRECTTO_BUTTON,
        G1000_MFD_MENU_BUTTON,
        G1000_MFD_CLEAR_BUTTON,
        G1000_MFD_ENTER_BUTTON,
        G1000_MFD_CURSOR_BUTTON,
        G1000_MFD_GROUP_KNOB_INC,
        G1000_MFD_GROUP_KNOB_DEC,
        G1000_MFD_PAGE_KNOB_INC,
        G1000_MFD_PAGE_KNOB_DEC,
        G1000_MFD_SOFTKEY1,
        G1000_MFD_SOFTKEY2,
        G1000_MFD_SOFTKEY3,
        G1000_MFD_SOFTKEY4,
        G1000_MFD_SOFTKEY5,
        G1000_MFD_SOFTKEY6,
        G1000_MFD_SOFTKEY7,
        G1000_MFD_SOFTKEY8,
        G1000_MFD_SOFTKEY9,
        G1000_MFD_SOFTKEY10,
        G1000_MFD_SOFTKEY11,
        G1000_MFD_SOFTKEY12,

**Comment by nguyenquyhy** [comment]
Those are already in our Struct file but I heard that SimConnect doesn't do anything with those events at the moment.

**Comment by rug4ever** [comment]
hello, 

Its the g1000 or g3000 now working?

**Comment by nguyenquyhy** [comment]
You can test them out. But I don't suppose they will suddenly work without any MSFS update 😄.

**Comment by Virtual-Chris** [comment]
Any new stuff working with the new MSFS update today?

**Comment by Crunchmeister1** [comment]
I look forward to this being added to SimConnect. I have a panel already built, just waiting for the functionality to be added.

**Comment by nguyenquyhy** [comment]
You can try version 0.22, which added support for MobiFlight WASM module to interact with the G1000. 
Please checkout the new User Guide section because there are some additional steps to make this work https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/master/docs/USERGUIDE.md#mobiflight-wasm-module-integration

**Comment by rug4ever** [comment]
yes now its working with the mobiflight addon

Many thx great Job

I take every flight the streamdeck

Thx and you can close this issue
