### ISSUE TITLE
Plug in Flight Tracker impossible to install on Stream Deck XL

### ISSUE THREAD

**Issue by magoa001** [nguyenquyhy/Flight-Tracker-StreamDeck#368]
Hello.
Impossible to install, either via the stream deck store (it downloads but does not install) or manually (nothing appears in the SD interface.
Someone has an idea.
Thanks in advance.

- Version: Stream Deck 5.3.3.15214 / Flight Tracker Plugin 0.46 / MSFS 1.29.30.0
- Description: I can't install flight tracker on my SD-XL / 
- Steps to reproduce the issue :
> Via the stream deck store: Flight Tracker plug in installation
> Double click the file tech.flighttracker.streamdeck.streamDeckPlugin to install 

- If the issue happens consistently, an export of your profile would help tremendously.
- Log files at `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log`: No file => No log !
- Screenshots:

01.png "before install SD-Store
<img width="1917" alt="01" src="https://user-images.githubusercontent.com/36919318/205986492-00f6a87a-6266-4085-9de3-3f9e1985f810.png">

02.png "after install SD-Store"
<img width="1918" alt="02" src="https://user-images.githubusercontent.com/36919318/205986449-cfbae0ce-1a76-46a9-b300-71d56ec5e144.png">

03.png "C:\MES PROGRAMMES\Elgato\StreamDeck\Plugins"
<img width="960" alt="03" src="https://user-images.githubusercontent.com/36919318/205986440-ed084b51-b06f-4b08-b637-f0c124e852ed.png">

04.png hidden icon taskbar
<img width="120" alt="04" src="https://user-images.githubusercontent.com/36919318/205986446-f2eba4d7-fd24-467d-ba8b-0ef5f4a500c4.png">

**Comment by nguyenquyhy** [comment]
Do you see this folder `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin`?

**Comment by magoa001** [comment]
> Do you see this folder `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin`? 

Thank you for the answer.
No, it is not created when I go through the SD store.  I tried different manual method:
1/ Create only the "tech.flighttracker.streamdeck.sdPlugin" folder and go through the store, it does not work.
2/ Drop the complete tech.flighttracker.streamdeck.sdPlugin file with the contents of the zip.

Same punishment.

**Comment by nguyenquyhy** [comment]
Can you please show me the screenshot of that location? `%appdata%\Elgato\StreamDeck\Plugins`

The previous screenshots show the incorrect place.

**Comment by magoa001** [comment]
> Can you please show me the screenshot of that location? `%appdata%\Elgato\StreamDeck\Plugins`
> 
> The previous screenshots show the incorrect place.

Sorry.
The good screen
<img width="960" alt="explorer_pz3M0j4ejx" src="https://user-images.githubusercontent.com/36919318/206246875-2304b7e7-8ece-421e-8363-fe2c7b0dc133.png">

**Comment by magoa001** [comment]
Thank you very much Nguyenquyhy.
I solved my problem now that I found the right directory. I deleted and it installs correctly with the store.
<img width="960" alt="StreamDeck_aiLEzTiUIz" src="https://user-images.githubusercontent.com/36919318/206249225-215546c9-d34b-47fe-8a30-dc0c9a482e2e.png">

**Comment by nguyenquyhy** [comment]
Awesome :)
