### ISSUE TITLE
Support pmgd sdk

### ISSUE THREAD

**Issue by maor561** [nguyenquyhy/Flight-Tracker-StreamDeck#38]
First thank you very much!!!!!
Can you support PMDG sdk?

**Comment by nguyenquyhy** [comment]
Right now I focus mainly on SimConnect and MSFS, so probably I'll leave that until we have the new 737. 😄

**Comment by nguyenquyhy** [comment]
Close this for now since the 737 won't come any time soon.

**Comment by jpbberry** [comment]
Not sure if this project is still active but this product is an amazing free tool. Would love to see PMDG support added.
