### ISSUE TITLE
Rotary knobs of the StreamDeckPlus

### ISSUE THREAD

**Issue by Zofren** [nguyenquyhy/Flight-Tracker-StreamDeck#382]
**Is your feature request related to a problem? Please describe.**
The SD+ brings a lot of possibilities with these four rotary knobs and the swipe thing to switch pages.

**Describe the solution you'd like**
Knobs to be managed by Flight Tracker StreamDeck

**Describe alternatives you've considered**
Well, competitors like AAO, FlightDeck ... But I like this plugin to be SimConnect based, I begin to be fed up by all these background tools we need to have a proper sim experience.

**Additional context**

**Comment by nguyenquyhy** [comment]
Anything specific you want? There is already some support for streamdeck+

**Comment by Zofren** [comment]
Oh, perhaps is it something I didn't get. How to use the knobs control with Flight Tracker ? I don't see any element in the Buttons tab of StreamDeck with the FlightTracker plugin.

**Comment by nguyenquyhy** [comment]
Are you sure you are using the latest version 0.48?

**Comment by Zofren** [comment]
0.45 indeed, it's the version from the StreamDeck plugin store.

**Comment by nguyenquyhy** [comment]
Please update to 0.48 and let me know what is still missing for you.

**Comment by nguyenquyhy** [comment]
Please feel free to open another issue if you have any idea for the SD+.
