### ISSUE TITLE
Rotary Knobs only working partially

### ISSUE THREAD

**Issue by Xantrass** [nguyenquyhy/Flight-Tracker-StreamDeck#384]
Streamdeck Plugin Version: 0.48
MSFS Version: 1.30.11.0 (AAU1 Beta)
Stream Deck+

VOR1 & VOR2 Preset Dial Buttons:
The visible value on the stream deck button correctly updates when I change the heading in the sim but rotary input on the Streamdeck + is not working.

COM and NAV inputs.
When I press long on the nav or com buttons the streamdeck switches correctly to the "numpad", but there only the outer rotary is working. The "inner" rotary blinks red.
Interestingly, the visible "inner" value changed at some point while the plugin was not connected to the simulator. 

[profile.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/10424023/profile.zip)

**Comment by nguyenquyhy** [comment]
Would you please sending me a screenshot of the Stream Deck buttons after you get to the "numpad"?

**Comment by nguyenquyhy** [comment]
Btw, very cool background for the strip 😄.

**Comment by Xantrass** [comment]
![Before long press on NAV1](https://user-images.githubusercontent.com/43748235/225229035-d445913a-3c30-4ef1-995b-cd4139f23b73.png)
![After long press on NAV1](https://user-images.githubusercontent.com/43748235/225229045-0afa52eb-e12b-4611-aa5c-526bcae9499f.png)

Bonus - Behavior shown in a video: https://nextcloud03.webo.hosting/s/qkCkwenrcS45HNT

**Comment by nguyenquyhy** [comment]
Okay I see the issue now. It will be fixed in the next version ;).

**Comment by nguyenquyhy** [comment]
This should be fixed in v0.49.
