### ISSUE TITLE
Parking Brake Longitude SD

### ISSUE THREAD

**Issue by avusracer** [nguyenquyhy/Flight-Tracker-StreamDeck#388]
Hello, since the AAUT update, I have had the problem that the parking brake in the longitude with the "PARKING_BRAKES" event on the SD no longer works!
In other planes it works!
On a button on the joystick it works and the colors of the buttom in the SD change too!
Another event "Parking Brake Set" only works in one direction (does not toggle)
Where could the mistake lie?

**Comment by nguyenquyhy** [comment]
`PARKING_BRAKES` is the correct event to toggle the parking brakes. I think they introduce this bugs while upgrading the Longitude's systems.

I still see the same issue on Sim Update 12 beta. I guess you should create a bug report in ZenDesk for MSFS.
