### ISSUE TITLE
Toggle

### ISSUE THREAD

**Issue by MAGISman** [nguyenquyhy/Flight-Tracker-StreamDeck#390]
I am trying to use some of the generic toggle button's, and it do not work most of the time. dont know if this is a bug or somthin i am doin wrong.

**Comment by nguyenquyhy** [comment]
Please share more details on how you configure the button. E.g. what value you input into each fields.

**Comment by MAGISman** [comment]
For example Master and engine button did not work when i tried last time, I set them up as seen in the
![Bilde_2023-03-17_155827490](https://user-images.githubusercontent.com/126558491/225941414-adce2a0c-344e-40a9-b6ff-436367046ccc.png)
![Skjermbilde 2023-03-17 155849](https://user-images.githubusercontent.com/126558491/225941609-993eb607-c5c0-44e6-a32f-be9639d85272.png)
 picture under
