### ISSUE TITLE
Horizon and Wind buttons no longer works in version 0.49

### ISSUE THREAD

**Issue by PeterDaniel3D** [nguyenquyhy/Flight-Tracker-StreamDeck#393]
There's no output for the either the Horizon or Wind button in version 0.49 with SU12 leaving the buttons values on zero.

**Comment by nguyenquyhy** [comment]
You are right. I missed this. I'll release v0.50 shortly to fix it.

**Comment by nguyenquyhy** [comment]
The fix is now released in v0.50.
