### ISSUE TITLE
Is there an event to set a value to an arbitrary variable?

### ISSUE THREAD

**Issue by 0tofu** [nguyenquyhy/Flight-Tracker-StreamDeck#395]
Thank you for providing this amazing tool.
The local variable (L:SwitchLandingTaxi) is being used to track the state of the LandingTaxiSwitch in the M-346 aircraft provided by IndiaFoxtEcho. Within the flight simulator, there is no existing event to modify this variable as it is currently assigned to a mouse click event.

I would like to overwrite the value of this variable using StreamDeck. Is it possible to configure such a setting?

**Comment by ijl20** [comment]
**+1 for this**. The entire UI of some HTML gauges can be controlled simply by setting L: vars to 1 (the gauge html/js picks that up, and resets the var to 0). There's no way any plugin can keep up with pre-defining 'event' setups for every possible gauge in every plane in MSFS.

**Comment by nguyenquyhy** [comment]
You can create a new event to set an LVar using MobiFlight. I have written a more detailed guide here. https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/main/docs/MOBIFLIGHT.md. Please feel free to let me know how it can be improved.
