### ISSUE TITLE
MOBIFLIGHT_ EVENTS ALL OK BUT NOR LVARS

### ISSUE THREAD

**Issue by fabianovm** [nguyenquyhy/Flight-Tracker-StreamDeck#396]
Hello nguyenquyhy thanks a lot, great app! I had success using it sending MOBIFLIGHT_ events to sim with success!! Wonderful! Question: is there a way to SET, MODIFY A CURRENT LVAR, instead of a mobiflight event? If so, can you tell me the sintax or any sample? thanks A LOT!
ex: MOBIFLIGHT_(>L:ASCRJ_OVHD_LDG_LEFT)  or some sintax like this? I want to write  to a LVAR, is there anyway?

**Comment by nguyenquyhy** [comment]
There is no such support right now.

Recently MS has added the ability to read LVARs to SimConnect, and I have added such support to the plugin. However, I have not tried to look into writing via the same interface yet.

I'll look into this in the next version.

**Comment by fabianovm** [comment]
> There is no such support right now.
> 
> Recently MS has added the ability to read LVARs to SimConnect, and I have added such support to the plugin. However, I have not tried to look into writing via the same interface yet.
> 
> I'll look into this in the next version.

Thanks a lot nguyenquyhy, I hope you can implement this, the last frontier to have full control of the sim with your plugin. 

I fly several aircrafts, mostly the Honda Jet and most of it´s control is about setting LVARS to 0 or 1. Even with the simplest command. There a lot of aircrafts that is the same. If I could SET a LVAR (and maybe other sim VARS) the jump this app would achieve is huge!

In time, there´s other app ins flightsim.to called Pilot's Deck  that says it can manage LVARS and more. But I prefer A LOT your app, but it misses something really important that is becoming more and more common. LVARS mostly, and other simVARS to command the aircraft. Hope you can understand the importance and implement it and get at least some coffee or beer my friend. thanks a lot for listening to me, I want the same, the most powerfull and easy to use app to COMPLETELY talk do msfs. Your app is almost there, really! Hope for some good news from you, and one more time, congrats, huge idea and app. Best regards, Fabiano

**Comment by jwvanderbeck** [comment]
In addition to just setting the LVAR though we also need the ability for a Toggle button to set different values depending on state. IOW send 1 to turn it on on the first press, send 0 to turn it off on the second press.  So even if we could write to LVARS I don't see how the setup of the current button would work?

**Comment by fabianovm** [comment]
> There is no such support right now.
> 
> Recently MS has added the ability to read LVARs to SimConnect, and I have added such support to the plugin. However, I have not tried to look into writing via the same interface yet.
> 
> I'll look into this in the next version.

Hi nguyenquyhy , how are you? I saw you launched 0.51 and saw your last reply  "added this to the [0.51]"... Is is possible now to SET LVARS or other VARS using mobiflight? IF yes, can you tell me the sintax? Best regards!

**Comment by nguyenquyhy** [comment]
Setting LVar is now possible using MobiFlight. You can read more in the new guide here https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/main/docs/MOBIFLIGHT.md.
