### ISSUE TITLE
Master Warning/Master Caution

### ISSUE THREAD

**Issue by g33z3r-hd** [nguyenquyhy/Flight-Tracker-StreamDeck#40]
I can't see a way to do it with the current variables but thought I might be missing something.

I would love a Master Warning/Master Caution button 

Thanks for everything you have done!  Loving the plugin!

**Comment by sn3akz** [comment]
Unfortunately, both buttons are not (yet) available through the interface.

**Comment by nguyenquyhy** [comment]
New variables are added in 0.42.
