### ISSUE TITLE
Crash Flight-Tracker-Plugin and Prepar3D Version 6

### ISSUE THREAD

**Issue by fsbloch** [nguyenquyhy/Flight-Tracker-StreamDeck#400]
### Discussed in https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/discussions/399

<div type='discussions-op-text'>

<sup>Originally posted by **fsbloch** July 22, 2023</sup>
If I use the Flight-Tracker-Plugin with my Elgato Stream Deck an Prepar3D Version 6 I get an crash to desktop. If the Flight-Trakcer-Plugin ist disabled, I get no crash. What could be the cause and how can the fault be rectified?

![2023-07-15 11_41_16-Ereigniseigenschaften - Ereignis 1000,  NET Runtime](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/assets/38840762/b36451ed-9fea-4301-a7a9-daa4667cd0d4)
</div>

**Comment by nguyenquyhy** [comment]
I think this is fixed. Please feel free to reopen otherwise.
