### ISSUE TITLE
SD+, Rotary altitude dial stuck #389 Revisited?

### ISSUE THREAD

**Issue by dvhowell1106** [nguyenquyhy/Flight-Tracker-StreamDeck#409]
Plugin version - 0.51
MSFS Version - 1.43.16.0

Preset dial button with "Altitude" function selected keeps going back to initial value when knob is turned.  If I'm on ground @ 890' and turn knob clockwise to increase selected altitude StreamDeck+ registers the change but immediately goes back to 0'.  Expecting value NOT to revert back to it's initial value but stay with value knob turned to.

Drag Preset Dial Buttons from Dials pane to a dial.  Select "Altitude" for Function.  Turn know and see what happens
Attachments as requested included.
Thanks.

[MSFS-streamDeckProfile.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/12818842/MSFS-streamDeckProfile.zip)
[StreamDeck0.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/12818849/StreamDeck0.log)
[tech.flighttracker.streamdeck0.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/12818850/tech.flighttracker.streamdeck0.log)

**Comment by nguyenquyhy** [comment]
Can you please also let me know which aircraft you are testing on?

**Comment by dvhowell1106** [comment]
Hello sir.  Sorry for delay.  I was using the Honda Jet HA-420.  Upon your reply I decided to try the Asobo C172 G1000 and it works there.  So I guess the onus is on the HA-420 developer.  Disappointing for me.  I really like the Honda Jet and was looking for a cost effective and easy to use SD+ plug in.

**Comment by nguyenquyhy** [comment]
The plugin uses standard SimConnect event to set AP Altitude. I guess the Honda Jet just ignore that event, so the altitude will keep reverting to the old value.
