### ISSUE TITLE
FLAPS_DECR moves flaps up completely

### ISSUE THREAD

**Issue by ajlakanen** [nguyenquyhy/Flight-Tracker-StreamDeck#415]
- Stream Deck Plugin V 0.48 MSFS version (newest as per Dec 2023)

I used generic toggle button to decrease flaps.  

FLAPS_DECR event should decrease flaps by one step but instead moves flaps up completely. 

I'm a newbie with 10hrs of flight time so sorry if I missed something.

**Comment by nguyenquyhy** [comment]
0.48 is a bit old though. 0.52 is actually the latest one.

Can you please provide a bit more info on which aircraft you have tested this on and please share an export of your Stream Deck profile?

**Comment by ajlakanen** [comment]
Regarding the plugin version, I installed it from the Elgato Marketplace. I wonder if it's ok to just install another version from somewhere else?

Happy holidays :)

**Comment by nguyenquyhy** [comment]
I updated the Marketplace version to 0.52. Do you still have the same issue?

**Comment by nguyenquyhy** [comment]
![image](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/assets/1560418/4e72fe2d-0a39-42cf-adb4-f282cc296ca2)
I have just tried this with the C172 and cannot reproduce the issue.

Please let me know if you still get this issue after upgrading the plugin to 0.52.
