### ISSUE TITLE
Plugin version in Elgato Marketplace is out of date.

### ISSUE THREAD

**Issue by alexstojda** [nguyenquyhy/Flight-Tracker-StreamDeck#417]
In the [plugin store](https://marketplace.elgato.com/product/flight-tracker-1c4afa3d-157a-4d2f-91bc-eb71865dad1c), the version available is only 0.48, whereas the latest version available according to the tags on the repo is 0.52.

Could you please update the version in the marketplace? It makes it easier to keep up to date with the new releases if they are deployed in the marketplace, rather than having to manually update for each new release :) 

Thanks!

**Comment by nguyenquyhy** [comment]
Wow I forgot to submit an update for a year already 😅. I'll do it this week. Generally I tried to delay submitting to Elgato store a little bit to make sure the version is stable and doesn't cause game breaking bugs, but I guess I was so distracted last year.

**Comment by alexstojda** [comment]
@nguyenquyhy no worries, I figured it was just an oversight :D

**Comment by alexstojda** [comment]
BTW, if you'd like, I'd be happy to setup some CD pipelines in GitHub actions to publish versions to the store automatically :) 

You could publish `pre-release` versions for people to download and test manually, then publish "full" releases which would get published to the marketplace automatically

**Comment by nguyenquyhy** [comment]
Is it even possible to publish to Elgato marketplace via API? I have been emailing Elgato everytime, so I wasn't aware that CD is even a possibility.

**Comment by alexstojda** [comment]
Ah yeah you are right, they still haven't implemented that yet :(

**Comment by nguyenquyhy** [comment]
Version 0.52 is now in the marketplace.
