### ISSUE TITLE
Question: Last Digit in COM/NAV

### ISSUE THREAD

**Issue by freps** [nguyenquyhy/Flight-Tracker-StreamDeck#42]
Hi all,
is it just me or how can I enter the last digit on the COM/NAV screen? 
I.e. I want to enter 120.175 as frequency but I cannot enter the "5", so MSFS is not accepting it as the right frequency.

**Comment by rmroc451** [comment]
It looks like it puts it in to the sim correctly, but rounds up on the UI.  other than the streamdeck not showing it fully, its right in the sim.

We'll take a look at the rounding error.

![image](https://user-images.githubusercontent.com/15070945/97650984-fd8fb600-1a28-11eb-8fb2-d72f68febe84.png)

**Comment by rmroc451** [comment]
the simconnect api doesn't like me trying to set it with the full 3 digit decimal places, so I'll leave that entry screen allowing 2.

you don't have to enter it, it knows that decimal 17 is 175.  I updated the UI to show it though.

This will be fixed once the changes are merged and put into a release

![image](https://user-images.githubusercontent.com/15070945/97653866-c7096980-1a2f-11eb-883f-f26ea23cc416.png)

**Comment by nguyenquyhy** [comment]
Released in v0.15
