### ISSUE TITLE
Icon doesnt change no matter what is ntered for the toggle variable (action in sim still fires)

### ISSUE THREAD

**Issue by jman1118** [nguyenquyhy/Flight-Tracker-StreamDeck#420]
Below are some useful information that you can include to help with troubleshooting the issue:
- Stream Deck Plugin and MSFS version - 
   0.52 (plugin version) and 6.5.0 (stream deck) and 1.36.2.0 (MSFS)
- Description of the issue & expected behavior
  Icon doesnt change but the event will still fire (for example, setting parking brake, battery switch, etc). It seems to default to 0 or NULL as indicated by favoring the OFF position.
- Steps to reproduce the issue
  1) Launch MSFS
  2) Launch this Plugin
  3) Press configured toggle button

- Screenshots
![image](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/assets/12668191/
[flightstreamdeck20240214.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/14291119/flightstreamdeck20240214.zip)
aa786a43-2604-4f1c-868e-b853249e2e41)

**Comment by nguyenquyhy** [comment]
I think the file didn't get attached. Can you please drag & drop the log file again?

**Comment by jman1118** [comment]
Here is an updated log file. Issue still occuring even after those changes we discussed in Discord.

**Comment by jman1118** [comment]
[flightstreamdeck20240215.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/14305292/flightstreamdeck20240215.log)

**Comment by jman1118** [comment]
Reinstalling the plugin fixed the issue.
