### ISSUE TITLE
Confused about Mobiflight Events

### ISSUE THREAD

**Issue by bmhatfield** [nguyenquyhy/Flight-Tracker-StreamDeck#428]
Given a preset like https://hubhop.mobiflight.com/preset/?simType=msfs2020&id=f98c4165-2e12-42a7-b491-176fb6749761

I expected to be able to send an event like `MOBIFLIGHT_Longitude_AP_SPD_Mode_MAN` however when I do this nothing happens. I reviewed the example profile and it seems to strongly suggest this should be the syntax, yet it does not work.

I am able to map this preset to a button on my joystick in MobiFlight and it functions okay. I'm also able to read `L:XMLVAR_SpeedIsManuallySet` fine in Flight Tracker / display it on a button.

**Comment by nguyenquyhy** [comment]
I have written a more detailed guide here. https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/main/docs/MOBIFLIGHT.md. Please feel free to let me know how it can be improved.
