### ISSUE TITLE
Tutorial on how  to use Flight Tracker with Mobiflight

### ISSUE THREAD

**Issue by JaimeLeon2** [nguyenquyhy/Flight-Tracker-StreamDeck#429]
**Is your feature request related to a problem? Please describe.**
Mobiflight has a database of over 21,000 MSFS2020 events.  Flight Tracker can use this database, but does not provide details on how to use it.  The documentation is very vague.

**Describe the solution you'd like**
A better tutorial on how to do this specific topic, with examples would help everyone.

**Describe alternatives you've considered**
There is no documentation on how to do this.

**Additional context**

**Comment by nguyenquyhy** [comment]
I have written a more detailed guide here. https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/main/docs/MOBIFLIGHT.md. Please feel free to let me know how it can be improved.
