### ISSUE TITLE
Is it possible to add Speed as an option for Preset Toggle Buttons and Increase/Decrease? 

### ISSUE THREAD

**Issue by Virtual-Chris** [nguyenquyhy/Flight-Tracker-StreamDeck#43]
Hi, I'm starting to implement a profile for the A320.

The A320 has an AP mode for speed.  I think (but not sure) that it may be activated by AP_PANEL_SPEED_HOLD_TOGGLE and it is likely adjusted by AP_SPD_VAR_INC and AP_SPD_VAR_DEC.

Is it possible to add these options to the Preset Toggle Button and the Increase/Decrease

**Comment by Virtual-Chris** [comment]
Note I have confirmed that these events are tied to the AP Speed mode...
AP_AIRSPEED_HOLD
AUTOPILOT AIRSPEED HOLD (state)
AUTOPILOT AIRSPEED HOLD VAR (display value)
AP_SPD_VAR_INC (+)
AP_SPD_VAR_DEC (-)

**Comment by nguyenquyhy** [comment]
Do you know which a/c actually use Speed mode? I tried 747 but it doesn't seem to be the normal Speed mode (i.e. AUTOPILOT AIRSPEED HOLD is not working).

**Comment by Virtual-Chris** [comment]
I don't know all the a/c that use speed mode, but definitely the A320 does.

Here's what works for me in the A320 using a regular toggle button...

<img width="327" alt="Screen Shot 2020-11-05 at 6 35 29 PM" src="https://user-images.githubusercontent.com/72712231/98319490-b9a33080-1f95-11eb-9e6b-dab4a51cfe23.png">

**Comment by nguyenquyhy** [comment]
I am not that familiar with A320, so I might understand this wrongly, but my observation is that the aircraft is always be in speed mode when it is not climbing or descending and in other appropriate climb/descend mode otherwise.

Can you elaborate a bit on when the activate/deactivate speed mode (toggle AP_AIRSPEED_HOLD) is applicable for A320 so I can do some tests?

Also, there is already Speed mode (Air Speed) in Increase/Decrease button.

**Comment by Virtual-Chris** [comment]
Unlike most aircraft, the Airbus has the added feature on its autopilot to control the thrust/throttles automatically to control speed. This speed control, I’m discussing here is the auto pilot throttle control. Once above 1500AGL, you move the throttle levers to Climb, and engage the A/THR (auto thrust) then the AP controls the spreed of the aircraft. You can either adjust the speed by turning a dial and pulling, or pushing the dial in for managed mode (similar to NAV mode) where the aircraft controls the speed. The values above are tested and working fine, they just need to be integrated into the preset toggle button. 

Also the increase/decrease you have already implemented is for speed is for vertical speed (VS). Not this speed. You should add a separate increase/decrease for the Airbus cruise speed as well. 

I really need you to look at implementing the request I have for sending a parameter as noted in my other issue. The Airbus has two modes for each AP control, that are set by sending a “1” or “2” parameter with the event value. Please enable me to do something like this so I can properly control the Airbus AP and not have to click knobs with a mouse.

**Comment by nguyenquyhy** [comment]
> Unlike most aircraft, the Airbus has the added feature on its autopilot to control the thrust/throttles automatically to control speed. This speed control, I’m discussing here is the auto pilot throttle control. Once above 1500AGL, you move the throttle levers to Climb, and engage the A/THR (auto thrust) then the AP controls the spreed of the aircraft. You can either adjust the speed by turning a dial and pulling, or pushing the dial in for managed mode (similar to NAV mode) where the aircraft controls the speed. The values above are tested and working fine, they just need to be integrated into the preset toggle button.

Yah I understand the autothrust and speed mode, but I don't get anything from "AP_AIRSPEED_HOLD" toggle; basically I cannot turn it off, it is either speed mode or switch to another mode.

Say you are now in speed mode and autothrust activated. If you press the button with AP_AIRSPEED_HOLD, what would happen in your A320?

> Also the increase/decrease you have already implemented is for speed is for vertical speed (VS). Not this speed. You should add a separate increase/decrease for the Airbus cruise speed as well.

Can you double check? I added Air Speed in the increase/decrease button a while ago.

> I really need you to look at implementing the request I have for sending a parameter as noted in my other issue. The Airbus has two modes for each AP control, that are set by sending a “1” or “2” parameter with the event value. Please enable me to do something like this so I can properly control the Airbus AP and not have to click knobs with a mouse.

Yes I am working on this 😄. Just need to understand a bit more about what happen with AP_AIRSPEED_HOLD toggle as in my first question.

**Comment by vicentezc** [comment]
In MSFS, for the A320, the autopilot uses the following:

- Speed: 'Speed Slot Index Set' with parameters 1 (selected) and 2 (managed)
- Altitude: 'Altitude Slot Index Set' with parameters 1 (selected) and 2 (managed)
- Heading: 'Heading Slot Index Set' with parameters 1 (selected) and 2 (managed)

For the moment, I am using Key assignments with FSUIPC 7 and defining those key assignments in a standard Hotkey Switch.
But I saw another request to have 'Parameter' as a config for the buttons, so maybe that would be the way to do it?

Cheers!
Vicente

**Comment by Virtual-Chris** [comment]
Hi, sorry I was away for awhile... I’m not sure what has changed but AP_AIRSPEED_HOLD no longer works for me. Maybe it never has and I was confused. 

At any rate, I’m now using the mouse to push or pull the AP knobs in the A320 until you get a solution to use the various slot index events with a parameter. Please work on that. :)

**Comment by Virtual-Chris** [comment]
I can confirm that your airspeed increase decrease buttons work with the A320. You can close this issue.
