### ISSUE TITLE
VOR1 and VOR2 are not working in SD+ dial

### ISSUE THREAD

**Issue by nguyenquyhy** [nguyenquyhy/Flight-Tracker-StreamDeck#432]
Hi,
I am a new user of the Streamdeck + and started to figure out the capabilities of the Flight Tracker Plugin. I am of cource most interested in the new stuff I can do with the rotary buttons. HEADING, ALTITUDE, VERTICAL SPEED are working very well but the VOR1 and VOR2 functions are not working for me. Not in FS 2020 nor in FS 2024. Is there something to consider to use this functions?

regards Sascha

PS: again, many thanks for the great job !!!!!!!!!!!!!!!!!!!!!!!!!!!!

_Originally posted by @johans1234 in https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/discussions/365#discussioncomment-11541937_

**Comment by nguyenquyhy** [comment]
Fixed in 0.53

**Comment by johans1234** [comment]
Wow, this was very quick. The VOR dials are working properly - great.

But now (or even before 0.53?) the VS dial does only allow positiv values. It is not possible to dial in a negative climb rate (= sink rate)  

Or do I have another problem which is not related to the plugin???

**Comment by nguyenquyhy** [comment]
You are right. I totally forgot that VS can be negative and force it to be positive number. Fix is coming :).
