### ISSUE TITLE
Multiple event triggers on one button

### ISSUE THREAD

**Issue by Photosbykev** [nguyenquyhy/Flight-Tracker-StreamDeck#45]
Is it possible to programme a button to trigger two events with one button press?

On the X-cub the the Pulse/Stby switch triggers LANDING_LIGHTS_TOGGLE and TOGGLE_RECOGNITION_LIGHTS events

regards
Kev

**Comment by GeekTrainer** [comment]
You should be able to do that by creating a **Multi action** or **Multi switch action** (the second is most likely what you're looking for) in Streamdeck, and then add the appropriate items to that

**Comment by vicentezc** [comment]
Hello,
I would like to do the same for NAV LIGHTS and LOGO LIGHTS (single switch in A320). I tried the suggestion of using multi action or multi switch action, but when I try to configure it the Flight Tracker actions don't show. And I am not sure how this would work as for the multi switch action it seems like you have to define the "ON" command and the "OFF" command.
Thanks!
Vicente

**Comment by nguyenquyhy** [comment]
You can now add toggle and increase/decrease buttons to Multi Action in version 0.17.

**Comment by 27trt** [comment]
Hi ther,
First of all many thanks for your effort and the superb program to use stream deck with MSFS!
I'm still in the progress of trying out, but in case of the Landing Light switch on the NXCub I am not making any progress. 
No matter what event ID I assign, the maximum I achieve is a short flash of the landing light, the switch does not move at all. Neither the LAND nor the PULSE switch move with either landing or recognition event. What am I doing wrong?
Thanks
Arno
