### ISSUE TITLE
need cdi change in garmin 1000 From nav1 nav2 GPS adf course i need the keybind or the variable in Simconnect

### ISSUE THREAD

**Issue by rug4ever** [nguyenquyhy/Flight-Tracker-StreamDeck#47]
i want to play VfR flight via vor vor or dme or nmd points 
I cant change via key or Simconnect the change in g1000 cdi Switch From GPS nav1 nav 2 or adf 

Have any where the keybind for that? 

Many thx for help

**Comment by nguyenquyhy** [comment]
I believe someone mentioned a key bind for that before. I think you should be able to find it in in-game Control settings.
I also want to add that into the plugin, but I can't find the SimConnect event for that yet.

**Comment by rug4ever** [comment]
thx for the answer

but Control only Switch GPS to nav1 and not nav2 dont no why

hmmm thx for your help

**Comment by rug4ever** [comment]
you make a really nice Job many thx

**Comment by rug4ever** [comment]
Hello,

How can i take the NAV_SELECT_SET and than value 1 and value 2 i dont know which variable in the streamdeck Button i must take.

nav select nav1 change gps and nav 

nav select Set can change vor1 and vor2 but dont know what i take in the streamdeck command line 

Sorry for my Bad English 

I hope everywhere can help me

**Comment by nguyenquyhy** [comment]
To switch between GPS and NAV, you can use event TOGGLE_GPS_DRIVES_NAV1.
To switch between NAV1 and NAV2, you can use event AP_NAV_SELECT_SET with parameter 1 or 2 (just added in 0.16).
