### ISSUE TITLE
Nav/com

### ISSUE THREAD

**Issue by maor561** [nguyenquyhy/Flight-Tracker-StreamDeck#48]
Nav/com does not work  with a320 (fs2020) 
Only Squawk working

**Comment by nguyenquyhy** [comment]
Can I have an export of your profile and the log at `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log`?

**Comment by vicentezc** [comment]
Hey! If it may help, I think it's just an issue with the update of the display of the values in MSFS radio panels.
I am using Vatsim, and when I change the COM1, the frequency does change in vPilot, but not in the radio panels in the cockpit.
It is also the same with NAV. With the A32NX mod, when I activate VOR display in ND, it does show the correct VOR and distance, however the MCDU is not updated to reflect the entered frequencies.

**Comment by nguyenquyhy** [comment]
Basically the A320 maintain a lot of internal values, which do only 1 way update to the "real" values that can be read by SimConnect. COM/NAV frequencies are an example of that.
Unfortunately a plugin that uses SimConnect can't fix that.
