### ISSUE TITLE
Spoiler position values

### ISSUE THREAD

**Issue by dodougla** [nguyenquyhy/Flight-Tracker-StreamDeck#49]
SPOILERS HANDLE POSITION
SPOILERS LEFT POSITION
SPOILERS RIGHT POSITION

don't seem to be available to set conditions with-- can these be added?

**Comment by nguyenquyhy** [comment]
`SPOILERS HANDLE POSITION` is already in, and it's value to 0.00 to 1.00, so you need to put 2 decimal number in the your condition (e.g. `SPOILERS HANDLE POSITION==0.00`).

I have added in `SPOILERS LEFT POSITION` and `SPOILERS RIGHT POSITION` (which are also from 0.00 to 1.00) and will release in the next update soon.

**Comment by nguyenquyhy** [comment]
Released in v0.15
