### ISSUE TITLE
Avionics Master Preset Toggle Button has no default label/header

### ISSUE THREAD

**Issue by craigusus** [nguyenquyhy/Flight-Tracker-StreamDeck#50]
- Stream Deck Plugin and MSFS version
Plugin - 0.15 (but been like this since 0.8)
MSFS - latest mandatory version 1.10.8.0
- Description of the issue & expected behaviour
When creating a Preset Toggle Button for Avionics Master, there is no default heading text. But there is in all the other presets.
If I add my own title the text is not in alignment with the other preset buttons
- Steps to reproduce the issue
Drag Preset Toggle Button into an empty button on Stream Deck
Select Avionics Master from the Function drop-down
- Export of profile
[Flight Simulator.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5506099/Flight.Simulator.zip)
- Log files at
[flightstreamdeck20201108.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5506096/flightstreamdeck20201108.log)
- Screenshot
![image](https://user-images.githubusercontent.com/6324863/98461811-335e3880-21a7-11eb-9a3b-491c9708b118.png)
Adding my own title:
![image](https://user-images.githubusercontent.com/6324863/98461859-9b148380-21a7-11eb-80b7-a28639e96f27.png)
![image](https://user-images.githubusercontent.com/6324863/98461867-a798dc00-21a7-11eb-8ab1-2d295641e61f.png)

**Comment by nguyenquyhy** [comment]
It was intentional because it was meant as an ON/OFF button. But since we have the Hide header checkbox now, I'll add in default text.

**Comment by nguyenquyhy** [comment]
Added in version 0.16
