### ISSUE TITLE
Deploying new local version

### ISSUE THREAD

**Issue by vicentezc** [nguyenquyhy/Flight-Tracker-StreamDeck#51]
Hello,

I downloaded the source code as I want to do some modifications of the fonts.

I updated 'ImageLogic.cs' and when I deployed by launching 'deploy.bat;', I can see the folder being created under '%appdata%\Elgato\StreamDeck\Plugins' (I had previously removed the folder I already had).

However, after I open Streak Deck app, I cannot see Flight Tracker actions anymore.
Could you please let me know if I am missing a step?

Thanks!

Vicente

**Comment by nguyenquyhy** [comment]
My guess is that you are running deploy.bat directly under `FlightStreamDeck.AddOn` folder, which wouldn't work. You have to run deploy.bat in your bin folder (e.g. `FlightStreamDeck.AddOn\bin\Debug\netcoreapp3.1`).

If you have already run the deploy.bat in the bin folder and still get this issue, can you share a screenshot of the content inside `%appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin`.

**Comment by vicentezc** [comment]
OK that has solved the problem :-)
I didn't know there was another deploy.bat in the bin folder, I was using the one directly under FlightStreamDeck.AddOn.
Thanks a lot!
