### ISSUE TITLE
Master Alternator state

### ISSUE THREAD

**Issue by WHamdiB** [nguyenquyhy/Flight-Tracker-StreamDeck#53]
Hello, 
I can't find a way to get the feedback value from the master engine alternator. None of the simulation variables work to tell me if the alternator in on or off.

**Comment by rmroc451** [comment]
howdy @WHamdiB!

This is what I have my BATT MAST & ALT switch looking like.  I don't think that the event & value for the individual alternator was working from simconnect.
![image](https://user-images.githubusercontent.com/15070945/99187466-6448eb00-271c-11eb-9a31-882cf0f60ffb.png)

The toggle is unfortunately both the ALT and BATT combined (TOGGLE_MASTER_BATTERY_ALTERNATOR), that one seems to work, and then I just read the (ELECTRICAL_MASTER_BATTERY).

I tend to fly GA, so this is from my C172 panel.  Unsure if this will work for any larger aircraft :)

**Comment by WHamdiB** [comment]
Ok got it, I'll use this instead. Thanks ;)

**Comment by nguyenquyhy** [comment]
I use the following ones:

### Alternator
- Toggle: `TOGGLE_MASTER_ALTERNATOR`
- Feedback: `GENERAL ENG MASTER ALTERNATOR:1`

### Battery
- Toggle: `TOGGLE_MASTER_BATTERY`
- Feedback: `ELECTRICAL MASTER BATTERY`

**Comment by WHamdiB** [comment]
Really nice, its working! Thanks
