### ISSUE TITLE
AP Page problem

### ISSUE THREAD

**Issue by Dede1104** [nguyenquyhy/Flight-Tracker-StreamDeck#54]
Hello, I looked in the issues for a solution but unfortunately I couldn't find anything.

The pluggin is installed well, the profile is imported well but the AP page is practically unusable.

Can anyone help me ?

https://zupimages.net/up/20/46/3cz0.png

**Comment by rmroc451** [comment]
Can we have an export of your profile and the log at %appdata%\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\flightstreamdeck*.log?

A screenshot of what your %appdata%\Elgato\StreamDeck\Plugins looks like as well, in case you somehow have differing multiple versions in there.

**Comment by Dede1104** [comment]
Voici le dossier Appdata : https://zupimages.net/viewer.php?id=20/46/jd8z.png

[flightstreamdeck20201115.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5542532/flightstreamdeck20201115.log)


J'ai joins le fichier log car il est très long

**Comment by rug4ever** [comment]
Hallo,
Mit welcher Maschine fliegst du?
Ich kann Dir später mein Profil schicken und du lädst es dir einfach mal rein. Da funktioniert im Moment alles was möglich ist. 
Bei Msfs funktionieren leider noch einige Befehle nicht so wie es muss. Aber das streamdeck ist der Wahnsinn was alles möglich ist und macht dadurch nochmal viel mehr Spaß

**Comment by Dede1104** [comment]
> Hallo,
> Mit welcher Maschine fliegst du?
> Ich kann Dir später mein Profil schicken und du lädst es dir einfach mal rein. Da funktioniert im Moment alles was möglich ist.
> Bei Msfs funktionieren leider noch einige Befehle nicht so wie es muss. Aber das streamdeck ist der Wahnsinn was alles möglich ist und macht dadurch nochmal viel mehr Spaß

I am currently flying the Cessna 172 Skyhawk.
I tested the profile with the A320 and I have the same problem

**Comment by rug4ever** [comment]
i send you later my Profile.
Pls test that

**Comment by phenDruck** [comment]
Wenn möglich, können Sie mir auch eine Kopie mitteilen? Vielen Dank

**Comment by rug4ever** [comment]
https://github.com/rug4ever/Flight-Tracker-StreamDeck-C172-Profil

**Comment by nguyenquyhy** [comment]
@rug4ever If you don't need to show value (or active/inactive indicator), you can leave Feedback value and Display value empty. You don't need to copy Toggle value to Feedback value.

@Dede1104 An export of your AP profile in Stream Deck would help a lot in determining the issue.
![image](https://user-images.githubusercontent.com/1560418/99203048-3a5ef980-27ec-11eb-91ce-cab6bfb5a6d4.png)

**Comment by rug4ever** [comment]
ok thx for your awesome Tool. its so cool and i play with streamdeck every flight.

**Comment by Dede1104** [comment]
@nguyenquyhy this is my profile 



[MSFS.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5547450/MSFS.zip)

**Comment by nguyenquyhy** [comment]
@Dede1104 From version 0.8, we have replaced all AP buttons with a single Preset Toggle button with more features (including VS and FLC). You'll have to manually replace the button unfortunately. However, the setup process should be straight forward.

**Comment by Dede1104** [comment]
@nguyenquyhy

**Comment by Dede1104** [comment]
@nguyenquyhy oups fail button
 ok no problem.
I just tested @rug4ever profile posted above.
Pages c172 and tbm930 are fonctional without error.
But same issue on page G36

**Comment by nguyenquyhy** [comment]
Yup. That's the old buttons.

**Comment by rug4ever** [comment]
yes i fly only c172 at the Moment and Rest dont change the Buttons  but c172 Profil work on other plane but some Button have to change. ngu pls if you want to share your Profil? maybe i found New Button for my Profil

Thx

**Comment by nguyenquyhy** [comment]
Basically all old AP buttons can be replaced with the new Preset Toggle button. For example, AP Heading can be replace with Preset Toggle button and then choose Heading in the function dropdown.
