### ISSUE TITLE
Stream Deck software freezing

### ISSUE THREAD

**Issue by blindye** [nguyenquyhy/Flight-Tracker-StreamDeck#55]
Yesterday I updated Flight-Tracker from version v0.12 -> v0.15. After that I cannot select any Flight Tracker Buttons from the menu in Stream deck software, it freezes immediately when I drag it in the keypad. All other choices work without problems (.Gamecapture, Hotkey, Open etc).
I uninstalled Stream Deck and deleted Elgato folder from %appdata%\Roaming, but it still doesn't work, even without any profiles.
I even tried to install fresh Stream Deck + v0.12 but not working.

If I load previous profile I can use those buttons ingame, I just can't add more or edit them.

Any idea what to try next?
[flightstreamdeck20201117.log](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5551619/flightstreamdeck20201117.log)

**Comment by rug4ever** [comment]
Hello,

Which Profil do you take?

**Comment by blindye** [comment]
> Hello,
> 
> Which Profil do you take?

It doesn't matter. Clean install with default profile and it'll freeze if I try to add for example a Generic Toggle Button. If I open the numpad profile and click one of the numbers it'll freeze.

**Comment by rug4ever** [comment]
Pls change the usb Port. i think a usb 3.0 its better, for the streamdeck.

**Comment by blindye** [comment]
> Pls change the usb Port. i think a usb 3.0 its better, for the streamdeck.

Oh yeah forgot to mention that I did change it already. And rebooted PC between change.

**Comment by nguyenquyhy** [comment]
Can you share all logs in `%appdata%\Elgato\StreamDeck\logs\`?

**Comment by blindye** [comment]
Here's the logs. I now have all my custom plugins installed and I noticed that the freezing happens with all custom plugins which are located in %appdata%\Elgato, so it's not only Flight-Tracker problem. All plugins that are in Program Files\Elgato works without issues. There might be some oddities in logs since I've tried everything to get it to work, but if you find something please let me know. Otherwise I think this issue can be closed since it's not Flight-Tracker bug.
[logs.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5558004/logs.zip)

**Comment by nguyenquyhy** [comment]
Are you on Windows 10?

For some reason I found this in the log

```
Loading tech.flighttracker.streamdeck.sdPlugin...
The plugin C:\Users\juha\AppData\Roaming\Elgato\StreamDeck\Plugins\tech.flighttracker.streamdeck.sdPlugin\manifest.json is not supported on this machine
Operating System version is 6.2.9200
```

My understanding is that 6.2.9200 is windows 8 or some windows server version, and I don't think MSFS is available for either. Our manifest.json does indicate minimum version of Windows 10, so maybe that's why it is not loaded.

**Comment by blindye** [comment]
Yeah that's because I tried compatibility mode with Windows 8 and Windows 7, that's why I said there might be oddities in the logs :) As you can see that's only in one of the logs.

But yeah, I'm on Windows 10, Version 10.0.19042 Build 19042.

**Comment by blindye** [comment]
Ok got it working, someone from reddit knew that the fix is moving the Stream Deck window to primary display. Never would have guessed that, interesting bug.

**Comment by mwolfe02** [comment]
This appears to still be a bug in Stream Deck app version 6.0.4.18165 as of February 12, 2023.  Moving the Stream Deck window to the primary display still seems to be a good workaround.
