### ISSUE TITLE
problem with AP_NAV_SELECT_SET__2

### ISSUE THREAD

**Issue by rug4ever** [nguyenquyhy/Flight-Tracker-StreamDeck#59]
hello,

its possible if you can add the "AP_NAV_SELECT_SET__1 and 2 
i can change gps to vor1 but not than vor1 vor2 

pla insert this commands 

and mybe the adf swap standby and activ 

thx

**Comment by nguyenquyhy** [comment]
Duplicate of https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/issues/47
