### ISSUE TITLE
adf1_radio_swap

### ISSUE THREAD

**Issue by rug4ever** [nguyenquyhy/Flight-Tracker-StreamDeck#61]
Hello, 

Its possible if you can Import the adf1_radio_swap

and maybe the vor1 and vor2 dec and Inc

and the adf Inc and dec 

long press 100 and short press 10 on adf

and on vor1 Version short press dec 1 and long press 10 and with vor2 the same

Many thx for fast import the nav select variable

**Comment by nguyenquyhy** [comment]
Can you list out the event IDs? I'll add them in.

**Comment by rug4ever** [comment]
ok later this evenning.

great many thx

**Comment by rmroc451** [comment]
I was working on #50, if you want to hold off on implementing the specifics new increase buttons @nguyenquyhy .

The new update would let any action be long press, if configured for it :)

**Comment by rug4ever** [comment]
ADF_100_DEC
ADF_10_DEC
ADF_10_INC
ADF_100_INC

adf1_radio_swap

**Comment by nguyenquyhy** [comment]
The following is already there.
- ADF_100_DEC
- ADF_10_DEC
- ADF_10_INC
- ADF_100_INC

I have added ADF1_RADIO_SWAP. It will be released in the next update.

**Comment by nguyenquyhy** [comment]
Added in v0.17
