### ISSUE TITLE
AP nav select 

### ISSUE THREAD

**Issue by rug4ever** [nguyenquyhy/Flight-Tracker-StreamDeck#62]
only a 1 or 2?
or ap_NAV_SELECT_SET? _1 __1?

in your Info 0.16 you write ab? 

Pls if you can give us a complete command for the NAV_SELECT_SET 

Many thx for your fast change

**Comment by nguyenquyhy** [comment]
Please try to comment on existing issues instead of opening new one 😄. 
This is the setting you are looking for
![image](https://user-images.githubusercontent.com/1560418/99913553-4b9b8f00-2d33-11eb-8351-a48e136d5ec5.png)
