### ISSUE TITLE
v.16 is crashing as soon as I try to edit any Flight Track related button

### ISSUE THREAD

**Issue by Virtual-Chris** [nguyenquyhy/Flight-Tracker-StreamDeck#64]
I was able to get some buttons changed to use the new events for the Airbus, but then Stream Deck configuration app is now crashing any time I try to click a Flight Track plugin related button to view or edit the config for that button.  Profile attached.
[My Profile.zip](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/files/5580983/My.Profile.zip)

**Comment by nguyenquyhy** [comment]
Can you get me the log from `%appdata%\Elgato\StreamDeck\logs\`?

**Comment by Virtual-Chris** [comment]
I was able to fix the issue by uninstalling the Flight Track plugin, installing v.15, verifying that worked, and then updating to v.16.  I seem to be able to edit the Stream Deck buttons normally now.  If it happens again, I'll grab the logs.

**Comment by rmroc451** [comment]
haven't heard any further on this. If it becomes an issue again, we can revisit.
