### ISSUE TITLE
APU BLEED

### ISSUE THREAD

**Issue by Kaledozor** [nguyenquyhy/Flight-Tracker-StreamDeck#67]
Hello guys,

I can't find the APU BLEED function.
I must have problems with my glasses;)

**Comment by rmroc451** [comment]
do either of these work?

https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/search?q=bleed

I don't see a bleed feedback value, but I tend to stick to GA

**Comment by Kaledozor** [comment]
In fact I just want an ON / OFF to finalize the start of the APU

**Comment by rmroc451** [comment]
Ah, I bet it is one of those notorious A320 set events `KEY_BLEED_AIR_SOURCE_CONTROL_SET`, which we don't have implemented.

I'll tinker around with it and see if I can get it to work, and get it in the next release.

**Comment by Kaledozor** [comment]
Thank a lot ;)

**Comment by Cronch** [comment]
Great, thanks!
I was looking for the same functionality. Apu start/off and if possible apu bleed.

**Comment by nguyenquyhy** [comment]
`BLEED AIR SOURCE CONTROL SET` controls only engine bleed and not APU bleed in my tests with the 32NX. I have added it anyway.

Some other APU events such as `APU_STARTER` are already in the plugin.

**Comment by matiaslarson** [comment]
This works with the FBW version using MobiFlight and their custom event, but I don’t know which one the stock 320 uses.

**Comment by matslarson** [comment]
This works with the FBW version using MobiFlight and their custom event, but I don’t know which one the stock 320 uses.

**Comment by nguyenquyhy** [comment]
I have written a more detailed guide here. https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/main/docs/MOBIFLIGHT.md. Please feel free to let me know how it can be improved.
