### ISSUE TITLE
Project file is incomplete. Expected imports are missing

### ISSUE THREAD

**Issue by tankstrr** [nguyenquyhy/Flight-Tracker-StreamDeck#7]
Found this project mentioned on the official MSFS discord.  Getting the above error when I try to reload FlightStreamDeck.AddOn.csproj (solution explorer says "(load failed)".  Full output msg is as follows

\Flight-Tracker-StreamDeck-master\FlightStreamDeck.AddOn\FlightStreamDeck.AddOn.csproj : error  : Project file is incomplete. Expected imports are missing.

**Comment by nguyenquyhy** [comment]
Are you using Visual Studio 2019 with .NET Core 3.1 SDK installed?

**Comment by tankstrr** [comment]
Was using 2017, installing 2019 now, will report back.

**Comment by tankstrr** [comment]
Ok, that worked great.  Can you provide some examples of a working gauge?  i cant seem to get this to work with anything.

**Comment by rmroc451** [comment]
I use it for trim, rpm, vertical speed, IAS, and total fuel.

I'm going to have a PR for some of those, since I added them. Really great work @nguyenquyhy !

![image](https://user-images.githubusercontent.com/15070945/91117860-473cd880-e655-11ea-9556-582a8e331681.png)
