### ISSUE TITLE
Issue with Custom Gauge when Min Value > Max Value

### ISSUE THREAD

**Issue by Virtual-Chris** [nguyenquyhy/Flight-Tracker-StreamDeck#70]
The new custom gauge is great as I love the idea of implementing a trim indicator which is otherwise not visible anywhere except when in external camera view.

However, there's some bug that prevents the trim gauge from working properly when inverting the min and max (min value > max value).  For some reason, the gauge doesn't go full scale.  See attached screen shot where the trim is full down, but the gauge is not near full deflection.

Note "ELEVATOR TRIM POSITION" returns a value from 0.34 (up)
![Untitled](https://user-images.githubusercontent.com/72712231/100190463-2463cf80-2ea3-11eb-9e5c-60459a07eaec.png)
 to -0.34 (down)

**Comment by rmroc451** [comment]
I gotta remove this piglet, I'll fix this up after work today.

https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/master/FlightStreamDeck.Logics/ImageLogic.cs#L260

**Comment by rmroc451** [comment]
@Virtual-Chris This should get fixed with the next release, if the PR makes it in there.

I also add a little padding to the min max value, I use -.5/.5 for my trim gauge, otherwise the chevron interferes with the title label at the top or bottom of the button.

Thanks for logging that bug!
