### ISSUE TITLE
Option to hide a value if the value is out of specific range

### ISSUE THREAD

**Issue by divisions-etch** [nguyenquyhy/Flight-Tracker-StreamDeck#73]
Would be great to have an option to hide a certain value if the value is out of specific range.

Example:
![deck3](https://user-images.githubusercontent.com/4646503/100296472-9d8b2180-2f8c-11eb-8121-f718aef72f20.PNG)

There is my 4 buttons altimeter on the screenshot.
P = Indicated altitude ( 14207 )
L = AP altitude lock ( 26000 )

Basic buttons settings min/max [max value gap fix] values:
Button 4: 30000/40000
Button 3: 20000/30000 [27000]
Button 2: 10000/20000 [17000] 
Button 1: 0/10000 [7000]

I see Indicated altitude and AP altitude lock value on all buttons, but i would like to see the values only on button 3 (AP altitude lock) and button 2 (Indicated altitude):

![deck3_LI (2)](https://user-images.githubusercontent.com/4646503/100296939-c7911380-2f8d-11eb-9ba6-e765e58c7b68.jpg)

All 4 buttons have "display value bottom" set to "INDICATED_ALTITUDE" and would be great to have an option to set "show bottom value only if the value is between 10000 and 20000" or "show bottom value only if the value is greater than 10000"...

**Comment by rmroc451** [comment]
Thats a pretty neat usage... lol

I never thought about stacking them like that!

I can add that option in, neat idea!

**Comment by nguyenquyhy** [comment]
Released in version 0.20
