### ISSUE TITLE
Request to add Transponder State:1 for MSFS2020

### ISSUE THREAD

**Issue by soeren1087** [nguyenquyhy/Flight-Tracker-StreamDeck#74]
**Is your feature request related to a problem? Please describe.**
I have the Problem in MSFS2020 that i can not check/change the Transpoder to diferent modes.

**Describe the solution you'd like**
It should work by adding the value "TRANSPONDER STATE:1" (0=off, 1=Standy, 2=Test, 3=On, 4= Altitude, 5= Ground)

**Describe alternatives you've considered**
I see no alternative or workaround

**Additional context**
No additional context.

**Comment by sn3akz** [comment]
I can't find `TRANSPONDER STATE` in both Event ID and simulation variables. Is this a newly added variable? Where did you find it?

**Comment by soeren1087** [comment]
Thanks for the fast reply.
I found it in spad.next and it worked fine.
It is also explained here:
https://forums.vatsim.net/topic/29069-msfs-2020-transponder-on-does-not-switch-mode-c-in-vpilot/ ( Posted September 27)

It seems to be a special value for the new MSFS2020.

**Comment by nguyenquyhy** [comment]
Added in v0.19

**Comment by soeren1087** [comment]
It works!!! A big big thank you!!!

**Comment by WHamdiB** [comment]
What should be the toggle event and paramater to change the state of the transponder ? Thanks

**Comment by soeren1087** [comment]
Just use the new added value. There is no event.

**Comment by WHamdiB** [comment]
And that should change the state of the transponder from standby to on or alt ?

**Comment by Kaledozor** [comment]
Have you find solution to change statut : standbt/on/alt ?

**Comment by WHamdiB** [comment]
Not really, I did not find the correct commands :/

**Comment by rmroc451** [comment]
The set event isn't implemented in the sdk yet. We only have the variable to read what mode it is for right now.

**Comment by WHamdiB** [comment]
What would be the variable?

**Comment by rmroc451** [comment]
since it is indexed, you'd have to enter either `TRANSPONDER_STATE__1` or `TRANSPONDER STATE:1`.  We do some sanitization on the input to replace spaces with _ and : with __, so either should work.

in my C172 implementation, I toyed with 5 buttons across the deck to have one for each mode and as I rotated the knob, the indicator light slid across them on the deck.

I entered #85 yesterday to add the request to see if we can stack feedbacks and trigger certain images based on what one it finds.

**Comment by WHamdiB** [comment]
I tried with the index but any state trigger the light. I'll dig more into it in a few days. Thanks a lot for your help.

**Comment by nicolasaujoux** [comment]
Sorry to dig up an old post,  but have you managed to make it work ? I am probably missing something here but i tried a lot of different combinations without success. My last guess is that it should work when setting XPNDR_SET in toogle event and TRANSPONDER STATE:1 in toogle parameter ?

Thanks for the help

**Comment by WHamdiB** [comment]
Well, I used a keyboard shortcut and did not dig it up yet. I'll may try again soon !
