### ISSUE TITLE
Generic gauge does not display value if header field is empty

### ISSUE THREAD

**Issue by dflachbart** [nguyenquyhy/Flight-Tracker-StreamDeck#79]
I was trying to get a generic gauge for elevator trim set up (latest v0.19), and couldn't get it to display any other value than '0'. Eventually I figured out that you **have** to put a string into the `Header` (same for `Header Bottom`) field, once I did that the gauge started working.

It even works when just putting a blank space into the entry field (if you don't want any label displayed), so I think a completely empty entry should be handled the same way, unless this behavior is somehow intended (but then it would help to mention this in the documentation).

**Comment by rmroc451** [comment]
It is in the documentation, if you don't add a header it won't show that section of the gauge (top or bottom). :) Check the user guide update with this [feature's](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/commit/7ef9caed2bb7d7641b7399bdcd0bcf4c0da517c6#diff-995a165dac255dc48d7001991d812a9ecbdf85e07d44df17f614cd37dd8b2ae8) release :)

Thanks for the feedback, but I think we will be leaving this as is for now.

**Comment by dflachbart** [comment]
>> It is in the documentation, if you don't add a header it won't show that section of the gauge (top or bottom). :) Check the user guide update with this feature's release :)

Ah sorry, failed to look at the documentation changes, perfect! And thanks for the explanation regarding the functionality, makes totally sense.
