### ISSUE TITLE
Gauge will not display output after using an incorrect field value

### ISSUE THREAD

**Issue by jplewis01** [nguyenquyhy/Flight-Tracker-StreamDeck#81]
Found and tested this issue on version 0.19 of the Flight tracker plugin but I think it existed in the the prior version also.
Summary:  When a generic or Custom Gauge is used and an incorrect field value is placed into a field after that point it is not possible to get the gauge to render gauge output, even after the fields are corrected. It was found that once corrected and the gauge was copied to a different profile then it began to work normally as did the corrected gauge in the original profile.

**Steps to preproduce:** (only lightly tested and not yet fully verified)

- Ensure that Flight Tracker plugin 0.19 is installed in Stream Deck and that a preset toggle works.
- In an empty button location on a profile, Add a generic Gauge.
- Place the following  `FLAPS_HANDLE_PERCENT` into Field `Toggle Value` 
- Enter "FLAPS" into the Header field.

 You will know the control is jammed up up if the Header value does not show up in the button.

Once jammed the control does not display a value even all fields are corrected. 
So far I have found that copying and pasting into a different profile will get the gauge to begin working. I have had mixed results copying to an empty button within the profile.

This situation applies to both Generic and Custom Gauges.
I will continue to test and refine the steps and value and will update the report if new details are gathered.

**Comment by rmroc451** [comment]
I'm going tontry installing .18 as well just to check, but ill work on this right now :)

Thanks for the detailed info.

**Comment by rmroc451** [comment]
@jplewis01 you don't put the value you want displayed into `Toggle value`, you put it in `Display Value`. You sure you had it in the `Toggle Value`?  If no `Display Value` is entered, that would cause the gauge to not render either 👍 

`Toggle Value` is used if you want to have the gauge do something when clicked, like reset the `BAROMETRIC` when clicking an altimeter gauge.

Regardless, the

**Comment by jplewis01** [comment]
I am hard at work creating gauges tonight and hope to be able to say close this or provide really clear steps to reproduce.  I have been learning much more about gauges in the past day or three and think this might have been a lack of understanding on my part.

**Comment by rmroc451** [comment]
No worries, thanks for the feedback!

**Comment by jplewis01** [comment]
I have been able to re-verify the behavior and found it is caused when a bad value is specified in a field that is then corrected but I do not shift focus to a different field to cause the new value (corrected) to be saved. This field save and validate behavior is already called out as a potential issue, and thus the original observation and report can be classified as "not a bug - user input error,"
