### ISSUE TITLE
Ability to make a range of values trigger the indicator light on a button

### ISSUE THREAD

**Issue by slemson** [nguyenquyhy/Flight-Tracker-StreamDeck#83]
I'm trying to map a button to the A320's throttle that lights up specifically when the throttle is in the "Climb" setting.  Simconnect sees this begin at 89%.  The problem is, 89.xx is also a possible value.  So if I set the feedback value to 
"GENERAL ENG THROTTLE LEVER POSITION:1==89" it doesn't light up.  If I set it to ">=89" it does, but I want it to go off again if it goes 90 or above.  So I really need a range like ">=89 AND <90" but I can't see how to do this.

**Comment by sn3akz** [comment]
Did you try `&&` instead of `AND`?

**Comment by rmroc451** [comment]
I dont remember if we allowed multiple conditions, we can take a look.

**Comment by sn3akz** [comment]
I believe it was on the todo list :)

**Comment by rmroc451** [comment]
"Todo" yeah, we'll get to it eventually

**Comment by nguyenquyhy** [comment]
For `GENERAL ENG THROTTLE LEVER POSITION`, you can now use `GENERAL ENG THROTTLE LEVER POSITION~89` to match the climb setting. Operator `~` is released in v0.31.

And I have create a new issue to track generic boolean & math support #224.
