### ISSUE TITLE
Procedure for upgrading to newest version

### ISSUE THREAD

**Issue by Jovian657** [nguyenquyhy/Flight-Tracker-StreamDeck#84]
I would like to upgrade from v0.18 to v0.20. Is there a recommended procedure to upgrade without loosing current button profiles? Thanks!

**Comment by rmroc451** [comment]
Updating doesn't touch the profiles folder.  You are safe.

If you want to be super safe, copy your profiles folder in the elgato appdata folder, and then update.

**Comment by Jovian657** [comment]
@rmroc451 Thank you. I updated to v0.20 by installing "over the top" of v0.18 with no problems.
