### ISSUE TITLE
ITT in ºC

### ISSUE THREAD

**Issue by Crunchmeister1** [nguyenquyhy/Flight-Tracker-StreamDeck#87]
It would be nice to have ITT temp in ºC like we see on our MFDs rather than a meaningless ºR. 

Should be pretty easy to convert that in the background and present a unit that's actually useful.

ºC = (°R − 491.67) × 5/9

**Comment by nguyenquyhy** [comment]
I put ITT in Rankine as the default unit. But I really wonder if anyone would use the unit. I am thinking of changing it to Celsius too as many are asking for that.

**Comment by rmroc451** [comment]
@nguyenquyhy do we have to do some more advanced conversion on it, as it comes from the sim as Rankine?

**Comment by Crunchmeister1** [comment]
Rankine is the default value that the sim puts out, so understandable. It's just not a value that "means anything" in terms of what the temps are in the planes. No plane uses that unit on its readouts. It's always converted to the far more relatable ºC.

I like having certain gauges on my Stream Deck since I don't always have them readily in view in game. It's nice to be able to glance down at the SD and make sure I'm not overcooking my turbines vs having to change my view in game.  I'm sure others would find this useful as well. 

That said, it's certainly not a high priority thing. If you can implement it, great. If not, I'm sure no one will be heartbroken either.

**Comment by nguyenquyhy** [comment]
@rmroc451 My guess is we just need to change the unit when we register the variable and let SimConnect handle the conversion. That works with many other variables, so I would expect that works with ITT too, but honestly I haven't tried yet. That would be a 1 line change.

**Comment by rmroc451** [comment]
I'll tinker tonight if you don't get to it first. I didn't think they did conversion in the simconnect library.

If so, we can do the lb/kg gal/liters updates too (which I have been avoiding like the plague)

**Comment by rmroc451** [comment]
> @rmroc451 My guess is we just need to change the unit when we register the variable and let SimConnect handle the conversion. That works with many other variables, so I would expect that works with ITT too, but honestly I haven't tried yet. That would be a 1 line change.

holy ****, that worked.  I'll PR some quick unit changes for ITT and Exhaust until we can get a more solid solution for specifying units in place.

**Comment by sn3akz** [comment]
> holy ****, that worked.

That isn't that surprising :) We just took the default values when registering the variables, but you should be able to convert it to practically anything. The same with speed and/or distance variables. You can let them return in ft, m, km, mm NM, sm, etc.

**Comment by nguyenquyhy** [comment]
Done in v0.21
