### ISSUE TITLE
pls give a Screenshots From your Setup Buttons on streamdeck 

### ISSUE THREAD

**Issue by rug4ever** [nguyenquyhy/Flight-Tracker-StreamDeck#89]
I have a many Buttons Programm with many hour to inverst. 

I can give Screenshots with the Infos From the streamdeck Button variable. everywhere have interessting From the Screenshot? 

maybe want to send everywhere himself Button Setup From streamdeck. 

I think have a complete Setup From c172 garmin 1000 

or give everywhere the Setups Profil copy share here.

**Comment by nguyenquyhy** [comment]
Are you using custom ON/OFF images? If so, it would be more beneficial to share the profile export once I finish a new feature for image embedding. Right now the profile stores only the path to your images on your disk, so if you export the profile, others have to get your images separately and put in the same path, which is not convenient.

I can update you here once the feature is released.

**Comment by rmroc451** [comment]
I'm going to move this into the new discussion area, since there really isn't anything actionable on this.
