### ISSUE TITLE
Comparison values would be nice

### ISSUE THREAD

**Issue by SnugglePilot** [nguyenquyhy/Flight-Tracker-StreamDeck#9]
I'm looking at `FUEL TANK SELECTOR:1` which reports a value back depending on the currently selected element.

I would love to be able to enter `FUEL TANK SELECTOR:1==16` or something similar to convert the reported value to a bool (so we can utilize the green-light on the button).

**Comment by nguyenquyhy** [comment]
I'll look into adding some expression evaluation for this.

**Comment by rmroc451** [comment]
@nguyenquyhy / @nguyenquyhy, I'm feeling up for this challenge. So I'm working on this this afternoon, there should be a PR out in a while. 👍

**Comment by rmroc451** [comment]
@SnugglePilot, I cut a [pre-release](https://github.com/rmroc451/Flight-Tracker-StreamDeck/releases/tag/0.2.2) on my repo with this in it. Might still not have all the values you are looking for in the enum, but this should get what you want!

@nguyenquyhy, I have this in this [branch](https://github.com/rmroc451/Flight-Tracker-StreamDeck/tree/develop-based/9-comparison-values).  Until we get my master merged into yours, I can't easily cut PRs to you.  Any thought on letting me collab on your repo, so I can create branches? Currently I can't.

**Comment by nguyenquyhy** [comment]
@rmroc451 You can always push my master as a new branch in your repo and branch from there, right?

**Comment by rmroc451** [comment]
@nguyenquyhy good point, let me do that quick.

**Comment by nguyenquyhy** [comment]
Resolve in version 0.4. https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/releases/tag/v0.4
