### ISSUE TITLE
Preset Increase/Decrease Button vor and adf

### ISSUE THREAD

**Issue by rug4ever** [nguyenquyhy/Flight-Tracker-StreamDeck#93]
Hello,

its possible you can in the programm variable 

short button and long button 

adf 

1 and 10 and 100 for adf inc and dec

vor 1 

1 and 10 inc and dec 

vor 2 

1 and 10 inc and dec

**Comment by rmroc451** [comment]
you can get +/- 1 currently with the following events:
`VOR1_OBI_DEC`
`VOR1_OBI_INC`
`VOR2_OBI_DEC`
`VOR2_OBI_INC`

I'm working on the present ones for hold +/- 10.

**Comment by rug4ever** [comment]
thx

I have IT, but 3 Button on my 15 Button Deck vor adf its to much

**Comment by rug4ever** [comment]
great thx for working

**Comment by rug4ever** [comment]
Sorry guys for me its vor 1 and 2 not working with hold 10

**Comment by rmroc451** [comment]
Hasn't been "released" yet, just merged into master. Once Hy releases it, you'll have it.

When we mention things in our PRs, when those get merged, it auto closes them.  Helps with paperwork :)
