### ISSUE TITLE
Some improvements for gauges

### ISSUE THREAD

**Issue by PlumbGlue67** [nguyenquyhy/Flight-Tracker-StreamDeck#94]
- The most important is when using the generic gauge and setting the value precision to 0, the Sub Display Value still have decimals.
Would be great if the precision will be at 0 too. (StreamDeck 01.jpg)

- Another important change to simplify use would be the ability to choose the way the indicator or chevron are moving. Clockwise or counterclockwise for the generic gauge, and up to down or down to up for vertical custom gauge.

- Ability to use the generic gauge look also for a custom gauge. And the ability to have it "flipped" horizontally.(StreamDeck 02.jpg)

- Ability to use a SimConnect Value for title so we have one more displayable value (I have a Stream Deck Mini, only six buttons viewable at the same time)

- Is there a possibility to "slow" the display of some values ?
eg. For Vertical Speed, displaying the average value of the last three seconds. Or dividing the display by 100. Or something else to prevent numbers changing so fast, which makes the reading uncomfortable.

Improvements for custom gauges:
- It takes me a long time to underdtand that Top/Bottom means Left/Right when using vertical gauge. Something to do ?

- When using a vertical custom gauge, the displayed values should be verticals too for short values like 1,2,3 etc... (or a way to choose)

-The Sub Display value is inoperative in vertical position. Have to use Display Value Bottom with the chevron, and it's not completely satisfying.(StreamDeck 03.jpg)

![StreamDeck 01](https://user-images.githubusercontent.com/75927436/102006335-bd5a6d80-3d20-11eb-8eea-4ab5e37978f0.jpg)
![StreamDeck 02](https://user-images.githubusercontent.com/75927436/102006341-cd724d00-3d20-11eb-89dc-fa4d039f84be.jpg)
![StreamDeck 03](https://user-images.githubusercontent.com/75927436/102006347-d400c480-3d20-11eb-8d1c-24885cc56456.jpg)

**Comment by rmroc451** [comment]
> Another important change to simplify use would be the ability to choose the way the indicator or chevron are moving. Clockwise or counterclockwise for the generic gauge, and up to down or down to up for vertical custom gauge.

Check out the 2nd bullet [here](https://github.com/nguyenquyhy/Flight-Tracker-StreamDeck/blob/master/docs/USERGUIDE.md#generic-gauge). Thanks for the feedback and requests!

**Comment by PlumbGlue67** [comment]
Yes. That's what I've done.
My suggestion is to get the same in an easier way, because it's not quite simple to obtain the desired result.
Anyway thanks for the quick answer.

**Comment by nguyenquyhy** [comment]
Since this is a large list of items, I'm splitting it to multiple smaller Issues so I can slot them in multiple releases more easily

> The most important is when using the generic gauge and setting the value precision to 0, the Sub Display Value still have decimals.
> Would be great if the precision will be at 0 too. (StreamDeck 01.jpg)

#436

> Another important change to simplify use would be the ability to choose the way the indicator or chevron are moving. Clockwise or counterclockwise for the generic gauge, and up to down or down to up for vertical custom gauge.

#437

> Ability to use the generic gauge look also for a custom gauge. And the ability to have it "flipped" horizontally.(StreamDeck 02.jpg)

#438

> Ability to use a SimConnect Value for title so we have one more displayable value (I have a Stream Deck Mini, only six buttons viewable at the same time)

#439

>Is there a possibility to "slow" the display of some values ?
> eg. For Vertical Speed, displaying the average value of the last three seconds. Or dividing the display by 100. Or something else to prevent numbers changing so fast, which makes the reading uncomfortable.

#440

> It takes me a long time to underdtand that Top/Bottom means Left/Right when using vertical gauge. Something to do ?

#441

> When using a vertical custom gauge, the displayed values should be verticals too for short values like 1,2,3 etc... (or a way to choose)

#442

> The Sub Display value is inoperative in vertical position. Have to use Display Value Bottom with the chevron, and it's not completely satisfying.(StreamDeck 03.jpg)

#443
