### ISSUE TITLE
Add Support for the Engine Manifold Pressure Variable

### ISSUE THREAD

**Issue by plewis-jama** [nguyenquyhy/Flight-Tracker-StreamDeck#99]
**Is your feature request related to a problem? Please describe.**
Not a problem Per Sie but being able to get this variable value opens up interesting gauge possiblities,

**Describe the solution you'd like**
Currently I cannot find a variable in Structs.cs that returns the manifold pressure.
Prepar3d SIMConnect SDK lists ENG MANIFOLD Pressure:_index_ as an available variable but I have not looked in MSFS SDK yet to see if it is listed there.
I would like to create a Gauge to show the manifold pressure value in inches of Hg. for recip engine aircraft with CSU Propellers e.g. G36 Bonanza. The update mod shows the value in the G36 G1000 BTW.

**Describe alternatives you've considered**
There seems to be no other engine related Variable available at present

**Additional context**
None

**Comment by rug4ever** [comment]
MIXTURE_INCR

MIXTURE_DECR

PROP_PITCH_INCR

PROP_PITCH_DECR

Do you mean that ?

**Comment by Rick111X3** [comment]
I can only support the request. Please give us the variable for the manifold pressure. Sorry for my bad English. Thanks for this wonderful project

**Comment by jplewis01** [comment]
`ENG MANIFOLD Pressure:index`  is the Simconnect variable it is listed in the SDK as responding to read and write and it work in Air Manager 4 when connected to a gauge.

**Comment by nguyenquyhy** [comment]
Would `RECIP ENG MANIFOLD PRESSURE:index` work for you? I have added that in version 0.25.

**Comment by Rick111X3** [comment]
Thanks for inserting. The variable: "RECIP ENG MANIFOLD PRESSURE: index" has the unit Psi. Some aircraft display the manifold pressure in inHg.
Can the variable "ENG MANIFOLD PRESSURE: index" be inserted? This should have the unit inHG. (according to http://www.prepar3d.com/)

Many Thanks

**Comment by jplewis01** [comment]
> Would `RECIP ENG MANIFOLD PRESSURE:index` work for you? I have added that in version 0.25.

Yes this is **exactly** the variable I am asking to have added! TY

Phil

**Comment by dieharder** [comment]
Indeed, in the docs I see:  "ENG MANIFOLD PRESSURE" is Engine manifold pressure inHG, which would be great to have for the Mooney M20R.

Thanks a lot (really great plugin!)

**Comment by nguyenquyhy** [comment]
@dieharder You can change the unit in the latest version, so I guess `RECIP ENG MANIFOLD PRESSURE: index` should already be enough?
